import type { Metadata } from 'next';
import AlphaChronology from '../components/AlphaChronology';
import AlphaPendingInsight from '../components/AlphaPendingInsight';
import ChartFooter from '../components/ChartFooter';
import HistoryPageShell from '../components/HistoryPageShell';
import WindRouteLogic from '../WindRouteLogic';

export const metadata:Metadata={title:'Oceanic Navigation',description:'Five visual arguments about routes, risk, navigation, shipyards, exchange, and coercion.',openGraph:{title:'Oceanic Navigation — How Everything Evolved',description:'The Manila galleon connected Asia and America—and monopoly made the crossing more dangerous.',images:[]},twitter:{card:'summary',title:'Oceanic Navigation — How Everything Evolved',description:'The Manila galleon connected Asia and America—and monopoly made the crossing more dangerous.',images:[]}};
const labels=['The Manila galleon connected Asia and America—and monopoly made the crossing more dangerous','Ocean routes followed winds and currents, not shortest lines','Sailors combined celestial, dead-reckoning, and local knowledge','Shipyards were global production systems','Oceanic exchange reorganized ecologies and coerced labor'];
const events=[
  {year:1,displayYear:'1565–1815',label:'250 years',detail:'The Manila Galleon route linked the Philippines and Mexico for roughly two and a half centuries.',kind:'route chronology'},
  {year:2,displayYear:'From 1593',label:'2 per year',detail:'The Crown legally capped departures from Manila at two galleons per year.',kind:'monopoly rule'},
  {year:3,displayYear:'All voyages',label:'20% failed',detail:'One fifth of Manila-to-Acapulco voyages in the estimation sample failed.',kind:'shipwreck or damaged return'},
  {year:4,displayYear:'On time',label:'17% failed',detail:'The descriptive failure share was lower among on-time departures.',kind:'subgroup share'},
  {year:5,displayYear:'Late',label:'22.5% failed',detail:'The descriptive failure share was higher among late departures.',kind:'subgroup share'},
];
export default function OceanicNavigationPage(){return <HistoryPageShell title="Oceanic Navigation" eyebrow="1400–1815 CE" standfirst="Open-ocean routes joined continents, but every crossing depended on seasons, skilled labor, institutions, and risk." status="draft" progress="2 of 5 insights live" published="August 2026" insightLabels={labels}
  introduction={<><p>Oceanic integration was not a frictionless shrinking of distance. Winds set calendars, navigators combined knowledge systems, shipyards assembled materials and labor, and monopolies shaped which risks people took.</p><p>The five claims move from one exceptionally documented trans-Pacific route to route geometry, navigation, shipbuilding, and the ecological and coercive consequences of connection.</p></>}
  methods={<><p>The opening visual uses Arteaga, Desierto, and Koyama’s universe of Manila-galleon voyages. “Failure” includes ships lost at sea or heavily damaged and forced back to port.</p><p>The on-time and late percentages are descriptive subgroup shares. The paper’s controlled analysis strengthens the association, but this page does not treat timing as the only cause of failure or this route as the whole oceanic world.</p></>}>
  <section className="insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">A legal bottleneck made each trans-Pacific departure unusually valuable—and encouraged dangerous delay and loading.</p><h3>{labels[0]}</h3><p>Asian manufactures crossed to Mexico; silver returned toward Manila. Yet the Crown’s two-ship cap created rents around scarce cargo space.</p><p>Across the Manila-to-Acapulco sample, 20% of voyages failed. Late departures show the higher descriptive failure share.</p></div><div className="viz-card"><div className="viz-title"><div><span>Manila Galleon · route rules and voyage outcomes</span><h4>{labels[0]}</h4></div><small>failure includes wreck or damaged return</small></div><AlphaChronology title="A global route carried monopoly risk" subtitle="Chronology, legal cap, and observed shares" events={events}/><ChartFooter source="Arteaga, Desierto, and Koyama (2024)" note="Failure means shipwreck or a heavily damaged return to port. Subgroup shares do not by themselves isolate causality." dataHref="/data/oceanic-navigation/20260831-alpha1/manila-galleon-risk.csv"/></div></section>
  <section className="insight"><div className="insight-copy"><span className="insight-number">02</span><p className="claim">The fastest sailing route could begin as a detour—or a wait.</p><h3>{labels[1]}</h3><p>Prevailing winds gave the same ocean different directions at different latitudes and seasons. Eastbound Pacific galleons sought westerlies; westbound ships used the trades.</p><p>Across the Indian Ocean, monsoon reversal turned routes into calendars. Select a passage to see the wind logic that a straight line leaves out.</p></div><div className="viz-card"><div className="viz-title"><div><span>Wind regime → sailing route</span><h4>{labels[1]}</h4></div><small>four route logics · no reconstructed tracks</small></div><WindRouteLogic/><ChartFooter source="NOAA Physical Sciences Laboratory; Philippe Beaujard (2019); Giuseppe Marcocci (2025)" note="The schematic preserves documented wind regimes and sailing windows. It does not reconstruct exact tracks, distances, speeds, traffic, or one route used by every voyage." dataHref="/data/oceanic-navigation/20260901-winds1/wind-shaped-routes.csv"/></div></section>
  <AlphaPendingInsight number="03" title={labels[2]} question="How did latitude, dead reckoning, pilots’ books, instruments, and indigenous knowledge work together at sea?"/>
  <AlphaPendingInsight number="04" title={labels[3]} question="Which forests, fibers, metals, artisans, financiers, and coerced workers had to converge before a ship could sail?"/>
  <AlphaPendingInsight number="05" title={labels[4]} question="Where did crops, pathogens, extraction, slavery, and imperial violence travel with commercial exchange?"/>
  </HistoryPageShell>}
