import type { Metadata } from 'next';
import AlphaChronology from '../components/AlphaChronology';
import AlphaPendingInsight from '../components/AlphaPendingInsight';
import ChartFooter from '../components/ChartFooter';
import HistoryPageShell from '../components/HistoryPageShell';
import AfricanGatewayNetworks from '../AfricanGatewayNetworks';

export const metadata:Metadata={title:'African States and Trade',description:'Five visual arguments about trade corridors, Nile states, Swahili ports, Great Zimbabwe, and plural political scale.',openGraph:{title:'African States and Trade — How Everything Evolved',description:'West African rulers turned trade corridors into revenue.',images:[]},twitter:{card:'summary',title:'African States and Trade — How Everything Evolved',description:'West African rulers turned trade corridors into revenue.',images:[]}};
const labels=['West African rulers turned trade corridors into revenue','Northeast African states turned geographic breaks into political gateways','Swahili cities were African ports in an Indian Ocean system','Great Zimbabwe converted cattle, gold, and distance into authority','African political scale followed more than one path'];
const events=[
  {year:1,displayYear:'1 dinar',label:'Salt entering Ghana',detail:'Al-Bakri reports one gold dinar due on every donkey-load of salt entering the country.',kind:'reported tariff'},
  {year:2,displayYear:'2 dinars',label:'Salt leaving Ghana',detail:'The same salt load incurred two dinars when carried onward out of the country.',kind:'reported tariff'},
  {year:3,displayYear:'5 mithqals',label:'Copper load',detail:'A load of copper carried a reported due of five mithqals.',kind:'reported tariff'},
  {year:4,displayYear:'10 mithqals',label:'Other merchandise',detail:'Other merchandise carried a reported due of ten mithqals.',kind:'reported tariff'},
  {year:5,displayYear:'Royal claim',label:'Rare gold nuggets',detail:'Al-Bakri says rare nuggets were reserved to the king while gold dust remained in circulation.',kind:'reported rule'},
];
export default function AfricanStatesPage(){return <HistoryPageShell title="African States and Trade" eyebrow="300–1500 CE" standfirst="States grew through river valleys, highlands, cattle landscapes, ports, mines, and long-distance corridors—not one African template." status="draft" progress="2 of 5 insights live" published="August 2026" insightLabels={labels}
  introduction={<><p>Pre-industrial Africa contained large territorial states, commercial city networks, sacred kingships, pastoral confederations, and political systems whose scale did not map neatly onto modern borders.</p><p>The five claims begin with a documented Ghanaian revenue system, then move through Nile connections, Swahili urbanism, Great Zimbabwe, and the continent’s plural routes to political coordination.</p></>}
  methods={<><p>The first visual transcribes al-Bakri’s eleventh-century report as translated and annotated by Levtzion and Hopkins. Al-Bakri wrote in Iberia from earlier information; the dues are reported rules, not audited receipts or trade volumes.</p><p>The second comparison keeps four unlike mechanisms separate. Geography created opportunities, but the political gateways depended on cities, ports, pacts, courts, and institutions; routes alone did not create states.</p></>}>
  <section className="insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">A salt load reportedly paid once entering Ghana—and twice as much when carried onward.</p><h3>{labels[0]}</h3><p>The Ghanaian court did not need to own every mine or caravan to profit from exchange. Al-Bakri describes fixed dues on salt, copper, and other merchandise, plus a royal claim on rare gold nuggets.</p><p>The key state technology was the corridor: authority over commercial centers and movement could convert distant ecological differences into revenue.</p></div><div className="viz-card"><div className="viz-title"><div><span>Ghana · al-Bakri’s 11th-century account</span><h4>{labels[0]}</h4></div><small>reported rules · source units retained</small></div><AlphaChronology title="The court taxed goods at trade interfaces" subtitle="One written account, not a revenue ledger" events={events}/><ChartFooter source="al-Bakri, translated in Levtzion & Hopkins (1981)" note="Reported tariffs are not observed collections or trade volumes. Dinars and mithqals are not treated as interchangeable or converted into modern money." dataHref="/data/african-states/20260831-alpha1/ghana-trade-dues.csv"/></div></section>
  <section className="insight"><div className="insight-copy"><span className="insight-number">02</span><p className="claim">River cataracts, confluences, highlands, and ports became useful when states built institutions around them.</p><h3>{labels[1]}</h3><p>Kush, Makuria, Alwa, and Aksum did not sit on one African highway. They occupied different joints: overland routes around the Nile, a negotiated Egyptian frontier, the Blue–White Nile confluence, and a difficult highland-to-port connection.</p><p>The recurring state technology was the gateway—joining ecological and political zones without erasing the distance between them.</p></div><div className="viz-card"><div className="viz-title"><div><span>Four gateways · late antiquity to 1500</span><h4>{labels[1]}</h4></div><small>selected mechanisms · not a traffic model</small></div><AfricanGatewayNetworks/><ChartFooter source="UNESCO; Spaulding (1995); Drzewiecki et al. (2021); British Museum" note="Selected cases show distinct geographic and institutional links. They do not measure route traffic, customs revenue, complete borders, or exclusive state control." dataHref="/data/african-states/20260831-gateways1/northeast-african-gateways.csv"/></div></section>
  <AlphaPendingInsight number="03" title={labels[2]} question="What do archaeology, language, architecture, and imported goods show about African urban institutions and Indian Ocean connections?"/>
  <AlphaPendingInsight number="04" title={labels[3]} question="How did cattle, gold production, tribute, stone building, and settlement hierarchy connect the plateau to the coast?"/>
  <AlphaPendingInsight number="05" title={labels[4]} question="Which combinations of cities, courts, age systems, clans, ritual authority, trade, and armies produced durable coordination without one state form?"/>
  </HistoryPageShell>}
