import type { Metadata } from 'next';
import IronAdoptionClocks from '../IronAdoptionClocks';
import IronFuelExperiments from '../IronFuelExperiments';
import IronQualityLab from '../IronQualityLab';
import IronMobilizationLedger from '../IronMobilizationLedger';
import IronInstitutionCircuits from '../IronInstitutionCircuits';
import EvidencePanel from '../components/EvidencePanel';
import HistoryPageShell from '../components/HistoryPageShell';
import ChartFooter from '../components/ChartFooter';

export const metadata:Metadata={title:'The Iron Age transformation',description:'Why iron spread through ore fuel furnaces skills workshops and institutions—not as an instantly superior metal.',openGraph:{title:'The Iron Age transformation — How Everything Evolved',description:'First iron was not the same thing as an iron economy.',images:[]},twitter:{card:'summary',title:'The Iron Age transformation — How Everything Evolved',description:'Five regional clocks for first evidence and sustained adoption.',images:[]}};

export default function IronAgePage(){return <HistoryPageShell
  title="The Iron Age transformation"
  eyebrow="2000–400 BCE · fuel · skill · scale"
  standfirst="Iron was abundant in the ground. Making it useful, repeatable, and ordinary was the historical achievement."
  status="reviewed"
  progress="5 of 5 insights live"
  published="August 2026"
  introduction={<><p>There is no single date when humanity “discovered iron.” Meteoric iron was worked long before ore-based production. Limited smelted iron then appeared centuries before it became common. The familiar Iron Age is therefore not an invention date; it is a family of regional transitions in production, use, and social organization.</p><p>That transition was not simply a better material beating a worse one. Early wrought iron could be soft and inconsistent. Bronze remained useful, recyclable, prestigious, and often technologically sophisticated. Iron became transformative when ore preparation, charcoal, furnace control, bloom consolidation or casting, smithing, and demand could be reproduced together.</p><p>This page begins with Western Eurasia and the North China Plain because their evidence supports a bounded comparison. It does not assign every society to a universal stage or imply that societies without an iron economy were technologically behind.</p></>}
  insightLabels={['Iron became transformative only when production became repeatable','Furnace control mattered more than charcoal alone','Hardness did not make iron usable','Institutions—not cheaper metal—made armies scale','Iron production scaled through households, markets, and states']}
  methods={<><p>The adoption comparison separates earliest or limited attestation from sustained regional adoption. Its bars are broad source-synthesis windows, not annual observations, confidence intervals, diffusion speeds, output series, or market shares. Definitions differ by region and are kept visible in the downloadable rows.</p><p>The five adoption lenses are dependencies, not scores. They distinguish prior bronze traditions, resources and charcoal, furnace pathways, smithing and product quality, and institutional context. Missing direct evidence is never converted into zero.</p><p>The fuel comparison uses eleven published modern experimental runs. Reported ore, charcoal, and bloom masses remain tied to individual furnace programs. Charcoal per kilogram of bloom is transparent arithmetic, not a historical efficiency estimate; zero and trace blooms remain categories.</p><p>The quality comparison uses four bloom samples and four nonstandard bars forged from one quarter of each bloom in Stepanov and colleagues&apos; experimental program. Hardness means, sample counts, standard deviations, SEM–EDS chemistry, microstructure, and recorded forgeability remain separate. These paired samples do not estimate average ancient iron or weapon performance, and hardness is not converted into toughness, lethality, or a superiority score.</p><p>The mobilization ledger intentionally combines unlike evidence without placing it on one scale. Kadesh preserves four named divisions and a modern campaign-total inference; the pre-Roman civitas case is qualitative and receives no headcount. Only Taylor&apos;s Carthaginian and Roman strategic-deployment models share an author, war context, and scope, so only they receive proportional bars. No metal find, equipment estimate, or kilogram value becomes an army total.</p><p>The production-institutions comparison is categorical. Fort Shalmaneser, Sangis and Vivungi, La Tène Bohemia, Han Lingnan, and Meroe preserve different mixtures of excavation, scientific analysis, administrative text, chronology, and regional interpretation. Their inputs, production units, coordinating institutions, distribution paths, and visible evidence are separated instead of collapsed into output or centralization.</p><p>The Near Eastern synthesis follows Erb-Satullo&apos;s review. The experimental series follow Humphris and colleagues at Meroe, Helmreich and colleagues at Sehnde, and Stepanov and colleagues on smelter decision-making. None is treated as an exact ancient recipe, a forest-loss model, or a basis for annual output.</p><p>Devereaux&apos;s process synthesis supplies the general production dependency chain and his pre-Roman army synthesis frames cheaper iron as one factor alongside social mobilization and pressure from states. Taylor&apos;s comparative manpower models supply the two Punic War maxima. These arguments remain source-specific rather than a universal technological law.</p><EvidencePanel page="iron-age"/></>}
>
  <section className="insight iron-adoption-insight"><div className="insight-copy"><span className="insight-number">01</span><h3>Iron became transformative only when production became repeatable</h3><p>Limited smelted iron appeared centuries before iron objects became common. In the Near East, early second-millennium evidence preceded wider adoption after 1200 BCE; other regions followed different schedules and technological paths.</p><p>Cyprus and the Aegean adopted utilitarian iron while keeping active bronze traditions. Central Europe expanded production unevenly. North China developed cast iron through a route unlike western bloomery practice.</p><p>The transition came when ore, charcoal, furnace control, smithing, exchange, and institutions formed a repeatable system. Discovery produced rare objects; reproducibility produced an Iron Age.</p></div><div className="viz-card iron-adoption-viz"><div className="viz-title"><div><span>First evidence and wider adoption across five regions</span><h4>Iron became transformative only when production became repeatable</h4></div></div><IronAdoptionClocks/><ChartFooter source="Regional archaeological syntheses led by Erb-Satullo’s Near Eastern review" note="Thin and thick bars preserve broad source windows for limited evidence and wider adoption. They are not annual observations, diffusion speeds, output series, or market shares." dataHref="/data/iron-age/20260830-adoption1/iron-adoption-windows.csv" /></div></section>
  <section className="insight iron-fuel-insight"><div className="insight-copy"><span className="insight-number">02</span><h3>Furnace control mattered more than charcoal alone</h3><p>Bloomery iron required charcoal, but fuel could not compensate for wet lining, blocked tuyeres, unsuitable ore, poor airflow, or badly controlled slag.</p><p>Four full-scale Meroe experiments used 71–105 kilograms of charcoal and produced outcomes from a 4.325-kilogram bloom to no recognizable bloom. Seven Lower Saxony experiments used 14.5–30 kilograms and recovered 0.02–2.4 kilograms.</p><p>The experiments break the simple equation “forest in, iron out.” Skill, furnace design, ore, airflow, timing, and later smithing determined whether fuel became usable metal.</p></div><div className="viz-card iron-fuel-viz"><div className="viz-title"><div><span>Eleven experimental smelts and their reported outcomes</span><h4>Furnace control mattered more than charcoal alone</h4></div></div><IronFuelExperiments/><ChartFooter source="Humphris et al. at Meroe and Helmreich et al. at Sehnde" note="These are individual modern experiments, not ancient productivity estimates. Ratios are arithmetic within each run; zero and trace blooms remain categorical." dataHref="/data/iron-age/20260830-fuel1/iron-smelting-experiments.csv" /></div></section>
  <section className="insight iron-quality-insight"><div className="insight-copy"><span className="insight-number">03</span><h3>Hardness did not make iron usable</h3><p>One bloom could contain ferritic iron, carburized zones, slag, pores, sulfur-rich inclusions, and internal gradients. Forging added heating, hammering, oxidation, cracking, and material loss.</p><p>FEXP-6 produced the hardest mean bloom at 139 HV, yet sulfur-rich inclusions made it brittle and difficult to forge; its bar averaged 113 HV. FEXP-5 began with the softest mean bloom at 84 HV but worked better.</p><p>Useful iron depended on controlling a bundle of properties for an intended object. Maximizing one hardness number could make the material worse.</p></div><div className="viz-card iron-quality-viz"><div className="viz-title"><div><span>Hardness, chemistry, structure, and forging in four paired experiments</span><h4>Hardness did not make iron usable</h4></div></div><IronQualityLab/><ChartFooter source="Stepanov et al.’s paired bloom-and-forged-bar experiments" note="Hardness means describe selected metallographic samples, not whole-object toughness or weapon performance. Sample counts and standard deviations remain in the readout and data." dataHref="/data/iron-age/20260830-quality1/iron-quality-experiments.csv" /></div></section>
  <section className="insight iron-mobilization-insight"><div className="insight-copy"><span className="insight-number">04</span><h3>Institutions—not cheaper metal—made armies scale</h3><p>Cheaper swords and spearheads could help elites arm more clients, but broader mobilization still required obligations, recruitment, food, transport, command, and replacement.</p><p>Ramesses II approached Kadesh with four named divisions centuries before iron became ordinary. During the Second Punic War, comparable models put Carthage near 170,000 deployed troops and Rome near 185,000.</p><p>The shared mechanism was institutional capacity to assemble and sustain people. Metal changed equipment costs at the margin; it did not create the levy or replace its losses.</p></div><div className="viz-card iron-mobilization-viz"><div className="viz-title"><div><span>Equipment, recruitment, supply, and replacement across four cases</span><h4>Institutions—not cheaper metal—made armies scale</h4></div></div><IronMobilizationLedger/><ChartFooter source="Devereaux’s mobilization synthesis and Taylor’s Punic War manpower models" note="Only Rome and Carthage share an author, war, and strategic scope and therefore receive comparable bars. Metal finds never become army headcounts." dataHref="/data/iron-age/20260830-mobilization1/iron-mobilization-cases.csv" /></div></section>
  <section className="insight iron-institutions-insight"><div className="insight-copy"><span className="insight-number">05</span><h3>Iron production scaled through households, markets, and states</h3><p>Fort Shalmaneser concentrated workshops, magazines, barracks, inspection, and royal administration. Sangis and Vivungi instead linked several small household production units to a central smithing site.</p><p>La Tène Bohemia relied on distribution networks; Han policy used a state monopoly with a documented frontier gap; Meroe sustained a production landscape around a royal city for more than a millennium.</p><p>Iron scaled through arsenals, households, exchange, offices, and urban districts. State control was one durable architecture, not the inevitable destination of production.</p></div><div className="viz-card iron-institutions-viz"><div className="viz-title"><div><span>Five production circuits from household networks to royal arsenals</span><h4>Iron production scaled through households, markets, and states</h4></div></div><IronInstitutionCircuits/><ChartFooter source="Five archaeological and textual production studies from Assyria to Meroe" note="Inputs, production, coordination, distribution, and surviving evidence remain categorical. The cases are not ranks, stages, output estimates, or a common centralization score." dataHref="/data/iron-age/20260830-institutions1/iron-production-institutions.csv" /></div></section>
</HistoryPageShell>}
