import type { Metadata } from 'next';
import IronAdoptionClocks from '../IronAdoptionClocks';
import IronFuelExperiments from '../IronFuelExperiments';
import IronQualityLab from '../IronQualityLab';
import IronMobilizationLedger from '../IronMobilizationLedger';
import EvidencePanel from '../components/EvidencePanel';
import HistoryPageShell from '../components/HistoryPageShell';

export const metadata:Metadata={title:'The Iron Age transformation',description:'Why iron spread through ore fuel furnaces skills workshops and institutions—not as an instantly superior metal.',openGraph:{title:'The Iron Age transformation — How Everything Evolved',description:'First iron was not the same thing as an iron economy.',images:[]},twitter:{card:'summary',title:'The Iron Age transformation — How Everything Evolved',description:'Five regional clocks for first evidence and sustained adoption.',images:[]}};

const Placeholder=({number,claim,title,copy}:{number:string;claim:string;title:string;copy:string})=><section className="insight insight-placeholder"><div className="insight-copy"><span className="insight-number">{number}</span><p className="claim">{claim}</p><h3>{title}</h3><p>{copy}</p><span className="status status-research">research · visual in development</span></div></section>;

export default function IronAgePage(){return <HistoryPageShell
  title="The Iron Age transformation"
  eyebrow="2000–400 BCE · fuel · skill · scale"
  standfirst="Iron was abundant in the ground. Making it useful, repeatable, and ordinary was the historical achievement."
  status="draft"
  progress="4 of 5 insights live"
  published="August 2026"
  introduction={<><p>There is no single date when humanity “discovered iron.” Meteoric iron was worked long before ore-based production. Limited smelted iron then appeared centuries before it became common. The familiar Iron Age is therefore not an invention date; it is a family of regional transitions in production, use, and social organization.</p><p>That transition was not simply a better material beating a worse one. Early wrought iron could be soft and inconsistent. Bronze remained useful, recyclable, prestigious, and often technologically sophisticated. Iron became transformative when ore preparation, charcoal, furnace control, bloom consolidation or casting, smithing, and demand could be reproduced together.</p><p>This page begins with Western Eurasia and the North China Plain because their evidence supports a bounded comparison. It does not assign every society to a universal stage or imply that societies without an iron economy were technologically behind.</p></>}
  insightLabels={['Adoption had two clocks','The charcoal constraint','Quality was made','Iron and mass armies','States scaled production']}
  methods={<><p>The adoption comparison separates earliest or limited attestation from sustained regional adoption. Its bars are broad source-synthesis windows, not annual observations, confidence intervals, diffusion speeds, output series, or market shares. Definitions differ by region and are kept visible in the downloadable rows.</p><p>The five adoption lenses are dependencies, not scores. They distinguish prior bronze traditions, resources and charcoal, furnace pathways, smithing and product quality, and institutional context. Missing direct evidence is never converted into zero.</p><p>The fuel comparison uses eleven published modern experimental runs. Reported ore, charcoal, and bloom masses remain tied to individual furnace programs. Charcoal per kilogram of bloom is transparent arithmetic, not a historical efficiency estimate; zero and trace blooms remain categories.</p><p>The quality comparison uses four bloom samples and four nonstandard bars forged from one quarter of each bloom in Stepanov and colleagues&apos; experimental program. Hardness means, sample counts, standard deviations, SEM–EDS chemistry, microstructure, and recorded forgeability remain separate. These paired samples do not estimate average ancient iron or weapon performance, and hardness is not converted into toughness, lethality, or a superiority score.</p><p>The mobilization ledger intentionally combines unlike evidence without placing it on one scale. Kadesh preserves four named divisions and a modern campaign-total inference; the pre-Roman civitas case is qualitative and receives no headcount. Only Taylor&apos;s Carthaginian and Roman strategic-deployment models share an author, war context, and scope, so only they receive proportional bars. No metal find, equipment estimate, or kilogram value becomes an army total.</p><p>The Near Eastern synthesis follows Erb-Satullo&apos;s review. The experimental series follow Humphris and colleagues at Meroe, Helmreich and colleagues at Sehnde, and Stepanov and colleagues on smelter decision-making. None is treated as an exact ancient recipe, a forest-loss model, or a basis for annual output.</p><p>Devereaux&apos;s process synthesis supplies the general production dependency chain and his pre-Roman army synthesis frames cheaper iron as one factor alongside social mobilization and pressure from states. Taylor&apos;s comparative manpower models supply the two Punic War maxima. These arguments remain source-specific rather than a universal technological law.</p><EvidencePanel page="iron-age"/></>}
>
  <section className="insight iron-adoption-insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">First iron was not an Iron Age. In some regions, centuries separated rare objects from sustained production.</p><h3>Iron adoption had two clocks</h3><p>In the Near East, current evidence points to limited extractive iron metallurgy in Anatolia during the early second millennium BCE. Yet iron artifacts only appear regularly after 1200 BCE, and wider adoption extended well into the first millennium. Discovery did not solve reproducibility.</p><p>Cyprus and the Aegean moved earlier toward utilitarian iron while keeping active bronze traditions. Central Europe remained largely bronze-centered while iron was rare, then saw rapid but uneven early Hallstatt expansion. On the North China Plain, cast iron appears by the eighth century BCE and grows through a technological route unlike western bloomery iron.</p><p>The common mechanism is not one migrating secret. Iron became ordinary where ore and charcoal, furnace control, smithing, exchange, and institutions formed a repeatable production system. That is why first object, first workshop, and Iron Age belong on different clocks.</p><a className="source-link" href="https://ora.ox.ac.uk/objects/uuid%3A8b406295-a086-48b1-aa7a-f66c4c035b07">Read the open Near Eastern review ↗</a></div><div className="viz-card iron-adoption-viz"><div className="viz-title"><div><span>Five regions · two clocks · five dependencies</span><h4>When did iron become ordinary?</h4></div><small>2000–400 BCE · no adoption score</small></div><IronAdoptionClocks/><p className="viz-note"><b>Method:</b> Select a region, then a dependency. Thin bars mark first or limited evidence; thick bars mark wider adoption. Neither is an annual series.</p></div></section>
  <section className="insight iron-fuel-insight"><div className="insight-copy"><span className="insight-number">02</span><p className="claim">Iron required charcoal—but more charcoal did not mechanically produce more usable iron.</p><h3>The forest was part of the furnace</h3><p>Ore is only the visible resource. Bloomery iron also required prepared charcoal, sustained airflow, a workable furnace, controlled slag, and skilled decisions over hours. Fuel supplied heat and the carbon monoxide that reduced iron oxides, but it could not compensate automatically for wet lining, blocked tuyeres, unsuitable ore, or a poorly controlled atmosphere.</p><p>Published reconstructions make this visible. In four full-scale Meroe experiments, 71–105 kilograms of charcoal produced outcomes ranging from a 4.325-kilogram bloom to no recognizable bloom. Seven reusable-shaft experiments in Lower Saxony used 14.5–30 kilograms of charcoal and recovered 0.02–2.4 kilograms of bloomery iron.</p><p>These are modern experiments, not ancient productivity statistics. Their value is precisely that they break the tempting equation “forest in, iron out.” Any historical estimate of woodland pressure must also specify charcoal making, furnace practice, ore, smithing losses, production frequency, and landscape management.</p><a className="source-link" href="https://www.repository.cam.ac.uk/items/ee03ff66-1277-4668-9830-43095946d816">Read the open Meroe study ↗</a></div><div className="viz-card iron-fuel-viz"><div className="viz-title"><div><span>Eleven modern experiments · two reconstruction programs</span><h4>How much charcoal became a bloom?</h4></div><small>reported inputs · derived ratios · no ancient projection</small></div><IronFuelExperiments/><p className="viz-note"><b>Method:</b> Switch between reported masses and the arithmetic charcoal-per-bloom ratio. Zero-bloom and trace-bloom runs remain categories rather than scale-setting infinities.</p></div></section>
  <section className="insight iron-quality-insight"><div className="insight-copy"><span className="insight-number">03</span><p className="claim">Iron was not born superior. Smelting, impurities, carbon, and working made different irons behave differently.</p><h3>Quality was made</h3><p>A bloom was not a standardized material. It could contain ferritic iron, localized carburized zones, slag, pores, sulfur-rich inclusions, and gradients created inside one furnace. Turning part of that bloom into a bar added another history of heating, hammering, oxidation, cracking, and material loss.</p><p>Four paired experimental samples reveal the trap in a single hardness number. FEXP-6 produced the hardest mean bloom at 139 HV, yet sulfur-rich inclusions made it brittle and difficult to forge. Its bar averaged only 113 HV. FEXP-5 began with the softest mean bloom at 84 HV but showed better workability.</p><p>All four bars remained mainly ferritic. Even FEXP-1—the run with localized carburized areas—produced only a small mild-steel patch in its bar. Useful iron depended on choosing and controlling properties for an intended object, not merely maximizing hardness.</p><a className="source-link" href="https://doi.org/10.1007/s12520-022-01516-3">Read the open metallographic study ↗</a></div><div className="viz-card iron-quality-viz"><div className="viz-title"><div><span>Four paired experiments · bloom and forged bar</span><h4>Did harder mean better?</h4></div><small>Vickers means · chemistry · microstructure · forging record</small></div><IronQualityLab/><p className="viz-note"><b>Method:</b> Select a run and then an evidence lens. Hardness means are shown without visual uncertainty bands; sample counts and standard deviations remain in the readout and CSV.</p></div></section>
  <section className="insight iron-mobilization-insight"><div className="insight-copy"><span className="insight-number">04</span><p className="claim">A cheaper weapon could broaden a levy. It could not create the levy.</p><h3>Metal did not mobilize itself</h3><p>Iron mattered at the margin. In pre-Roman European societies, cheaper swords and spearheads plausibly helped aristocrats arm more clients than an elite bronze-and-armor system could. But armor remained unequal, and broader mobilization also required social ties, external pressure, and a way to compel or persuade households to serve.</p><p>The counterexample comes first: Ramesses II approached Kadesh with four named divisions centuries before iron became ordinary. The often-repeated total of roughly twenty thousand is a modern inference, not a surviving Egyptian count—but the documented divisional and logistical system is enough to show that iron was not necessary for organized scale.</p><p>During the Second Punic War, Taylor reconstructs Carthage at roughly 170,000 deployed troops and Rome at roughly 185,000. Those are unusually comparable models from the same war. Their closeness makes the real question institutional: who recruited citizens, subjects, allies, or mercenaries; who supplied them; and who could replace losses?</p><a className="source-link" href="https://utpress.utexas.edu/9781477330777/">Read the comparative manpower study ↗</a></div><div className="viz-card iron-mobilization-viz"><div className="viz-title"><div><span>Four bounded cases · three evidence classes</span><h4>What turned equipment into an army?</h4></div><small>1274–212 BCE · no military-power score</small></div><IronMobilizationLedger/><p className="viz-note"><b>Method:</b> Select a case to inspect the equipment, recruitment, supply, and replacement ledger. Only Rome and Carthage share a model family and receive comparable bars.</p></div></section>
  <Placeholder number="05" claim="States, markets, and specialist communities made iron production durable—and chose different ways to organize it." title="Scale was institutional" copy="This section will compare workshops, tribute, standards, and state production without one centralization index."/>
</HistoryPageShell>}
