import type { Metadata } from 'next';
import AlphaChronology from '../components/AlphaChronology';
import AlphaPendingInsight from '../components/AlphaPendingInsight';
import ChartFooter from '../components/ChartFooter';
import HistoryPageShell from '../components/HistoryPageShell';

export const metadata:Metadata={title:'Southeast Asian Mandalas',description:'Five visual arguments about workshop ports, radiating authority, rivers, temples, and shifting maritime centers.',openGraph:{title:'Southeast Asian Mandalas — How Everything Evolved',description:'Early Southeast Asian ports manufactured imported technologies locally.',images:[]},twitter:{card:'summary',title:'Southeast Asian Mandalas — How Everything Evolved',description:'Early Southeast Asian ports manufactured imported technologies locally.',images:[]}};
const labels=['Early ports manufactured imported technologies locally','Political authority radiated from centers instead of stopping at borders','River basins linked upland products to coastal exchange','Temples stored labor and legitimacy—not only belief','Maritime centers survived by shifting alliances and routes'];
const events=[
  {year:1,displayYear:'Local workshop',label:'Glass ornaments',detail:'More than one thousand glass samples and at least two production areas document local bracelet and bead working.',kind:'archaeological industry'},
  {year:2,displayYear:'Local workshop',label:'Hard-stone ornaments',detail:'Carnelian, agate, and other hard-stone debris identify specialized ornament production.',kind:'archaeological industry'},
  {year:3,displayYear:'3 traditions',label:'Copper alloys',detail:'Analyses identify South Asian, Vietnamese, and Western Han analogies within one metallurgical assemblage.',kind:'archaeometallurgical comparison'},
  {year:4,displayYear:'Local workshop',label:'Iron working',detail:'Smithing evidence places iron production among the port’s craft activities.',kind:'archaeological industry'},
  {year:5,displayYear:'Local production',label:'Ceramics',detail:'Indian and Indian-style wares include evidence used to study technological exchange rather than imports alone.',kind:'technological comparison'},
];
export default function SoutheastAsiaPage(){return <HistoryPageShell title="Southeast Asian Mandalas" eyebrow="500 BCE–1500 CE" standfirst="Ports, river valleys, temples, and overlapping centers made power mobile across a maritime region." status="draft" progress="1 of 5 insights live" published="August 2026" insightLabels={labels}
  introduction={<><p>Premodern Southeast Asian power often radiated through alliances, ritual centers, ports, and river systems rather than ending at one surveyed frontier. The mandala is a useful model for that pattern, not a label for every polity.</p><p>The five claims start with workshop evidence from Khao Sam Kaeo, then test overlapping authority, river-to-coast systems, temple economies, and the political resilience of shifting maritime centers.</p></>}
  methods={<><p>The first visual combines peer-reviewed technological studies of Khao Sam Kaeo, dated broadly to the fourth–second centuries BCE. Categories identify production evidence and technological analogies; they are not output volumes or worker counts.</p><p>One cosmopolitan port cannot represent all Southeast Asian societies. “Foreign” technologies were selectively transferred and adapted; similar forms do not prove the ethnicity of individual artisans.</p></>}>
  <section className="insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">Khao Sam Kaeo worked glass, stone, metal, iron, and ceramics locally.</p><h3>{labels[0]}</h3><p>The Upper Thai-Malay Peninsula was not a passive bridge between India and China. At Khao Sam Kaeo, imported materials, foreign technical traditions, and local workshops combined to make goods for regional exchange.</p><p>Connectivity produced hybrid industries: the port’s advantage was not merely where it sat, but what craftspeople could remake there.</p></div><div className="viz-card"><div className="viz-title"><div><span>Khao Sam Kaeo · 4th–2nd centuries BCE</span><h4>{labels[0]}</h4></div><small>five industry lenses · no output score</small></div><AlphaChronology title="The port was a workshop as well as a waypoint" subtitle="Archaeological production evidence" events={events}/><ChartFooter source="Lankton, Dussubieux & Gratuze (2006); Murillo-Barroso et al. (2010); Bellina (2018)" note="Categories show local production evidence and technological analogies—not comparable output, workforce size, or proof of artisan ethnicity." dataHref="/data/southeast-asia/20260831-alpha1/khao-sam-kaeo-industries.csv"/></div></section>
  <AlphaPendingInsight number="02" title={labels[1]} question="Where did tribute, marriage, ritual status, and personal allegiance produce overlapping centers rather than exclusive territorial sovereignty?"/>
  <AlphaPendingInsight number="03" title={labels[2]} question="How did upstream-downstream systems move forest, mineral, and agricultural products between hinterlands, courts, and ports?"/>
  <AlphaPendingInsight number="04" title={labels[3]} question="What do labor mobilization, land, storage, inscriptions, pilgrimage, and monumental construction reveal about temple-centered coordination?"/>
  <AlphaPendingInsight number="05" title={labels[4]} question="How did ports relocate, compete, and rewire allegiance as chokepoints, trading partners, and sea routes changed?"/>
  </HistoryPageShell>}
