import type { Metadata } from 'next';
import AlphaChronology from '../components/AlphaChronology';
import AlphaPendingInsight from '../components/AlphaPendingInsight';
import ChartFooter from '../components/ChartFooter';
import HistoryPageShell from '../components/HistoryPageShell';
import MedievalTownCharters from '../MedievalTownCharters';

export const metadata:Metadata={title:'Medieval Europe',description:'Five visual arguments about manuscripts, towns, layered power, the church, and state rebuilding.',openGraph:{title:'Medieval Europe — How Everything Evolved',description:'Manuscript production accelerated centuries before printing.',images:[]},twitter:{card:'summary',title:'Medieval Europe — How Everything Evolved',description:'Manuscript production accelerated centuries before printing.',images:[]}};
const labels=['Manuscript production accelerated centuries before printing','Towns turned negotiated privileges into portable collective rights','Power was layered—not one feudal pyramid','The church connected polities that no king controlled','War and taxation rebuilt territorial states'];
const events=[
  {year:6,displayYear:'13.6k',label:'6th century',detail:'Estimated manuscripts copied across the study’s Western European regions.',kind:'modeled century total'},
  {year:7,displayYear:'10.6k',label:'7th century',detail:'The estimate falls before the later long expansion.',kind:'modeled century total'},
  {year:8,displayYear:'43.7k',label:'8th century',detail:'Estimated production rises above forty-three thousand manuscripts.',kind:'modeled century total'},
  {year:9,displayYear:'201.7k',label:'9th century',detail:'The Carolingian-era estimate is high and followed by a tenth-century contraction.',kind:'modeled century total'},
  {year:10,displayYear:'135.6k',label:'10th century',detail:'Estimated production remains below the ninth-century peak.',kind:'modeled century total'},
  {year:11,displayYear:'212.0k',label:'11th century',detail:'The later medieval rise begins from roughly two hundred thousand copies.',kind:'modeled century total'},
  {year:12,displayYear:'768.7k',label:'12th century',detail:'Estimated manuscript production more than triples from the previous century.',kind:'modeled century total'},
  {year:13,displayYear:'1.76m',label:'13th century',detail:'The estimate passes one and three-quarter million manuscripts.',kind:'modeled century total'},
  {year:14,displayYear:'2.75m',label:'14th century',detail:'Production continues to rise despite demographic and political shocks.',kind:'modeled century total'},
  {year:15,displayYear:'5.00m',label:'15th century',detail:'Estimated manuscript copying reaches about five million before printed books are added separately.',kind:'modeled century total'},
];
export default function MedievalEuropePage(){return <HistoryPageShell title="Medieval Europe" eyebrow="500–1500 CE" standfirst="Fragmented authority coexisted with expanding towns, churches, schools, markets, records, and states." status="draft" progress="2 of 5 insights live" published="August 2026" insightLabels={labels}
  introduction={<><p>Medieval Europe was neither a thousand-year collapse nor a steady march toward modern states. Political authority remained layered while institutions for worship, trade, law, learning, and war multiplied.</p><p>The five claims follow information growth, urban rights, overlapping jurisdiction, translocal church organization, and the fiscal-military rebuilding of territorial government.</p></>}
  methods={<><p>The first visual reproduces Buringh and van Zanden’s modeled manuscript-production totals for the regions they group as Western Europe. Their reconstruction corrects surviving-manuscript evidence for loss; it is not an archive census or a literacy series.</p><p>The charter comparison keeps four unlike cases separate. Written privileges could define predictable dues, trade rights, or civic status, but did not make every resident equal or remove lordship.</p></>}>
  <section className="insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">Estimated manuscript copying rose from about 212,000 in the eleventh century to five million in the fifteenth.</p><h3>{labels[0]}</h3><p>Europe’s information economy changed before Gutenberg. The reconstruction rises unevenly—Carolingian expansion is followed by contraction—but accelerates after 1000 as monasteries, cathedral schools, universities, courts, towns, and professional scribes demanded more texts.</p><p>Print transformed cost and scale. It did not create Europe’s appetite for books from nothing.</p></div><div className="viz-card"><div className="viz-title"><div><span>Western Europe · modeled manuscript copies</span><h4>{labels[0]}</h4></div><small>6th–15th centuries · century totals</small></div><AlphaChronology title="Book production expanded before print" subtitle="Published reconstruction by century" events={events}/><ChartFooter source="Buringh & van Zanden (2009), Table 1" note="Estimated copies produced, corrected from surviving-manuscript evidence. These are century totals—not surviving books, readers, literacy rates, or annual observations." dataHref="/data/medieval-europe/20260831-alpha1/manuscript-production.csv"/></div></section>
  <section className="insight"><div className="insight-copy"><span className="insight-number">02</span><p className="claim">Charters turned bargains with lords into rights that towns could confirm, copy, and invoke elsewhere.</p><h3>{labels[1]}</h3><p>Urban freedom was rarely granted once and forever. Towns converted custom and negotiated concessions into documents: predictable dues, merchant-gild privileges, toll exemptions, and recognition as a legal community.</p><p>The strongest clue is portability. Fourteenth-century civic registers preserved other towns’ records so merchants could assert exemptions beyond their own walls.</p></div><div className="viz-card"><div className="viz-title"><div><span>Four charter mechanisms · 1120–14th century</span><h4>{labels[1]}</h4></div><small>selected cases · not an autonomy score</small></div><MedievalTownCharters/><ChartFooter source="Freiburg charter synthesis; Customs of Lorris; Henry II's Oxford charter; Porter (2024)" note="Selected charters and civic records show distinct bargains. They do not measure every town, resident, enforcement outcome, or degree of independence." dataHref="/data/medieval-europe/20260831-charters1/town-charter-rights.csv"/></div></section>
  <AlphaPendingInsight number="03" title={labels[2]} question="How did lordship, kinship, office, property, and negotiated allegiance overlap without forming one universal hierarchy?"/>
  <AlphaPendingInsight number="04" title={labels[3]} question="Which networks of dioceses, monasteries, canon law, schools, and correspondence coordinated action across kingdoms?"/>
  <AlphaPendingInsight number="05" title={labels[4]} question="Where did war, debt, taxation, representation, and record-keeping turn negotiated rule into durable territorial institutions?"/>
  </HistoryPageShell>}
