import type { Metadata } from 'next';
import AlphaChronology from '../components/AlphaChronology';
import AlphaPendingInsight from '../components/AlphaPendingInsight';
import ChartFooter from '../components/ChartFooter';
import ChristianCareInstitutions from '../ChristianCareInstitutions';
import HistoryPageShell from '../components/HistoryPageShell';

export const metadata:Metadata={title:'Christianity',description:'Five visual arguments about letters, cities, institutions, empire, fragmentation, and Christian afterlives.',openGraph:{title:'Christianity — How Everything Evolved',description:'Christianity became a letter network before it became an empire.',images:[]},twitter:{card:'summary',title:'Christianity — How Everything Evolved',description:'Christianity became a letter network before it became an empire.',images:[]}};
const labels=['Christianity became a letter network before it became an empire','Recurring gifts and named offices made congregations durable','Constantine changed the church faster than he Christianized the empire','One creed did not produce one Christianity','Monasteries carried Christian institutions beyond western empire'];
const events=[
  {year:51,displayYear:'c. 51 CE',label:'1 Thessalonians',detail:'A letter addressed to a congregation in Thessalonica.',kind:'generally accepted Pauline letter'},
  {year:54,displayYear:'c. 53–54',label:'1 Corinthians',detail:'A community letter to Christians in Corinth.',kind:'generally accepted Pauline letter'},
  {year:54.2,displayYear:'c. 54',label:'Galatians',detail:'A letter to congregations in the Roman province of Galatia.',kind:'generally accepted Pauline letter'},
  {year:55,displayYear:'c. 54–56',label:'2 Corinthians',detail:'A collected correspondence with the Corinthian community.',kind:'generally accepted Pauline letter'},
  {year:56,displayYear:'c. 56',label:'Philippians',detail:'A letter to Christians in Philippi.',kind:'generally accepted Pauline letter'},
  {year:56.2,displayYear:'c. 56',label:'Philemon',detail:'A personal letter revealing a household-scale Christian network.',kind:'generally accepted Pauline letter'},
  {year:57,displayYear:'c. 57',label:'Romans',detail:'A letter to Christians in Rome before Paul had visited them.',kind:'generally accepted Pauline letter'},
];
export default function ChristianityPage(){return <HistoryPageShell title="Christianity" eyebrow="30–800 CE" standfirst="A movement became an institution before it became imperial." status="draft" progress="2 of 5 insights live" published="August 2026" insightLabels={labels}
  introduction={<><p>Christianity did not begin as a territorial state. It spread through households, congregations, letters, travel, and arguments among communities embedded in Roman cities.</p><p>The five claims follow that network as it acquired bishops, resources, imperial patrons, competing doctrines, and institutions capable of surviving the western imperial court.</p></>}
  methods={<><p>The first visual limits itself to the seven letters most scholars generally accept as Pauline. Dates follow J. Albert Harrill’s rough chronology; authorship consensus follows E. P. Sanders. The letters are surviving texts, not a census of congregations or a direct measure of Christian population.</p><p>Philemon is a personal rather than community letter, and its destination is not securely stated. The timeline therefore uses the type of network rather than assigning it an invented city.</p><p>The second visual compares prescriptions and an apologetic description from different dates and genres. It treats recurring contributions, eligibility rules, and named distribution roles as evidence of organizational capacity—not as audited spending, observed compliance, or a measured survival rate. The date and authorship of 1 Timothy remain disputed.</p></>}>
  <section className="insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">The earliest surviving Christian literature links congregations and households across the Roman world.</p><h3>{labels[0]}</h3><p>Between roughly 51 and 57 CE, the seven generally accepted Pauline letters addressed communities in Thessalonica, Corinth, Galatia, Philippi, and Rome, plus one household-scale relationship.</p><p>Christianity was already a repeatable communications system decades before imperial patronage: travelers carried letters, communities read and recopied them, and distant disputes became shared institutional problems.</p></div><div className="viz-card"><div className="viz-title"><div><span>Seven generally accepted Pauline letters</span><h4>{labels[0]}</h4></div><small>c. 51–57 CE · surviving texts</small></div><AlphaChronology title="Seven letters connect cities and households in six years" subtitle="Rough scholarly chronology" events={events}/><ChartFooter source="Harrill (2012); Sanders (1996)" note="Surviving letters are not a census of Christians or congregations. Dates are approximate, and Philemon is a personal letter with a debated location." dataHref="/data/christianity/20260831-alpha1/pauline-letter-network.csv"/></div></section>
  <section className="insight christian-care-insight"><div className="insight-copy"><span className="insight-number">02</span><p className="claim">Christian congregations became durable when repeated gifts, beneficiary rules, and named offices turned mutual aid into an organization.</p><h3>{labels[1]}</h3><p>Paul&apos;s instructions to Corinth made giving repeatable and transferable: set money aside each week, then entrust it to approved delegates. A later letter describes an enrolled group of widows, including an age threshold and duties split between households and the congregation.</p><p>By about 155 CE, Justin described a weekly assembly in Rome where voluntary contributions went to a president who distributed aid to orphans, widows, sick or needy people, prisoners, and resident strangers.</p><p>These texts do not measure budgets or prove uniform practice. They do show the institutional move: generosity became more durable when communities gave it a schedule, rules, records, and accountable roles.</p></div><div className="viz-card christian-care-viz"><div className="viz-title"><div><span>Contributions + rules + offices</span><h4>{labels[1]}</h4></div><small>three textual windows · c. 54–155 CE</small></div><ChristianCareInstitutions/><ChartFooter source="1 Corinthians 16:1–4; 1 Timothy 5:3–16; Justin, First Apology 67" note="These are prescriptions and an apologetic description, not audited accounts or a census of congregations. 1 Timothy's authorship and date are disputed." dataHref="/data/christianity/20260831-charity1/congregational-care-institutions.csv"/></div></section>
  <AlphaPendingInsight number="03" title={labels[2]} question="What changed immediately after imperial patronage, and what evidence shows that conversion across the empire remained slower and uneven?"/>
  <AlphaPendingInsight number="04" title={labels[3]} question="How did councils, creeds, rival bishops, languages, and regional churches create connection and schism at the same time?"/>
  <AlphaPendingInsight number="05" title={labels[4]} question="Which monastic, educational, legal, calendrical, and charitable institutions persisted after western imperial government fragmented?"/>
  </HistoryPageShell>}
