import type { Metadata } from 'next';
import AlphaChronology from '../components/AlphaChronology';
import AlphaPendingInsight from '../components/AlphaPendingInsight';
import ChartFooter from '../components/ChartFooter';
import HistoryPageShell from '../components/HistoryPageShell';
import SteppeHorseMobility from '../SteppeHorseMobility';
import SteppeWarSystem from '../SteppeWarSystem';
import SteppeFrontierBargains from '../SteppeFrontierBargains';

export const metadata:Metadata={title:'The Steppe',description:'Five visual arguments about pastoral mobility, horses, warfare, confederations, and Eurasian exchange.',openGraph:{title:'The Steppe — How Everything Evolved',description:'Pastoralism came before cavalry.',images:[]},twitter:{card:'summary',title:'The Steppe — How Everything Evolved',description:'Pastoralism came before cavalry.',images:[]}};
const labels=['At Begash, pastoralism began with sheep and goats—not cavalry','Horse power became military reach in stages—not one revolution','Steppe military power came from a system—not a wonder weapon','Steppe states turned frontier pressure into recurring payments and markets','Steppe migrations moved genes and languages without erasing everyone'];
const events=[
  {year:-2450,displayYear:'c. 2450 BCE',label:'Mobile herding at Begash',detail:'The earliest occupation already shows a pastoral economy dominated by sheep and goats.',kind:'faunal assemblage'},
  {year:-1950,displayYear:'after c. 1950 BCE',label:'Horses enter the sequence',detail:'Horse remains are absent in the earliest phase and appear only later.',kind:'faunal assemblage'},
  {year:-1000,displayYear:'2nd millennium BCE',label:'Horses remain a minority',detail:'Horse remains stay below four percent while sheep and goats continue to dominate.',kind:'published synthesis'},
  {year:-500,displayYear:'mid-1st millennium BCE',label:'Horse use grows',detail:'A larger horse share coincides with more hunting and larger political groupings.',kind:'archaeological interpretation'},
];
export default function SteppePage(){return <HistoryPageShell title="The Steppe" eyebrow="3500 BCE–1500 CE" standfirst="Mobility turned uneven grasslands into a connected political world." status="draft" progress="4 of 5 insights live" published="August 2026" insightLabels={labels}
  introduction={<><p>The Eurasian steppe was not an empty corridor between civilizations. Mobile herders learned to combine seasonal pasture, mixed herds, exchange, and political alliances across environments where permanent farming was often risky.</p><p>The horse later changed what mobility could do, but it did not create pastoralism. The five claims separate herding from cavalry, military reach from weapons alone, and migration from simple replacement.</p></>}
  methods={<><p>The first visual uses one unusually long faunal sequence from Begash in south-eastern Kazakhstan. It is a regional case, not a census of every steppe society. Fragment shares describe recovered animal remains, not calories, wealth, or mounted soldiers.</p><p>Frachetti and Benecke report sheep and goats as the dominant early herd, no horses in the earliest phase, horse frequencies below four percent through the second millennium BCE, and a later increase. Date labels summarize their occupation phases and should not be read as exact adoption dates across Eurasia.</p><p>The mobility comparison keeps four different evidentiary clocks separate. Genomes reveal breeding and horse-lineage dispersal, not rider routes; a Sintashta grave preserves a chariot context, not an army; surviving saddles postdate the first riding and do not define cavalry&apos;s origin. The sequence therefore marks capabilities rather than one invention date or numerical range multiplier.</p><p>The frontier comparison preserves the original terms of four unlike bargains. Han-Xiongnu quantities are later maxima within a changing heqin framework; Türk tribute silk is not a full flow series; Song-Liao silver and silk and Song-Western Xia mixed goods retain their reported units. None is converted into a common value, confederation-strength score, or guaranteed duration of peace.</p></>}>
  <section className="insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">At Begash, mobile pastoralism was already established while horses were absent or rare.</p><h3>{labels[0]}</h3><p>Popular histories often make the horse the beginning of steppe life. Begash reverses that sequence. Sheep and goats dominated the earliest third-millennium-BCE assemblage; horses arrived later and remained a small minority for centuries.</p><p>The steppe toolkit began with moving mixed herds through seasonal landscapes. Cavalry was a later political and military transformation of an older pastoral economy.</p></div><div className="viz-card"><div className="viz-title"><div><span>Begash · south-eastern Kazakhstan</span><h4>{labels[0]}</h4></div><small>one site · 4,500-year sequence</small></div><AlphaChronology title="Pastoralism came before horse-centered herding" subtitle="Published faunal sequence" events={events}/><ChartFooter source="Frachetti & Benecke (2009)" note="This is one mountain-steppe settlement. Faunal fragment shares are not herd censuses, diet shares, or evidence that every steppe region followed the same sequence." dataHref="/data/steppe/20260831-alpha1/begash-pastoral-sequence.csv"/></div></section>
  <section className="insight steppe-mobility-insight"><div className="insight-copy"><span className="insight-number">02</span><p className="claim">Horse-based military reach emerged in stages: local husbandry came first, large-scale breeding supplied mounts, chariots accelerated elites, and mounted cavalry followed.</p><h3>{labels[1]}</h3><p>Botai people managed horses around 3500 BCE, but those animals followed a different lineage from most later domestic horses. A study of 475 ancient genomes instead dates reproductive control and rapid dispersal of the modern domestic lineage to around 2200 BCE.</p><p>Sintashta communities then paired horse teams with light spoked-wheel vehicles. One chariot grave at Kamennyj Ambar-5 is modeled to 1950–1880 BCE—fast transport for people, but not yet mass mounted cavalry.</p><p>By the middle of the first millennium BCE, cavalry and soft-pad saddles were widespread. The strategic change was cumulative: breeding, control gear, vehicles, riding practice, weapons, and organization turned horse management into military reach.</p></div><div className="viz-card steppe-mobility-viz"><div className="viz-title"><div><span>Breeding + vehicles + riding technology</span><h4>{labels[1]}</h4></div><small>four evidence windows · no single revolution date</small></div><SteppeHorseMobility/><ChartFooter source="Librado et al. (2024); Lindner (2020); Bayarsaikhan et al. (2023)" note="Genomes, graves, and surviving tack answer different questions. The stages do not measure travel speed, action radius, army size, or one universal adoption date." dataHref="/data/steppe/20260831-mobility1/horse-mobility-stages.csv"/></div></section>
  <section className="insight"><div className="insight-copy"><span className="insight-number">03</span><p className="claim">The bow delivered force, but maneuver, fresh horses, and information made that force operational.</p><h3>{labels[2]}</h3><p>The composite bow mattered because it let a mounted archer strike while moving. It worked inside a larger system: feigned retreats and encirclement shaped the fight, remounts limited fatigue, and scouts protected dispersed columns.</p><p>A thirteenth-century report gives Mongol soldiers as many as six or seven spare horses. That is a bounded report, not a universal allowance—but it makes the hidden herd behind the famous archer visible.</p></div><div className="viz-card"><div className="viz-title"><div><span>Weapon + maneuver + herd + information</span><h4>{labels[2]}</h4></div><small>unlike evidence · no power score</small></div><SteppeWarSystem/><ChartFooter source="May (2015, 2018); Martin (1943), citing Meng Hong" note="The four mechanisms come from unlike periods and sources. They explain an operating system without estimating range, speed, endurance, army size, or each factor's causal share." dataHref="/data/steppe/20260901-war-system1/steppe-war-system.csv"/></div></section>
  <section className="insight"><div className="insight-copy"><span className="insight-number">04</span><p className="claim">Military leverage was only the opening move. Steppe rulers repeatedly converted it into annual goods, recognized status, fixed frontiers, and access to markets.</p><h3>{labels[3]}</h3><p>After the Han defeat in 200 BCE, the Xiongnu bargain bundled annual goods with marriage, coequal status, and a recognized boundary. Centuries later, Chinese silk paid to the Türks fed a Sogdian-led search for markets as far west as Byzantium.</p><p>The Song frontier makes the bargain measurable. In 1005, the Khitan Liao received annual silver and silk alongside diplomatic parity; in 1044, Western Xia secured annual silk, silver, and tea, hereditary recognition, and two official border markets.</p></div><div className="viz-card"><div className="viz-title"><div><span>Pressure → recurring resources → political terms</span><h4>{labels[3]}</h4></div><small>four treaty packages · original units retained</small></div><SteppeFrontierBargains/><ChartFooter source="Barfield (2001); de la Vaissière (2013); Smith (2023)" note="These are four source-bounded bargains, not a complete treaty census. Unlike goods retain their original units; no tribute value, confederation strength, or peace-durability score is inferred." dataHref="/data/steppe/20260901-bargains1/frontier-bargain-packages.csv"/></div></section>
  <AlphaPendingInsight number="05" title={labels[4]} question="Where do ancient DNA, language history, archaeology, and military borrowing show movement, mixture, or cultural transmission rather than total replacement?"/>
  </HistoryPageShell>}
