import type { Metadata } from 'next';
import AlphaChronology from '../components/AlphaChronology';
import AlphaPendingInsight from '../components/AlphaPendingInsight';
import ChartFooter from '../components/ChartFooter';
import HistoryPageShell from '../components/HistoryPageShell';

export const metadata:Metadata={title:'The Steppe',description:'Five visual arguments about pastoral mobility, horses, warfare, confederations, and Eurasian exchange.',openGraph:{title:'The Steppe — How Everything Evolved',description:'Pastoralism came before cavalry.',images:[]},twitter:{card:'summary',title:'The Steppe — How Everything Evolved',description:'Pastoralism came before cavalry.',images:[]}};
const labels=['Steppe pastoralism began with sheep and goats—not cavalry','Horses turned mobility into military reach','Remounts mattered as much as bows','Confederations grew by bargaining with agrarian states','Steppe migrations moved genes and languages without erasing everyone'];
const events=[
  {year:-2450,displayYear:'c. 2450 BCE',label:'Mobile herding at Begash',detail:'The earliest occupation already shows a pastoral economy dominated by sheep and goats.',kind:'faunal assemblage'},
  {year:-1950,displayYear:'after c. 1950 BCE',label:'Horses enter the sequence',detail:'Horse remains are absent in the earliest phase and appear only later.',kind:'faunal assemblage'},
  {year:-1000,displayYear:'2nd millennium BCE',label:'Horses remain a minority',detail:'Horse remains stay below four percent while sheep and goats continue to dominate.',kind:'published synthesis'},
  {year:-500,displayYear:'mid-1st millennium BCE',label:'Horse use grows',detail:'A larger horse share coincides with more hunting and larger political groupings.',kind:'archaeological interpretation'},
];
export default function SteppePage(){return <HistoryPageShell title="The Steppe" eyebrow="3500 BCE–1500 CE" standfirst="Mobility turned uneven grasslands into a connected political world." status="draft" progress="1 of 5 insights live" published="August 2026" insightLabels={labels}
  introduction={<><p>The Eurasian steppe was not an empty corridor between civilizations. Mobile herders learned to combine seasonal pasture, mixed herds, exchange, and political alliances across environments where permanent farming was often risky.</p><p>The horse later changed what mobility could do, but it did not create pastoralism. The five claims separate herding from cavalry, military reach from weapons alone, and migration from simple replacement.</p></>}
  methods={<><p>The first visual uses one unusually long faunal sequence from Begash in south-eastern Kazakhstan. It is a regional case, not a census of every steppe society. Fragment shares describe recovered animal remains, not calories, wealth, or mounted soldiers.</p><p>Frachetti and Benecke report sheep and goats as the dominant early herd, no horses in the earliest phase, horse frequencies below four percent through the second millennium BCE, and a later increase. Date labels summarize their occupation phases and should not be read as exact adoption dates across Eurasia.</p></>}>
  <section className="insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">At Begash, mobile pastoralism was already established while horses were absent or rare.</p><h3>{labels[0]}</h3><p>Popular histories often make the horse the beginning of steppe life. Begash reverses that sequence. Sheep and goats dominated the earliest third-millennium-BCE assemblage; horses arrived later and remained a small minority for centuries.</p><p>The steppe toolkit began with moving mixed herds through seasonal landscapes. Cavalry was a later political and military transformation of an older pastoral economy.</p></div><div className="viz-card"><div className="viz-title"><div><span>Begash · south-eastern Kazakhstan</span><h4>{labels[0]}</h4></div><small>one site · 4,500-year sequence</small></div><AlphaChronology title="Pastoralism came before horse-centered herding" subtitle="Published faunal sequence" events={events}/><ChartFooter source="Frachetti & Benecke (2009)" note="This is one mountain-steppe settlement. Faunal fragment shares are not herd censuses, diet shares, or evidence that every steppe region followed the same sequence." dataHref="/data/steppe/20260831-alpha1/begash-pastoral-sequence.csv"/></div></section>
  <AlphaPendingInsight number="02" title={labels[1]} question="When did riding, carts, and horse breeding materially expand transport, herding, communication, and raiding ranges?"/>
  <AlphaPendingInsight number="03" title={labels[2]} question="How much operational reach came from composite bows, and how much from spare horses, fodder, intelligence, and command?"/>
  <AlphaPendingInsight number="04" title={labels[3]} question="Which tribute, trade, marriage, hostage, and frontier arrangements made mobile confederations and agrarian states mutually dependent?"/>
  <AlphaPendingInsight number="05" title={labels[4]} question="Where do ancient DNA, language history, archaeology, and military borrowing show movement, mixture, or cultural transmission rather than total replacement?"/>
  </HistoryPageShell>}
