import type { Metadata } from 'next';
import AlphaChronology from '../components/AlphaChronology';
import AlphaPendingInsight from '../components/AlphaPendingInsight';
import ChartFooter from '../components/ChartFooter';
import HistoryPageShell from '../components/HistoryPageShell';

export const metadata:Metadata={title:'Mesoamerican Cities and States',description:'Five visual arguments about Maya settlement, ecological engineering, writing, markets, and political change.',openGraph:{title:'Mesoamerican Cities and States — How Everything Evolved',description:'Maya cities were embedded in a densely built countryside.',images:[]},twitter:{card:'summary',title:'Mesoamerican Cities and States — How Everything Evolved',description:'Maya cities were embedded in a densely built countryside.',images:[]}};
const labels=['Maya cities were embedded in a densely built countryside','Maize supported states only with water and labor systems','Writing made dynasties and tribute durable','Markets coordinated households beyond palace redistribution','Political collapse moved people more than it erased Maya society'];
const events=[
  {year:1,displayYear:'2,144 km²',label:'Surveyed landscape',detail:'Airborne lidar mapped twelve blocks in the Maya Biosphere Reserve of northern Guatemala.',kind:'survey footprint'},
  {year:2,displayYear:'61,480',label:'Ancient structures',detail:'The classification counted buildings, platforms, roads, fortifications, terraces, and other features.',kind:'mapped feature count'},
  {year:3,displayYear:'29 / km²',label:'Structure density',detail:'The mapped total averages twenty-nine classified structures per square kilometre across the survey.',kind:'survey-wide ratio'},
  {year:4,displayYear:'80–120 / km²',label:'People at Late Classic peak',detail:'The authors modeled average population density for the central Maya Lowlands at their Late Classic height.',kind:'regional model'},
  {year:5,displayYear:'7–11m',label:'Central lowland population',detail:'The modeled density implies seven to eleven million people across the larger central lowland region.',kind:'regional extrapolation'},
];
export default function MesoamericaPage(){return <HistoryPageShell title="Mesoamerican Cities and States" eyebrow="1000 BCE–1500 CE" standfirst="Cities, farms, markets, dynasties, and engineered landscapes made political life possible without one permanent empire." status="draft" progress="1 of 5 insights live" published="August 2026" insightLabels={labels}
  introduction={<><p>Mesoamerica repeatedly produced large cities and states without draft animals, wheeled freight, or one continuous imperial center. Dense settlement depended on intensive land use, water management, markets, records, and negotiated political authority.</p><p>The five claims begin with lidar’s regional view of Maya settlement, then test ecological engineering, writing, exchange, and what political collapse changed—and did not erase.</p></>}
  methods={<><p>The first visual reproduces the headline results of the 2016 PACUNAM lidar survey published by Canuto and colleagues. Structure counts come from the 2,144-square-kilometre sample; population figures are models extended to the larger central Maya Lowlands.</p><p>Lidar detects surface relief, not occupants, dates, political allegiance, or building function automatically. The five measures therefore retain their different scopes instead of becoming one urbanization score.</p></>}>
  <section className="insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">Lidar mapped 61,480 ancient structures across 2,144 square kilometres of northern Guatemala.</p><h3>{labels[0]}</h3><p>The forest did not hide a few isolated ceremonial centers. It hid roads, terraces, fortifications, buildings, and fields spread across an intensively modified region.</p><p>The strongest conclusion is spatial: urban cores and rural settlement formed one connected landscape. The modeled population totals are useful, but more assumption-dependent than the mapped structures beneath them.</p></div><div className="viz-card"><div className="viz-title"><div><span>Northern Guatemala · PACUNAM lidar</span><h4>{labels[0]}</h4></div><small>survey counts and regional models kept separate</small></div><AlphaChronology title="The forest covered a built landscape" subtitle="Published lidar results" events={events}/><ChartFooter source="Canuto et al. (2018)" note="The 61,480 structures belong to the 2,144 km² survey. Population density and 7–11 million people are regional Late Classic models—not direct counts or annual observations." dataHref="/data/mesoamerica/20260831-alpha1/maya-lidar-findings.csv"/></div></section>
  <AlphaPendingInsight number="02" title={labels[1]} question="How did reservoirs, terraces, raised fields, soils, and organized maintenance turn seasonal environments into reliable urban food systems?"/>
  <AlphaPendingInsight number="03" title={labels[2]} question="Which inscriptions and codices made descent, office, tribute, conquest, calendrics, and ritual claims durable across generations?"/>
  <AlphaPendingInsight number="04" title={labels[3]} question="Where do market spaces, household goods, production debris, and price evidence show exchange operating beyond court redistribution?"/>
  <AlphaPendingInsight number="05" title={labels[4]} question="Which cities and regions depopulated, persisted, reorganized, or moved after political breakdown—and on what different clocks?"/>
  </HistoryPageShell>}
