import type { Metadata } from 'next';
import AlphaChronology from '../components/AlphaChronology';
import AlphaPendingInsight from '../components/AlphaPendingInsight';
import ChartFooter from '../components/ChartFooter';
import GreekMilitaryConstituencies from '../GreekMilitaryConstituencies';
import HistoryPageShell from '../components/HistoryPageShell';

export const metadata:Metadata={title:'Greek City-States',description:'Five visual arguments about small states, citizenship, exclusion, leagues, and the persistence of the polis.',openGraph:{title:'Greek City-States — How Everything Evolved',description:'The typical Greek state was smaller than its famous exceptions.',images:[]},twitter:{card:'summary',title:'Greek City-States — How Everything Evolved',description:'The typical Greek state was smaller than its famous exceptions.',images:[]}};
const labels=['The typical Greek state was smaller than its famous exceptions','Military necessity gave poorer citizens political leverage','Democracy expanded participation while excluding most residents','Leagues scaled collective action without erasing local poleis','Macedon ended autonomy before it ended the polis'];
const events=[
  {year:1,displayYear:'15%',label:'≤25 km²',detail:'Fifteen percent of classified polis territories fit inside twenty-five square kilometres.',kind:'cumulative share'},
  {year:2,displayYear:'60%',label:'≤100 km²',detail:'Three in five were no larger than one hundred square kilometres.',kind:'cumulative share'},
  {year:3,displayYear:'80%',label:'≤200 km²',detail:'Four in five fit inside two hundred square kilometres.',kind:'cumulative share'},
  {year:4,displayYear:'≤10%',label:'>500 km²',detail:'At most one in ten exceeded five hundred square kilometres.',kind:'upper-bound share'},
  {year:5,displayYear:'13 poleis',label:'>1,000 km²',detail:'Only thirteen classified poleis exceeded one thousand square kilometres.',kind:'reported count'},
];
export default function GreekCityStatesPage(){return <HistoryPageShell title="Greek City-States" eyebrow="800–338 BCE" standfirst="A world of unusually small states learned to act together without becoming one state." status="draft" progress="2 of 5 insights live" published="August 2026" insightLabels={labels}
  introduction={<><p>Ancient Greece was not Athens and Sparta writ small. It was a city-state culture of more than a thousand known communities, most governing territories compact enough to cross on foot in a day.</p><p>The five claims ask what political smallness made possible, whom citizenship excluded, and how leagues, federations, and Macedonian power changed collective action without immediately erasing the polis.</p></>}
  methods={<><p>The first visual reproduces cumulative territory categories reported by Mogens Hansen from the Copenhagen Polis Centre inventory. The underlying classified set contains 636 of 869 locatable poleis; categories are approximate and do not describe simultaneous borders.</p><p>Athens and Sparta were exceptional large territories. Territory is not population, wealth, military power, democracy, or political independence.</p><p>The second visual makes Aristotle&apos;s comparative typology inspectable rather than turning it into a causal score. Peter Hunt&apos;s modern synthesis emphasizes that military service often brought political power in its wake while warning against an intrinsic or automatic hoplite-to-democracy link.</p></>}>
  <section className="insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">Four in five classified polis territories were no larger than 200 km².</p><h3>{labels[0]}</h3><p>The Greece remembered through Athens and Sparta was mostly a world of much smaller states. Sixty percent of classified poleis had territories no larger than 100 km²; eighty percent fit inside 200 km².</p><p>That scale helps explain why citizenship, war, religion, and government remained intensely local—and why collective action so often required alliances or federal institutions above the polis.</p></div><div className="viz-card"><div className="viz-title"><div><span>Archaic and Classical poleis · classified territories</span><h4>{labels[0]}</h4></div><small>cumulative shares · not a map</small></div><AlphaChronology title="Most poleis occupied compact territories" subtitle="Copenhagen Polis Centre inventory" events={events}/><ChartFooter source="Hansen (2006); Hansen & Nielsen (2004)" note="The categories cover 636 approximately classified territories. They are cumulative, not simultaneous boundaries, and territory is not population or political power." dataHref="/data/greek-city-states/20260831-alpha1/polis-territory-distribution.csv"/></div></section>
  <section className="insight greek-citizens-insight"><div className="insight-copy"><span className="insight-number">02</span><p className="claim">The cheaper a military role was to enter, the farther political leverage could extend down the citizen body.</p><h3>{labels[1]}</h3><p>A cavalry force depended on estate owners who could keep horses. Hoplite service demanded privately supplied armor. Light infantry and naval rowing lowered the personal equipment barrier and made poorer men militarily useful.</p><p>Aristotle mapped those constituencies onto political tendencies: cavalry favored oligarchy; heavy infantry favored property-qualified government; light and naval forces were democratic elements.</p><p>Equipment did not mechanically cause democracy. It changed which people the polis depended on—and therefore who could plausibly demand a voice.</p></div><div className="viz-card greek-citizens-viz"><div className="viz-title"><div><span>Military role + entry cost + political tendency</span><h4>{labels[1]}</h4></div><small>Aristotle&apos;s comparison · not a causal score</small></div><GreekMilitaryConstituencies/><ChartFooter source="Aristotle, Politics 6; Hunt (2009)" note="This is an ancient comparative theory checked against modern synthesis. It does not show that hoplite tactics automatically created democracy or that soldiers and citizens were identical groups." dataHref="/data/greek-city-states/20260831-citizens1/military-political-constituencies.csv"/></div></section>
  <AlphaPendingInsight number="03" title={labels[2]} question="How large were the excluded groups—women, enslaved people, resident foreigners, and non-citizen dependants—and how did exclusion vary by polis?"/>
  <AlphaPendingInsight number="04" title={labels[3]} question="Which military, fiscal, citizenship, and council arrangements let leagues coordinate while member poleis retained local institutions?"/>
  <AlphaPendingInsight number="05" title={labels[4]} question="Which civic institutions survived Macedonian hegemony and Hellenistic monarchy, and which decisions moved beyond the polis?"/>
  </HistoryPageShell>}
