import type { Metadata } from 'next';
import AlphaChronology from '../components/AlphaChronology';
import ArabicAdministrationClocks from '../ArabicAdministrationClocks';
import ArabicBookJourneys from '../ArabicBookJourneys';
import CaliphateTradeEdges from '../CaliphateTradeEdges';
import ChartFooter from '../components/ChartFooter';
import CaliphateTaxTransition from '../CaliphateTaxTransition';
import HistoryPageShell from '../components/HistoryPageShell';

export const metadata:Metadata={title:'The Caliphates',description:'Five visual arguments about conquest, inherited administration, Arabic, trade, and a connected post-imperial world.',openGraph:{title:'The Caliphates — How Everything Evolved',description:'The first caliphates joined former Roman and Sasanian lands within twenty-two years.',images:[]},twitter:{card:'summary',title:'The Caliphates — How Everything Evolved',description:'The first caliphates joined former Roman and Sasanian lands within twenty-two years.',images:[]}};
const labels=['The first caliphates joined former Roman and Sasanian lands within twenty-two years','Conquest changed the ruler before it changed the tax office','Arabic became an imperial administrative language around 700—but local government remained multilingual','Trade tied together seas that no caliph controlled alone','Arabic books crossed the borders that split the caliphal world'];
const events=[
  {year:632,displayYear:'632 CE',label:'Arabian political core',detail:'Muhammad died after authority had expanded across much of Arabia.',kind:'political baseline'},
  {year:641,displayYear:'by 641',label:'Iraq, Syria, and Egypt',detail:'Former Sasanian and eastern Roman provinces were under the new rulers.',kind:'conquest endpoint'},
  {year:654,displayYear:'by 654',label:'Iran',detail:'The Sasanian imperial realm had been incorporated.',kind:'conquest endpoint'},
  {year:711,displayYear:'643–711',label:'North Africa',detail:'Expansion across North Africa ended the remaining eastern Roman position there.',kind:'conquest interval'},
  {year:712,displayYear:'from 711',label:'Iberia',detail:'Armies crossed into Iberia and began another regional conquest.',kind:'conquest opening'},
  {year:751,displayYear:'by 751',label:'Transoxiana',detail:'Territory between the Oxus and Jaxartes was incorporated into the wider imperial sphere.',kind:'conquest endpoint'},
];
export default function CaliphatesPage(){return <HistoryPageShell title="The Caliphates" eyebrow="632–1258 CE" standfirst="Rapid conquest joined old imperial worlds; institutions made the connection last." status="draft" progress="5 of 5 insights live" published="August 2026" insightLabels={labels}
  introduction={<><p>The early caliphates did more than replace rulers. Their conquests brought Arabia, the former Sasanian realm, and large eastern Roman provinces into one political field, then adapted the tax systems, cities, languages, and exchange networks already operating there.</p><p>The five claims separate rapid territorial expansion from the slower construction of an Arabic-speaking, legally plural, commercially connected, and intellectually shared world.</p></>}
  methods={<><p>The first visual follows Ira Lapidus’s compact scholarly chronology. “Conquered” marks broad political incorporation, not uniform control, conversion, demographic replacement, or a complete annual boundary.</p><p>The twenty-two-year comparison runs from Muhammad’s death in 632 to Lapidus’s endpoint for Iran in 654. North Africa is an interval; Iberia and Transoxiana mark later extensions. Civil wars and contested frontiers are not shown in this alpha chronology and will enter the beta map.</p><p>The second visual compares unlike evidence: one bilingual Egyptian papyrus, regional papyrus syntheses, selected coin types, and dated reforms. These reveal mechanisms and timing, not one tax rate, complete staffing, mint output, language share, or an empire-wide switch.</p><p>The third visual likewise keeps media and regions separate. A bilingual receipt, one 107-text local archive, a later narrative date for Iraq’s fiscal register, epigraphic coins, and the multilingual Qurra dossier show an overlapping language transition. They do not form an empire-wide language census or prove one switch year.</p><p>The fourth visual compares four unlike cross-border traces: dirham distributions, one excavated port, one shipwreck, and one merchant letter. Their dates and scopes remain separate; no traffic totals, annual route lines, or unified caliphal market are reconstructed.</p><p>The fifth visual follows three named books and one translator portfolio. Composition and translation dates are broad scholarly anchors; they do not measure copies, readers, curricula, textual fidelity, or influence.</p></>}>
  <section className="insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">By 654, rulers based in Arabia controlled Iraq, Syria, Egypt, and Iran.</p><h3>{labels[0]}</h3><p>In twenty-two years after 632, the first caliphs joined the former Sasanian realm to several of the richest eastern Roman provinces. Later Umayyad expansion reached North Africa, Iberia, and Transoxiana.</p><p>The remarkable result was not one uninterrupted victory line. It was the creation of a political arena spanning regions that had spent centuries on opposite sides of Roman–Sasanian war.</p></div><div className="viz-card"><div className="viz-title"><div><span>632–751 CE · regional incorporation</span><h4>{labels[0]}</h4></div><small>dated endpoints and intervals · not annual borders</small></div><AlphaChronology title="Former Roman and Sasanian provinces entered one imperial field" subtitle="Scholarly conquest chronology" events={events}/><ChartFooter source="Lapidus (2012)" note="Dates mark broad incorporation, not uniform rule, conversion, population replacement, or continuous territorial control. North Africa is a 643–711 interval." dataHref="/data/caliphates/20260831-alpha1/early-caliphate-expansion.csv"/></div></section>
  <section className="insight caliphate-tax-insight"><div className="insight-copy"><span className="insight-number">02</span><p className="claim">Early caliphs collected revenue through recognizable documents, officials, and mints before later rulers made those systems more uniformly Arabic and caliphal.</p><h3>{labels[1]}</h3><p>A Greek-Arabic receipt dated 25 April 643 records sheep delivered in Egypt as a tax down-payment. The ruler had changed, but Greek documentary practice and local collection machinery remained useful.</p><p>In Iran, early Islamic governors likewise issued silver on late-Sasanian standards, retaining familiar portraits, fire altars, Pahlavi legends, and provincial mints while adding Arabic phrases and new names.</p><p>Standardization came later. A 691–692 land survey, the epigraphic coin reform of 697, and conversion or closure of most former Arab-Sasanian mints by 703 show a second phase: old fiscal capacity was first reused, then made more legibly caliphal.</p></div><div className="viz-card caliphate-tax-viz"><div className="viz-title"><div><span>Documents + offices + mints + reforms</span><h4>{labels[1]}</h4></div><small>four evidence windows · 643–703 CE</small></div><CaliphateTaxTransition/><ChartFooter source="Demiri & Römer (2009); Foss (2009); Sijpesteijn (2013); Benfey (2024); Encyclopaedia Iranica" note="One papyrus, regional document samples, coin types, and dated reforms answer different questions. They do not produce one tax rate or an empire-wide switch date." dataHref="/data/caliphates/20260831-tax1/caliphal-fiscal-transition.csv"/></div></section>
  <section className="insight arabic-admin-insight"><div className="insight-copy"><span className="insight-number">03</span><p className="claim">The administrative language changed in layers: Arabic entered bilingual documents at conquest, became the public language of reform around 700, and still coexisted with Greek and Coptic afterward.</p><h3>{labels[2]}</h3><p>The first surviving fiscal receipt from Islamic Egypt is bilingual in Greek and Arabic. Three decades later, most of the 107 texts in one Upper Egyptian official’s archive were still Greek.</p><p>A reform wave followed. Narrative sources place Iraq’s Persian-to-Arabic fiscal-register change in 697, while the new epigraphic coinage made Arabic visible across imperial money in 697–699.</p><p>But reform did not erase local languages. The Egyptian governor Qurra’s 709–714 dossier includes Greek, Arabic, and bilingual correspondence alongside Coptic registers. Arabic had become an imperial interface; administration remained multilingual in practice.</p></div><div className="viz-card arabic-admin-viz"><div className="viz-title"><div><span>643–714 CE · five documentary clocks</span><h4>{labels[2]}</h4></div><small>unlike media and regions · no language shares</small></div><ArabicAdministrationClocks/><ChartFooter source="Demiri & Römer; Foss; Encyclopaedia Iranica; Metropolitan Museum of Art; ISAC" note="Five source windows show sequence and overlap, not one empire-wide switch. The 697 Iraqi date comes from later narratives; the Egyptian archives are local survivals, not language censuses." dataHref="/data/caliphates/20260901-arabic1/arabic-administration-clocks.csv"/></div></section>
  <section className="insight caliphate-trade-insight"><div className="insight-copy"><span className="insight-number">04</span><p className="claim">The trade network was larger than the political map: silver, ships, ports, and merchant letters joined caliphal cities to Scandinavia, China, and India.</p><h3>{labels[3]}</h3><p>Islamic silver reached Scandinavia through Khazaria and Bulgar. Siraf linked the Gulf to Indian Ocean and China routes. A ninth-century wreck in Indonesian waters carried Chinese ceramics in a western Indian Ocean shipbuilding tradition.</p><p>By the 1130s, a Judaeo-Arabic letter could coordinate prices, credit, agents, and the next ship between Aden and Mangalore. No caliph governed that whole chain. Exchange worked because merchants and ports could hand goods and obligations across jurisdictions.</p><p>The result was connection without political unity—and also coercion. Northern silver circuits were entangled with the trade in captives as well as furs.</p></div><div className="viz-card caliphate-trade-viz"><div className="viz-title"><div><span>Four cross-border traces · 9th–12th centuries</span><h4>{labels[3]}</h4></div><small>unlike evidence · no total trade map</small></div><CaliphateTradeEdges/><ChartFooter source="Jankowiak (2017); Whitehouse; Pourkerman et al.; Flecker; Princeton Geniza Project" note="Coin distributions, a port, a wreck, and a letter show different links. They do not form annual traffic, market-share, cargo-total, or complete route estimates." dataHref="/data/caliphates/20260901-trade1/caliphate-cross-border-trade.csv"/></div></section>
  <section className="insight arabic-books-insight"><div className="insight-copy"><span className="insight-number">05</span><p className="claim">Political fragmentation did not end a common scholarly language: Arabic works from Baghdad, Córdoba, and Iran entered Latin translation in Christian Iberia.</p><h3>{labels[4]}</h3><p>Al-Khwarizmi’s ninth-century algebra reached Latin readers in Robert of Chester’s 1145 translation. Around 1000, al-Zahrawi compiled surgery in Córdoba; around 1025, Ibn Sina completed his medical Canon after moving among Iranian courts.</p><p>Those books did not require one caliph to keep moving. In twelfth-century Toledo, Gerard of Cremona and other translators worked across Arabic and Latin, drawing on texts produced under rival dynasties and on Arabic versions of older Greek works.</p><p>The strongest claim is therefore institutional, not civilizational. A portable scholarly language, manuscripts, and translators connected courts that did not share a ruler.</p></div><div className="viz-card arabic-books-viz"><div className="viz-title"><div><span>Three books + one translation portfolio</span><h4>{labels[4]}</h4></div><small>9th–12th centuries · documented journeys</small></div><ArabicBookJourneys/><ChartFooter source="Burnett (2001); Oxford MPLS; U.S. National Library of Medicine" note="The paths show composition and translation across political boundaries. They do not estimate manuscript counts, readership, textual fidelity, curricular use, or causal influence." dataHref="/data/caliphates/20260901-books1/arabic-book-journeys.csv"/></div></section>
  </HistoryPageShell>}
