import type { Metadata } from 'next';
import AlphaChronology from '../components/AlphaChronology';
import AlphaPendingInsight from '../components/AlphaPendingInsight';
import ChartFooter from '../components/ChartFooter';
import HistoryPageShell from '../components/HistoryPageShell';

export const metadata:Metadata={title:'The Caliphates',description:'Five visual arguments about conquest, inherited administration, Arabic, trade, and a connected post-imperial world.',openGraph:{title:'The Caliphates — How Everything Evolved',description:'The first caliphates joined former Roman and Sasanian lands within twenty-two years.',images:[]},twitter:{card:'summary',title:'The Caliphates — How Everything Evolved',description:'The first caliphates joined former Roman and Sasanian lands within twenty-two years.',images:[]}};
const labels=['The first caliphates joined former Roman and Sasanian lands within twenty-two years','Conquest reused tax systems before it standardized them','Arabic became an administrative interface over generations—not overnight','Trade tied together seas that no caliph controlled alone','A shared scholarly world outlived political unity'];
const events=[
  {year:632,displayYear:'632 CE',label:'Arabian political core',detail:'Muhammad died after authority had expanded across much of Arabia.',kind:'political baseline'},
  {year:641,displayYear:'by 641',label:'Iraq, Syria, and Egypt',detail:'Former Sasanian and eastern Roman provinces were under the new rulers.',kind:'conquest endpoint'},
  {year:654,displayYear:'by 654',label:'Iran',detail:'The Sasanian imperial realm had been incorporated.',kind:'conquest endpoint'},
  {year:711,displayYear:'643–711',label:'North Africa',detail:'Expansion across North Africa ended the remaining eastern Roman position there.',kind:'conquest interval'},
  {year:712,displayYear:'from 711',label:'Iberia',detail:'Armies crossed into Iberia and began another regional conquest.',kind:'conquest opening'},
  {year:751,displayYear:'by 751',label:'Transoxiana',detail:'Territory between the Oxus and Jaxartes was incorporated into the wider imperial sphere.',kind:'conquest endpoint'},
];
export default function CaliphatesPage(){return <HistoryPageShell title="The Caliphates" eyebrow="632–1258 CE" standfirst="Rapid conquest joined old imperial worlds; institutions made the connection last." status="draft" progress="1 of 5 insights live" published="August 2026" insightLabels={labels}
  introduction={<><p>The early caliphates did more than replace rulers. Their conquests brought Arabia, the former Sasanian realm, and large eastern Roman provinces into one political field, then adapted the tax systems, cities, languages, and exchange networks already operating there.</p><p>The five claims separate rapid territorial expansion from the slower construction of an Arabic-speaking, legally plural, commercially connected, and intellectually shared world.</p></>}
  methods={<><p>The first visual follows Ira Lapidus’s compact scholarly chronology. “Conquered” marks broad political incorporation, not uniform control, conversion, demographic replacement, or a complete annual boundary.</p><p>The twenty-two-year comparison runs from Muhammad’s death in 632 to Lapidus’s endpoint for Iran in 654. North Africa is an interval; Iberia and Transoxiana mark later extensions. Civil wars and contested frontiers are not shown in this alpha chronology and will enter the beta map.</p></>}>
  <section className="insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">By 654, rulers based in Arabia controlled Iraq, Syria, Egypt, and Iran.</p><h3>{labels[0]}</h3><p>In twenty-two years after 632, the first caliphs joined the former Sasanian realm to several of the richest eastern Roman provinces. Later Umayyad expansion reached North Africa, Iberia, and Transoxiana.</p><p>The remarkable result was not one uninterrupted victory line. It was the creation of a political arena spanning regions that had spent centuries on opposite sides of Roman–Sasanian war.</p></div><div className="viz-card"><div className="viz-title"><div><span>632–751 CE · regional incorporation</span><h4>{labels[0]}</h4></div><small>dated endpoints and intervals · not annual borders</small></div><AlphaChronology title="Former Roman and Sasanian provinces entered one imperial field" subtitle="Scholarly conquest chronology" events={events}/><ChartFooter source="Lapidus (2012)" note="Dates mark broad incorporation, not uniform rule, conversion, population replacement, or continuous territorial control. North Africa is a 643–711 interval." dataHref="/data/caliphates/20260831-alpha1/early-caliphate-expansion.csv"/></div></section>
  <AlphaPendingInsight number="02" title={labels[1]} question="Which Byzantine and Sasanian taxes, offices, documents, and mints continued, and where did conquerors redesign them?"/>
  <AlphaPendingInsight number="03" title={labels[2]} question="How quickly did Arabic replace Greek, Persian, Coptic, and other administrative languages across different regions and media?"/>
  <AlphaPendingInsight number="04" title={labels[3]} question="Which ports, caravan cities, merchant institutions, and commodity routes connected the Atlantic, Mediterranean, Indian Ocean, and Central Asia?"/>
  <AlphaPendingInsight number="05" title={labels[4]} question="How far did books, scholars, legal schools, scientific texts, and commercial practices circulate after caliphal political unity fractured?"/>
  </HistoryPageShell>}
