import type { Metadata } from 'next';
import BronzeMetalNetwork from '../BronzeMetalNetwork';
import EvidencePanel from '../components/EvidencePanel';
import HistoryPageShell from '../components/HistoryPageShell';

export const metadata:Metadata={
  title:'The Bronze Age world system',
  description:'How copper and tin connected distant mines, ports, workshops, and courts—without pretending the surviving evidence is a complete trade map.',
  openGraph:{title:'The Bronze Age world system — How Everything Evolved',description:'Copper was regional. Tin was scarce. Bronze joined them in a long-distance production network.',images:[]},
  twitter:{card:'summary',title:'The Bronze Age world system — How Everything Evolved',description:'An evidence map of copper, tin, one ship cargo, analytical provenance, and textual exchange.',images:[]},
};

const Placeholder=({number,claim,title,copy}:{number:string;claim:string;title:string;copy:string})=><section className="insight insight-placeholder"><div className="insight-copy"><span className="insight-number">{number}</span><p className="claim">{claim}</p><h3>{title}</h3><p>{copy}</p><span className="status status-research">research · visual in development</span></div></section>;

export default function BronzeAgePage(){return <HistoryPageShell
  title="The Bronze Age world system"
  eyebrow="3300–1200 BCE · metals · palaces · connected seas"
  standfirst="Bronze was not one invention. It was a supply chain that joined landscapes, ports, workshops, and courts."
  status="draft"
  progress="1 of 5 insights live"
  published="August 2026"
  introduction={<><p>The Bronze Age is often introduced as a better material replacing an older one. That misses the historical system. Copper ores were available in many regions; tin was much scarcer. Making bronze at scale therefore joined unlike landscapes through prospecting, mining, transport, exchange, storage, alloying, and skilled craft.</p><p>Those connections are visible, but incompletely. A wreck preserves one shipment. Chemical and isotopic analyses can connect metal to ore fields, sometimes securely and sometimes not. Tablets record relationships without preserving the itinerary or the cargo. No surviving source gives an annual traffic series for the whole system.</p><p>This page begins with Europe, the Mediterranean, and western and central Asia. “World system” is an analytical description of overlapping long-distance networks—not a claim that they covered the entire planet, formed one market, or were controlled from one center.</p></>}
  insightHeading={<>Distant materials.<br/>Interdependent societies.</>}
  methods={<><p>The map separates four evidence classes instead of combining them into a reconstructed flow model: one archaeologically observed ship cargo; an isotopic comparison of seventy-eight copper ingots; a multi-method tin-provenance signal; and one textual exchange relationship. Lines connect an observation to the places named or tested by its source. They are not roads, shipping itineraries, market shares, or annual quantities.</p><p>Uluburun is a late-fourteenth-century BCE time capsule, not a typical-year estimate. Its roughly ten tonnes of copper and one tonne of tin describe that wreck. The copper is consistent with Cypriot ores, especially Apliki. Tin is different: Powell and colleagues proposed Mušiston and Taurus sources in 2022; Berger and colleagues rejected the specific Mušiston match in 2023 and found no definite source. The visual keeps both publications visible rather than choosing certainty the evidence does not supply.</p><p>The Atlantic view follows Williams and colleagues’ three-method compatibility between Cornwall–Devon ores and ingots from shipwrecks off Israel. The authors explicitly report no evidence for a direct Britain-to-Levant connection. Sardinia is shown only as a possible intermediary, never as an observed leg. The Mari–Ugarit–Minoan relationship likewise remains textual evidence, not a mine or cargo reconstruction.</p><p>The labels “copper” and “tin” identify the material under discussion, not pure-metal guarantees for every object. Coordinates locate evidence places and broad find regions; they are not territorial boundaries. The downloadable tables preserve every source key, observation, evidence status, and inference limit.</p><EvidencePanel page="bronze-age"/></>}
>
  <section className="insight bronze-network-insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">Copper was common enough to build regional industries. Tin was scarce enough to connect them.</p><h3>The Bronze Age was a supply chain before it was an age</h3><p>At Uluburun, copper and tin physically converged in one ship: about ten tonnes of copper and one tonne of tin. The copper points strongly toward Cyprus. The tin does not resolve into one accepted source—a useful reminder that the best-preserved cargo is not the same thing as a complete map.</p><p>The larger system appears in overlapping fragments. Cypriot copper ingots reached at least six find regions in one isotopic study. Tin ingots wrecked off Israel carry a signal compatible with Cornwall and Devon, but not proof of a direct voyage. A Mari text places Ugarit, Minoans, and a translator in a tin exchange without telling us where the ore began.</p><p>Together these observations support a strong claim and reject a tempting one. Bronze production depended on long-distance coordination. We cannot responsibly turn that dependence into smooth annual trade flows or a single route network.</p><a className="source-link" href="https://doi.org/10.15184/aqy.2025.41">Read the open Atlantic tin study ↗</a></div><div className="viz-card bronze-network-viz"><div className="viz-title"><div><span>Four evidence views · copper and tin</span><h4>What can we actually connect?</h4></div><small>c. 18th–13th centuries BCE · no traffic model</small></div><BronzeMetalNetwork/><p className="viz-note"><b>Method:</b> Select an evidence view, then a place. Solid lines show analytical connections; dashed lines show textual relationships or hypotheses. Every line exposes what it cannot establish.</p></div></section>
  <Placeholder number="02" claim="Palaces made distant materials governable by concentrating records, stores, and specialists." title="Storage became administration" copy="The next insight will compare archives, workshops, magazines, and redistribution without treating every palace as one centrally planned economy."/>
  <Placeholder number="03" claim="Chariots were not a wonder weapon. They were an elite system of horses, wheels, crews, land, and maintenance." title="Speed had a supply chain" copy="This section will visualize the inputs and constraints behind chariot forces rather than rank armies by a single technology score."/>
  <Placeholder number="04" claim="Ports and cargoes connected the eastern Mediterranean more tightly than political borders imply." title="Ships made a shared material world" copy="This section will compare documented cargoes and exchange relationships while keeping wreck survival and route uncertainty visible."/>
  <Placeholder number="05" claim="The Late Bronze Age collapse was a systems failure, not one invasion, drought, earthquake, or rebellion." title="Connected systems can fail together" copy="This section will set competing explanations on one chronology and distinguish local destruction from regional institutional change."/>
</HistoryPageShell>}
