'use client';

import { useEffect, useMemo, useState } from 'react';
import { fetchClientText } from './lib/clientAsset';

type Row={work_id:string;work_order:string;work_title:string;field:string;origin_period:string;origin_place:string;origin_political_context:string;origin_language:string;translation_period:string;translation_place:string;translation_political_context:string;output_language:string;evidence:string;quantitative_anchor:string;source_keys:string;limits:string};
const DATA_URL='/data/caliphates/20260901-books1/arabic-book-journeys.csv';
function parseCSV<T>(text:string):T[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const[headers,...body]=rows;return body.map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])) as T);}
export default function ArabicBookJourneys(){const[rows,setRows]=useState<Row[]>([]);const[state,setState]=useState<'loading'|'ready'|'error'>('loading');const[error,setError]=useState('');const[attempt,setAttempt]=useState(0);const[selectedId,setSelectedId]=useState('khwarizmi_algebra');useEffect(()=>{const controller=new AbortController();fetchClientText(DATA_URL,{signal:controller.signal,label:'Arabic book journeys'}).then(text=>{const parsed=parseCSV<Row>(text);if(parsed.length!==4||parsed.some(row=>!row.work_id||!row.work_title||!row.origin_place||!row.translation_place||!row.evidence||!row.source_keys))throw new Error('The book-journey evidence used an incompatible data contract.');setRows(parsed);setState('ready');}).catch(problem=>{if(controller.signal.aborted)return;setError(problem instanceof Error?problem.message:'The book journeys could not be loaded.');setState('error');});return()=>controller.abort();},[attempt]);const selected=useMemo(()=>rows.find(row=>row.work_id===selectedId)??rows[0],[rows,selectedId]);if(state!=='ready'||!selected)return <div className={`data-state arabic-books-state ${state}`} role={state==='error'?'alert':'status'}><b>{state==='error'?'The book journeys did not load':'Loading book journeys…'}</b><span>{state==='error'?error:'Baghdad · Córdoba · Hamadan · Toledo'}</span>{state==='error'&&<button type="button" onClick={()=>{setError('');setState('loading');setAttempt(value=>value+1);}}>Retry evidence</button>}</div>;return <div className="arabic-books-chart"><div className="arabic-books-axis"><span>Different courts</span><i>→</i><strong>Arabic books</strong><i>→</i><span>Latin Toledo</span></div><div className="arabic-books-lanes">{rows.map(row=><button type="button" key={row.work_id} className={selected.work_id===row.work_id?'active':''} aria-pressed={selected.work_id===row.work_id} onClick={()=>setSelectedId(row.work_id)}><span>{row.origin_period} · {row.field}</span><b>{row.work_title}</b><div><strong>{row.origin_place}</strong><em>→</em><strong>{row.translation_place}</strong></div><small>{row.quantitative_anchor}</small></button>)}</div><section aria-live="polite"><header><div><span>{selected.origin_political_context}</span><h5>{selected.work_title}</h5></div><strong>{selected.origin_language} → {selected.output_language}</strong></header><div className="arabic-books-detail"><article><span>Documented journey</span><p>{selected.evidence}</p></article><article><span>Translation setting</span><b>{selected.translation_period} · {selected.translation_place}</b><p>{selected.translation_political_context}</p></article><article><span>Limit</span><p>{selected.limits}</p></article></div></section><p className="arabic-books-takeaway"><strong>The state fractured; the reading language traveled.</strong> Baghdad, Córdoba, and Iranian courts produced or preserved works that translators carried into a different political and linguistic world.</p></div>}
