'use client';

import { useEffect, useState } from 'react';
import { fetchClientText } from './lib/clientAsset';

type Row={window_id:string;window_order:string;display_period:string;region:string;medium:string;languages:string;headline:string;evidence:string;source_keys:string;limits:string};
const DATA_URL='/data/caliphates/20260901-arabic1/arabic-administration-clocks.csv';
function parseCSV<T>(text:string):T[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const[headers,...body]=rows;return body.map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])) as T);}
export default function ArabicAdministrationClocks(){const[rows,setRows]=useState<Row[]>([]);const[state,setState]=useState<'loading'|'ready'|'error'>('loading');const[error,setError]=useState('');const[attempt,setAttempt]=useState(0);useEffect(()=>{const controller=new AbortController();fetchClientText(DATA_URL,{signal:controller.signal,label:'Arabic administration evidence'}).then(text=>{const parsed=parseCSV<Row>(text);if(parsed.length!==5||parsed.some(row=>!row.window_id||!row.display_period||!row.languages||!row.headline||!row.evidence||!row.source_keys))throw new Error('The Arabic-administration evidence used an incompatible data contract.');setRows(parsed);setState('ready');}).catch(problem=>{if(controller.signal.aborted)return;setError(problem instanceof Error?problem.message:'The evidence could not be loaded.');setState('error');});return()=>controller.abort();},[attempt]);if(state!=='ready')return <div className={`data-state arabic-admin-state ${state}`} role={state==='error'?'alert':'status'}><b>{state==='error'?'The administrative-language evidence did not load':'Loading administrative-language evidence…'}</b><span>{state==='error'?error:'Greek · Persian · Arabic · Coptic'}</span>{state==='error'&&<button type="button" onClick={()=>{setError('');setState('loading');setAttempt(value=>value+1);}}>Retry evidence</button>}</div>;return <div className="arabic-admin-chart"><div className="arabic-admin-axis" aria-hidden="true"><span>Conquest</span><i/><span>Reform wave</span><i/><span>Multilingual practice</span></div><div className="arabic-admin-windows">{rows.map((row,index)=><article key={row.window_id} className={index===2||index===3?'reform':''}><header><span>{row.display_period}</span><b>{row.region}</b></header><div className="arabic-admin-language">{row.languages.split(' + ').map(language=><em key={language}>{language}</em>)}</div><h5>{row.headline}</h5><p>{row.evidence}</p><small>{row.medium}</small></article>)}</div><p className="arabic-admin-takeaway"><strong>The overlap is the argument.</strong> Arabic became an imperial administrative language through a visible reform wave, while local government continued to work across inherited languages and scribal systems.</p></div>}
