'use client';

import { useMemo, useState } from 'react';

type Status = 'research' | 'draft' | 'reviewed';
type AtlasPage = { number: string; title: string; years: string; era: string; region: string; system: string; status: Status; progress: string; thesis: string; href?: string };

const pages: AtlasPage[] = [
  { number:'01', title:'Rome', years:'500 BCE–476 CE', era:'Iron Age', region:'Mediterranean', system:'States', status:'draft', progress:'5 of 5 live', thesis:'How an Italian coalition became a continental state—and why the Roman state survived its western court.', href:'/rome'},
  { number:'02', title:'Uruk and the first states', years:'7000–2900 BCE', era:'First cities', region:'Mesopotamia', system:'States', status:'reviewed', progress:'5 of 5 live', thesis:'Water, grain, writing, and organized labor made people and landscapes newly legible—without making control complete.', href:'/uruk' },
  { number:'03', title:'The cradles of civilization', years:'4000 BCE–1550 CE', era:'First cities', region:'Global', system:'Ecology', status:'reviewed', progress:'5 of 5 live', thesis:'Cities, states, monuments, notation, coordination, and collapse followed different clocks and pathways.', href:'/cradles' },
  { number:'04', title:'The Bronze Age world system', years:'3300–1050 BCE', era:'Bronze Age', region:'Eurasia', system:'Networks', status:'reviewed', progress:'5 of 5 live', thesis:'Distant materials and selective institutions made societies powerful, connected, and vulnerable without producing one synchronized collapse.', href:'/bronze-age' },
  { number:'05', title:'The Iron Age transformation', years:'2000–400 BCE', era:'Iron Age', region:'Eurasia', system:'Technology', status:'reviewed', progress:'5 of 5 live', thesis:'Iron became transformative when fuel, furnaces, skills, exchange, and institutions made production repeatable—not when someone first found the metal.', href:'/iron-age' },
  { number:'06', title:'Persia and territorial empire', years:'550 BCE–651 CE', era:'Iron Age', region:'Eurasia', system:'States', status:'reviewed', progress:'5 of 5 live', thesis:'Roads, provinces, obligations, coalition armies, and reusable institutions made imperial scale outlast one dynasty.', href:'/persia' },
  { number:'07', title:'Qin and Han China', years:'475 BCE–220 CE', era:'Classical', region:'East Asia', system:'States', status:'reviewed', progress:'5 of 5 live', thesis:'Competition built mobilizing systems; standards and a maintained logistics ecology made distance governable.', href:'/qin-han' },
  { number:'08', title:'India from cities to empires', years:'2600 BCE–550 CE', era:'Classical', region:'South Asia', system:'Trade', status:'reviewed', progress:'5 of 5 live', thesis:'Shared measures, monsoon ecologies, cities, empires, religions, and trade coordinated South Asia on overlapping geographies.', href:'/india' },
  { number:'09', title:'The Steppe', years:'3500 BCE–1500 CE', era:'Long duration', region:'Eurasia', system:'War', status:'draft', progress:'2 of 5 live', thesis:'Pastoral mobility preceded cavalry, then repeatedly changed agrarian states, trade, warfare, languages, and populations.', href:'/steppe' },
  { number:'10', title:'Christianity', years:'30–800 CE', era:'Late Antiquity', region:'Mediterranean', system:'Belief', status:'draft', progress:'2 of 5 live', thesis:'Letters, cities, bishops, ritual, and charity made institutions that outlasted western empire.', href:'/christianity' },
  { number:'11', title:'The Caliphates', years:'632–1258 CE', era:'Medieval', region:'Afro-Eurasia', system:'States', status:'draft', progress:'2 of 5 live', thesis:'Conquest joined old imperial worlds; administration, Arabic, law, trade, and scholarship made the connection last.', href:'/caliphates' },
  { number:'12', title:'Greek City-States', years:'800–338 BCE', era:'Classical', region:'Mediterranean', system:'States', status:'draft', progress:'2 of 5 live', thesis:'Small political territories made citizenship intensely local while leagues and empires repeatedly tested the limits of the polis.', href:'/greek-city-states' },
  { number:'13', title:'Hellenistic Kingdoms', years:'323–30 BCE', era:'Classical', region:'Mediterranean', system:'War', status:'draft', progress:'2 of 5 live', thesis:'Alexander’s successors built royal systems from mixed armies, capitals, settlements, money, and durable local institutions.', href:'/hellenistic-kingdoms' },
  { number:'14', title:'Silk Roads', years:'200 BCE–1500 CE', era:'Long duration', region:'Eurasia', system:'Trade', status:'draft', progress:'1 of 5 live', thesis:'Changing chains of oasis economies, merchants, states, religious institutions, and sea lanes connected Eurasia.', href:'/silk-roads' },
  { number:'15', title:'Medieval Europe', years:'500–1500 CE', era:'Medieval', region:'Europe', system:'States', status:'draft', progress:'1 of 5 live', thesis:'Layered power coexisted with expanding manuscripts, towns, church institutions, markets, and territorial states.', href:'/medieval-europe' },
  { number:'16', title:'African States and Trade', years:'300–1500 CE', era:'Medieval', region:'Africa', system:'Trade', status:'draft', progress:'1 of 5 live', thesis:'River valleys, highlands, cattle landscapes, ports, mines, and corridors produced many routes to political scale.', href:'/african-states' },
  { number:'17', title:'Southeast Asian Mandalas', years:'500 BCE–1500 CE', era:'Long duration', region:'Southeast Asia', system:'Trade', status:'draft', progress:'1 of 5 live', thesis:'Workshop ports, river systems, temples, and overlapping centers made authority mobile across a maritime region.', href:'/southeast-asia' },
  { number:'18', title:'Mesoamerican Cities and States', years:'1000 BCE–1500 CE', era:'Long duration', region:'Mesoamerica', system:'Ecology', status:'draft', progress:'1 of 5 live', thesis:'Dense cities and countryside depended on engineered landscapes, writing, markets, and political systems that repeatedly reorganized.', href:'/mesoamerica' },
  { number:'19', title:'Andean Worlds and the Inka', years:'1000 BCE–1533 CE', era:'Long duration', region:'Andes', system:'States', status:'draft', progress:'1 of 5 live', thesis:'Roads, ecological portfolios, labor obligations, and knotted records coordinated an exceptionally vertical political world.', href:'/andes' },
  { number:'20', title:'Mongol Eurasia', years:'1206–1500 CE', era:'Medieval', region:'Eurasia', system:'Networks', status:'draft', progress:'1 of 5 live', thesis:'Conquest joined armies, relays, merchants, disease ecologies, and successor states across a continental space.', href:'/mongol-eurasia' },
  { number:'21', title:'Gunpowder Empires', years:'1450–1800 CE', era:'Early modern', region:'Eurasia', system:'War', status:'draft', progress:'1 of 5 live', thesis:'Cannon changed walls, muskets changed infantry, and paying for both changed states.', href:'/gunpowder-empires' },
  { number:'22', title:'Oceanic Navigation', years:'1400–1815 CE', era:'Early modern', region:'Global', system:'Networks', status:'draft', progress:'1 of 5 live', thesis:'Open-ocean routes joined continents through seasonal knowledge, skilled labor, monopolies, exchange, and coercion.', href:'/oceanic-navigation' },
  { number:'23', title:'The Great Divergence', years:'1500–1800 CE', era:'Early modern', region:'Global', system:'Economy', status:'draft', progress:'1 of 5 live', thesis:'Wages, energy, ecology, states, and empire created unequal incentives before factories transformed output.', href:'/great-divergence' },
];

const filterValues = { era:['All','First cities','Bronze Age','Iron Age','Classical','Late Antiquity','Medieval','Early modern','Long duration'], region:['All','Global','Mesopotamia','Mediterranean','Eurasia','East Asia','South Asia','Afro-Eurasia','Europe','Africa','Southeast Asia','Mesoamerica','Andes'], system:['All','States','Ecology','Trade','Technology','War','Belief','Networks','Economy'] } as const;

export default function AtlasExplorer(){
  const [dimension,setDimension]=useState<keyof typeof filterValues>('era');
  const [filter,setFilter]=useState('All');
  const visible=useMemo(()=>pages.filter(page=>filter==='All'||page[dimension]===filter),[dimension,filter]);
  const chooseDimension=(value:keyof typeof filterValues)=>{setDimension(value);setFilter('All');};
  return <section className="atlas" id="atlas">
    <div className="atlas-heading"><div><p className="topic-label">The atlas</p><h2>History as systems<br/>you can see.</h2></div><p>Pages are published as their evidence and visuals become strong enough. <b>Draft</b> pages contain live, auditable work; <b>research</b> pages show the committed sequence.</p></div>
    <div className="atlas-controls" aria-label="Filter atlas pages"><div className="dimension-tabs">{(['era','region','system'] as const).map(value=><button type="button" className={dimension===value?'active':''} onClick={()=>chooseDimension(value)} key={value}>By {value}</button>)}</div><div className="filter-tabs">{filterValues[dimension].map(value=><button type="button" className={filter===value?'active':''} onClick={()=>setFilter(value)} key={value}>{value}</button>)}</div></div>
    <div className="atlas-count"><b>{visible.length}</b> {visible.length===1?'page':'pages'} in this view</div>
    <div className="atlas-grid">{visible.map(page=>{
      const content=<><div className="card-top"><span>{page.number}</span><i className={`status status-${page.status}`}>{page.status}</i></div><p className="card-years">{page.years}</p><h3>{page.title}</h3><p className="card-thesis">{page.thesis}</p><div className="card-meta"><span>{page.era}</span><span>{page.region}</span><span>{page.system}</span></div><div className="card-progress">{page.progress}<b>{page.href?'Read the page →':'In the research queue'}</b></div></>;
      return page.href?<a className="atlas-card live" href={page.href} key={page.number}>{content}</a>:<article className="atlas-card" key={page.number}>{content}</article>;
    })}</div>
  </section>;
}
