'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { fetchClientJson, fetchClientText } from './lib/clientAsset';

type Point=[number,number];
type Geometry={type:string;arcs:unknown};
type Topology={transform:{scale:Point;translate:Point};arcs:Point[][];objects:Record<string,{geometries:Geometry[]}>};
type MaritimeCase={case_id:string;name:string;case_kind:string;date_window:string;latitude:string;longitude:string;political_setting:string;anchor_value:string;anchor_label:string;carrier:string;evidence:string;interpretation:string;source_keys:string;limits:string};
type MaritimeLink={case_id:string;link_id:string;region:string;latitude:string;longitude:string;material:string;evidence_class:string;observation:string;source_keys:string;limits:string};

const REVISION='20260830-maritime1';
const casesUrl=`/data/bronze-age/${REVISION}/bronze-maritime-cases.csv`;
const linksUrl=`/data/bronze-age/${REVISION}/bronze-maritime-links.csv`;
const landUrl='/data/land.topojson';
const order=['uluburun','cape-gelidonya','point-iria','kommos','hala-sultan-tekke'];
const colors:Record<string,string>={'uluburun':'#a5483f','cape-gelidonya':'#9a6b35','point-iria':'#6c5c86','kommos':'#477184','hala-sultan-tekke':'#58784d'};
const MIN_LON=6,MAX_LON=43,MIN_LAT=27,MAX_LAT=40.5;

function parseCSV<T>(text:string):T[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const[headers,...body]=rows;return body.map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])) as T);}
function decodeArc(topology:Topology,index:number):Point[]{const reversed=index<0,arc=topology.arcs[reversed?~index:index];let x=0,y=0;const points=arc.map(([dx,dy])=>{x+=dx;y+=dy;return[x*topology.transform.scale[0]+topology.transform.translate[0],y*topology.transform.scale[1]+topology.transform.translate[1]] as Point;});return reversed?points.reverse():points;}
function topoRings(topology:Topology,geometry:Geometry):Point[][]{const polygons=geometry.type==='Polygon'?[geometry.arcs]:geometry.arcs as number[][][];return(polygons as number[][][]).flatMap(poly=>poly.map(ring=>ring.flatMap((arc,index)=>{const points=decodeArc(topology,arc);return index?points.slice(1):points;})));}
function project([lon,lat]:Point,width:number,height:number):Point{return[((lon-MIN_LON)/(MAX_LON-MIN_LON))*width,((MAX_LAT-lat)/(MAX_LAT-MIN_LAT))*height];}
function label(value:string){return value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());}

export default function BronzeMaritimeNetwork(){
  const canvas=useRef<HTMLCanvasElement>(null);
  const[cases,setCases]=useState<MaritimeCase[]>([]);const[links,setLinks]=useState<MaritimeLink[]>([]);const[land,setLand]=useState<Topology|null>(null);
  const[state,setState]=useState<'loading'|'ready'|'error'>('loading');const[error,setError]=useState('');const[selectedCase,setSelectedCase]=useState('uluburun');const[selectedLink,setSelectedLink]=useState('uluburun-cyprus');const[attempt,setAttempt]=useState(0);
  useEffect(()=>{const controller=new AbortController();Promise.all([
    fetchClientText(casesUrl,{signal:controller.signal,label:'Maritime cases'}).then(parseCSV<MaritimeCase>),
    fetchClientText(linksUrl,{signal:controller.signal,label:'Maritime connections'}).then(parseCSV<MaritimeLink>),
    fetchClientJson<Topology>(landUrl,{signal:controller.signal,label:'Basemap'}),
  ]).then(([caseRows,linkRows,topology])=>{if(caseRows.length!==5||linkRows.length!==19||new Set(caseRows.map(row=>row.case_id)).size!==5||!topology?.objects?.['10m_land']||caseRows.some(row=>!row.limits||!row.source_keys)||linkRows.some(row=>!row.limits||!row.source_keys))throw new Error('The maritime evidence response used an incompatible schema.');setCases(caseRows);setLinks(linkRows);setLand(topology);setState('ready');}).catch(problem=>{if(controller.signal.aborted)return;setError(problem instanceof Error?problem.message:'The maritime evidence could not be loaded.');setState('error');});return()=>controller.abort();},[attempt]);
  const active=useMemo(()=>cases.find(row=>row.case_id===selectedCase)??cases[0],[cases,selectedCase]);
  const activeLinks=useMemo(()=>links.filter(row=>row.case_id===active?.case_id),[links,active]);
  const activeLink=activeLinks.find(row=>row.link_id===selectedLink)??activeLinks[0];
  useEffect(()=>{if(!canvas.current||!land||!active||!activeLink)return;const ctx=canvas.current.getContext('2d');if(!ctx)return;const width=ctx.canvas.width,height=ctx.canvas.height;ctx.clearRect(0,0,width,height);const sea=ctx.createLinearGradient(0,0,0,height);sea.addColorStop(0,'#dcebf0');sea.addColorStop(1,'#c7dde5');ctx.fillStyle=sea;ctx.fillRect(0,0,width,height);ctx.strokeStyle='rgba(65,99,115,.12)';ctx.lineWidth=1;for(let lon=20;lon<=40;lon+=5){const[x]=project([lon,0],width,height);ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,height);ctx.stroke();}for(let lat=30;lat<=40;lat+=5){const[,y]=project([0,lat],width,height);ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(width,y);ctx.stroke();}for(const geometry of land.objects['10m_land'].geometries){ctx.beginPath();for(const ring of topoRings(land,geometry)){if(!ring.some(([lon,lat])=>lon>MIN_LON-5&&lon<MAX_LON+5&&lat>MIN_LAT-5&&lat<MAX_LAT+5))continue;ring.forEach((point,index)=>{const[x,y]=project(point,width,height);if(index===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});}ctx.fillStyle='#eee9dc';ctx.fill('evenodd');ctx.strokeStyle='#aeb8b7';ctx.lineWidth=.7;ctx.stroke();}
    const origin:[number,number]=project([Number(active.longitude),Number(active.latitude)],width,height);for(const link of activeLinks){const target=project([Number(link.longitude),Number(link.latitude)],width,height),selected=link.link_id===activeLink.link_id;ctx.save();ctx.strokeStyle=colors[active.case_id];ctx.lineWidth=selected?4:2;ctx.globalAlpha=selected?.9:.45;ctx.setLineDash([8,7]);ctx.beginPath();ctx.moveTo(...origin);ctx.quadraticCurveTo((origin[0]+target[0])/2,(origin[1]+target[1])/2-Math.max(15,Math.abs(target[0]-origin[0])*.1),...target);ctx.stroke();ctx.restore();ctx.beginPath();ctx.arc(target[0],target[1],selected?9:6,0,Math.PI*2);ctx.fillStyle=selected?'#fff':colors[active.case_id];ctx.fill();ctx.strokeStyle=colors[active.case_id];ctx.lineWidth=selected?4:2;ctx.stroke();ctx.font=`${selected?'700':'600'} 11px Arial`;ctx.fillStyle='#263843';ctx.textAlign=target[0]>width*.8?'right':'left';ctx.fillText(link.region,target[0]+(target[0]>width*.8?-12:12),target[1]-9);}
    ctx.beginPath();ctx.arc(origin[0],origin[1],11,0,Math.PI*2);ctx.fillStyle=colors[active.case_id];ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=4;ctx.stroke();ctx.font='700 12px Arial';ctx.fillStyle='#173a5d';ctx.textAlign=origin[0]>width*.76?'right':'left';ctx.fillText(active.name,origin[0]+(origin[0]>width*.76?-15:15),origin[1]+18);},[land,active,activeLinks,activeLink]);
  const chooseCase=(id:string)=>{setSelectedCase(id);const first=links.find(row=>row.case_id===id);if(first)setSelectedLink(first.link_id);};
  const chooseFromMap=(clientX:number,clientY:number)=>{const element=canvas.current;if(!element)return;const rect=element.getBoundingClientRect(),point:[number,number]=[((clientX-rect.left)/rect.width)*element.width,((clientY-rect.top)/rect.height)*element.height];let winner:string|undefined,nearest=28;for(const link of activeLinks){const marker=project([Number(link.longitude),Number(link.latitude)],element.width,element.height),distance=Math.hypot(marker[0]-point[0],marker[1]-point[1]);if(distance<nearest){winner=link.link_id;nearest=distance;}}if(winner)setSelectedLink(winner);};
  const retry=()=>{setCases([]);setLinks([]);setLand(null);setError('');setState('loading');setAttempt(value=>value+1);};
  if(state!=='ready'||!active||!activeLink)return <div className={`data-state maritime-data-state ${state}`} role={state==='error'?'alert':'status'}><b>{state==='error'?'The maritime evidence did not load':'Loading five ports and cargoes…'}</b><span>{state==='error'?error:'wrecks · harbors · mixed connections'}</span>{state==='error'&&<button type="button" onClick={retry}>Retry maritime evidence</button>}</div>;
  return <div className="maritime-chart" style={{'--maritime-color':colors[active.case_id]} as React.CSSProperties}>
    <nav className="maritime-tabs" aria-label="Choose a Bronze Age maritime evidence window">{order.map(id=>{const row=cases.find(item=>item.case_id===id)!;return <button type="button" key={id} className={active.case_id===id?'active':''} aria-pressed={active.case_id===id} onClick={()=>chooseCase(id)} style={{'--tab-color':colors[id]} as React.CSSProperties}><i/><span><b>{row.name}</b><small>{label(row.case_kind)} · {row.date_window}</small></span></button>})}</nav>
    <section className="maritime-map"><header><div><span>{label(active.case_kind)} · {active.date_window}</span><h5>{active.name}: one network window</h5></div><small>{active.political_setting}</small></header><div className="maritime-map-stage"><canvas ref={canvas} width="1100" height="520" onPointerDown={event=>chooseFromMap(event.clientX,event.clientY)} aria-label={`${active.name} maritime evidence map; ${activeLink.region} selected`}/><div className="maritime-map-legend"><i/><span>Evidence association</span><small>Dashed lines do not reconstruct a sailing route.</small></div></div>
      <nav className="maritime-origin-list" aria-label={`Choose a connection for ${active.name}`}>{activeLinks.map(link=><button type="button" key={link.link_id} className={activeLink.link_id===link.link_id?'active':''} aria-pressed={activeLink.link_id===link.link_id} onClick={()=>setSelectedLink(link.link_id)}><i/><span><b>{link.region}</b><small>{label(link.evidence_class)}</small></span></button>)}</nav></section>
    <section className="maritime-case-readout"><div><span>{active.carrier}</span><b>{active.anchor_value}</b><small>{active.anchor_label}</small></div><div><p>{active.evidence}</p><strong>{active.interpretation}</strong><small>{active.limits}</small></div></section>
    <section className="maritime-link-readout" aria-live="polite"><div><h5>{active.name} ↔ {activeLink.region}</h5></div><div><p>{activeLink.observation}</p><small>{activeLink.limits}</small></div></section>
    <section className="maritime-ledger"><header><div><span>One sea · multiple institutions</span><h5>The cargo type changes with the carrier</h5></div><small>Categories describe interpretations, not an evolutionary sequence.</small></header><div>{order.map(id=>{const row=cases.find(item=>item.case_id===id)!;return <button type="button" key={id} className={active.case_id===id?'active':''} onClick={()=>chooseCase(id)} style={{'--tab-color':colors[id]} as React.CSSProperties}><b>{row.name}</b><span>{row.carrier}</span><strong>{row.anchor_value}</strong><small>{row.anchor_label}</small></button>})}</div></section>
  </div>;
}
