'use client';

import { useEffect, useMemo, useState } from 'react';
import { fetchClientText } from './lib/clientAsset';

type Row={route_id:string;route_order:string;display_period:string;network:string;endpoint_a:string;interface:string;endpoint_b:string;what_crossed:string;institution:string;evidence_class:string;evidence:string;quantitative_anchor:string;source_keys:string;limits:string};
const DATA_URL='/data/caliphates/20260901-trade1/caliphate-cross-border-trade.csv';
function parseCSV<T>(text:string):T[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const[headers,...body]=rows;return body.map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])) as T);}
export default function CaliphateTradeEdges(){const[rows,setRows]=useState<Row[]>([]);const[state,setState]=useState<'loading'|'ready'|'error'>('loading');const[error,setError]=useState('');const[attempt,setAttempt]=useState(0);const[selectedId,setSelectedId]=useState('baltic_dirhams');useEffect(()=>{const controller=new AbortController();fetchClientText(DATA_URL,{signal:controller.signal,label:'caliphal-era trade evidence'}).then(text=>{const parsed=parseCSV<Row>(text);if(parsed.length!==4||parsed.some(row=>!row.route_id||!row.network||!row.endpoint_a||!row.interface||!row.endpoint_b||!row.evidence||!row.source_keys))throw new Error('The trade evidence used an incompatible data contract.');setRows(parsed);setState('ready');}).catch(problem=>{if(controller.signal.aborted)return;setError(problem instanceof Error?problem.message:'The trade evidence could not be loaded.');setState('error');});return()=>controller.abort();},[attempt]);const selected=useMemo(()=>rows.find(row=>row.route_id===selectedId)??rows[0],[rows,selectedId]);if(state!=='ready'||!selected)return <div className={`data-state caliphate-trade-state ${state}`} role={state==='error'?'alert':'status'}><b>{state==='error'?'The cross-border trade evidence did not load':'Loading cross-border trade evidence…'}</b><span>{state==='error'?error:'Baltic · Persian Gulf · China seas · Malabar'}</span>{state==='error'&&<button type="button" onClick={()=>{setError('');setState('loading');setAttempt(value=>value+1);}}>Retry evidence</button>}</div>;return <div className="caliphate-trade-chart"><div className="caliphate-trade-lanes">{rows.map(row=><button type="button" key={row.route_id} className={selected.route_id===row.route_id?'active':''} aria-pressed={selected.route_id===row.route_id} onClick={()=>setSelectedId(row.route_id)}><header><span>{row.display_period}</span><b>{row.network}</b></header><div><strong>{row.endpoint_a}</strong><em>→</em><strong className="interface">{row.interface}</strong><em>→</em><strong>{row.endpoint_b}</strong></div><small>{row.what_crossed}</small></button>)}</div><section aria-live="polite"><header><div><span>{selected.evidence_class}</span><h5>{selected.network}</h5></div><strong>{selected.quantitative_anchor}</strong></header><div className="caliphate-trade-detail"><article><span>What made the link work</span><b>{selected.institution}</b><p>{selected.evidence}</p></article><article><span>What the evidence cannot show</span><p>{selected.limits}</p></article></div></section><p className="caliphate-trade-takeaway"><strong>No caliph controlled all four chains.</strong> Ports, merchant correspondence, caravan markets, ship technology, and widely accepted silver connected regions across political boundaries.</p></div>}
