'use client';

import { useEffect, useMemo, useState } from 'react';
import { fetchClientText } from './lib/clientAsset';

type TaxRow={window_id:string;window_order:string;display_period:string;window_title:string;evidence:string;inherited_layer:string;new_layer:string;quantitative_anchor:string;source_keys:string;limits:string};
const dataUrl='/data/caliphates/20260831-tax1/caliphal-fiscal-transition.csv';
function parseCSV<T>(text:string):T[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const[headers,...body]=rows;return body.map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])) as T);}
export default function CaliphateTaxTransition(){const[rows,setRows]=useState<TaxRow[]>([]);const[state,setState]=useState<'loading'|'ready'|'error'>('loading');const[error,setError]=useState('');const[attempt,setAttempt]=useState(0);const[selectedId,setSelectedId]=useState('egypt_bilingual_receipt');useEffect(()=>{const controller=new AbortController();fetchClientText(dataUrl,{signal:controller.signal,label:'caliphal fiscal transition'}).then(text=>{const parsed=parseCSV<TaxRow>(text);if(parsed.length!==4||parsed.some(row=>!row.window_id||!row.window_title||!row.evidence||!row.inherited_layer||!row.new_layer||!row.source_keys))throw new Error('The fiscal-transition evidence used an incompatible data contract.');setRows(parsed);setState('ready');}).catch(problem=>{if(controller.signal.aborted)return;setError(problem instanceof Error?problem.message:'The evidence could not be loaded.');setState('error');});return()=>controller.abort();},[attempt]);const selected=useMemo(()=>rows.find(row=>row.window_id===selectedId)??rows[0],[rows,selectedId]);const retry=()=>{setRows([]);setError('');setState('loading');setAttempt(value=>value+1);};if(state!=='ready'||!selected)return <div className={`data-state caliphate-tax-state ${state}`} role={state==='error'?'alert':'status'}><b>{state==='error'?'The fiscal-transition evidence did not load':'Loading fiscal-transition evidence…'}</b><span>{state==='error'?error:'documents · offices · mints · reforms'}</span>{state==='error'&&<button type="button" onClick={retry}>Retry evidence</button>}</div>;return <div className="caliphate-tax-chart"><nav aria-label="Choose a fiscal-transition window">{rows.map(row=><button type="button" key={row.window_id} className={selected.window_id===row.window_id?'active':''} aria-pressed={selected.window_id===row.window_id} onClick={()=>setSelectedId(row.window_id)}><span>{row.display_period}</span><b>{row.window_title}</b></button>)}</nav><section aria-live="polite"><header><div><span>{selected.display_period}</span><h5>{selected.window_title}</h5></div><strong>{selected.quantitative_anchor}</strong></header><div className="caliphate-tax-lanes"><article><span>Evidence</span><p>{selected.evidence}</p></article><article><span>What persisted</span><p>{selected.inherited_layer}</p></article><article><span>What changed</span><p>{selected.new_layer}</p></article></div></section></div>}
