'use client';

import { useEffect, useMemo, useState } from 'react';
import { fetchClientText } from './lib/clientAsset';

type CareRow={window_id:string;window_order:string;display_period:string;window_title:string;primary_evidence:string;recurring_practice:string;organizational_role:string;quantitative_anchor:string;source_keys:string;limits:string};
const dataUrl='/data/christianity/20260831-charity1/congregational-care-institutions.csv';
function parseCSV<T>(text:string):T[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const[headers,...body]=rows;return body.map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])) as T);}
export default function ChristianCareInstitutions(){const[rows,setRows]=useState<CareRow[]>([]);const[state,setState]=useState<'loading'|'ready'|'error'>('loading');const[error,setError]=useState('');const[attempt,setAttempt]=useState(0);const[selectedId,setSelectedId]=useState('corinth_collection');useEffect(()=>{const controller=new AbortController();fetchClientText(dataUrl,{signal:controller.signal,label:'Christian congregational care evidence'}).then(text=>{const parsed=parseCSV<CareRow>(text);if(parsed.length!==3||parsed.some(row=>!row.window_id||!row.window_title||!row.primary_evidence||!row.recurring_practice||!row.organizational_role||!row.source_keys))throw new Error('The congregational-care evidence used an incompatible data contract.');setRows(parsed);setState('ready');}).catch(problem=>{if(controller.signal.aborted)return;setError(problem instanceof Error?problem.message:'The evidence could not be loaded.');setState('error');});return()=>controller.abort();},[attempt]);const selected=useMemo(()=>rows.find(row=>row.window_id===selectedId)??rows[0],[rows,selectedId]);const retry=()=>{setRows([]);setError('');setState('loading');setAttempt(value=>value+1);};if(state!=='ready'||!selected)return <div className={`data-state christian-care-state ${state}`} role={state==='error'?'alert':'status'}><b>{state==='error'?'The congregational-care evidence did not load':'Loading congregational-care evidence…'}</b><span>{state==='error'?error:'contributions · registers · offices'}</span>{state==='error'&&<button type="button" onClick={retry}>Retry evidence</button>}</div>;return <div className="christian-care-chart"><nav aria-label="Choose an institutional-care window">{rows.map(row=><button type="button" key={row.window_id} className={selected.window_id===row.window_id?'active':''} aria-pressed={selected.window_id===row.window_id} onClick={()=>setSelectedId(row.window_id)}><span>{row.display_period}</span><b>{row.window_title}</b></button>)}</nav><section aria-live="polite"><header><div><span>{selected.display_period}</span><h5>{selected.window_title}</h5></div><strong>{selected.quantitative_anchor}</strong></header><div className="christian-care-lanes"><article><span>Evidence</span><p>{selected.primary_evidence}</p></article><article><span>Repeated practice</span><p>{selected.recurring_practice}</p></article><article><span>Organization</span><p>{selected.organizational_role}</p></article></div></section></div>}
