'use client';

import { useEffect, useMemo, useState } from 'react';
import { fetchClientText } from './lib/clientAsset';

type Row={constituency_id:string;sort_order:string;military_arm:string;resource_barrier:string;political_pattern:string;aristotle_evidence:string;visual_anchor:string;source_keys:string;limits:string};
const dataUrl='/data/greek-city-states/20260831-citizens1/military-political-constituencies.csv';
function parseCSV<T>(text:string):T[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const[headers,...body]=rows;return body.map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])) as T);}
export default function GreekMilitaryConstituencies(){const[rows,setRows]=useState<Row[]>([]);const[state,setState]=useState<'loading'|'ready'|'error'>('loading');const[error,setError]=useState('');const[attempt,setAttempt]=useState(0);const[selectedId,setSelectedId]=useState('cavalry');useEffect(()=>{const controller=new AbortController();fetchClientText(dataUrl,{signal:controller.signal,label:'Greek military constituencies'}).then(text=>{const parsed=parseCSV<Row>(text);if(parsed.length!==4||parsed.some(row=>!row.constituency_id||!row.military_arm||!row.political_pattern||!row.aristotle_evidence||!row.source_keys))throw new Error('The military-constituency evidence used an incompatible data contract.');setRows(parsed);setState('ready');}).catch(problem=>{if(controller.signal.aborted)return;setError(problem instanceof Error?problem.message:'The evidence could not be loaded.');setState('error');});return()=>controller.abort();},[attempt]);const selected=useMemo(()=>rows.find(row=>row.constituency_id===selectedId)??rows[0],[rows,selectedId]);const retry=()=>{setRows([]);setError('');setState('loading');setAttempt(value=>value+1);};if(state!=='ready'||!selected)return <div className={`data-state greek-citizens-state ${state}`} role={state==='error'?'alert':'status'}><b>{state==='error'?'The military evidence did not load':'Loading military constituencies…'}</b><span>{state==='error'?error:'cavalry · hoplites · light infantry · navy'}</span>{state==='error'&&<button type="button" onClick={retry}>Retry evidence</button>}</div>;return <div className="greek-citizens-chart"><nav aria-label="Choose a military constituency">{rows.map(row=><button type="button" key={row.constituency_id} className={selected.constituency_id===row.constituency_id?'active':''} aria-pressed={selected.constituency_id===row.constituency_id} onClick={()=>setSelectedId(row.constituency_id)}><span>{row.military_arm}</span><b>{row.political_pattern}</b></button>)}</nav><section aria-live="polite"><header><div><span>{selected.military_arm}</span><h5>{selected.political_pattern}</h5></div><strong>{selected.visual_anchor}</strong></header><div className="greek-citizens-lanes"><article><span>Resource barrier</span><p>{selected.resource_barrier}</p></article><article><span>Ancient argument</span><p>{selected.aristotle_evidence}</p></article><article><span>Evidence limit</span><p>{selected.limits}</p></article></div></section></div>}
