'use client';

import { useEffect, useMemo, useState } from 'react';
import { fetchClientText } from './lib/clientAsset';

type RelationshipRow={relation_id:string;relation_order:string;display_region:string;relation_title:string;political_relationship:string;administrative_instrument:string;inscriptional_evidence:string;named_places:string;quantitative_anchor:string;source_keys:string;limits:string};
const dataUrl='/data/india/20260831-maurya1/mauryan-regional-relationships.csv';

function parseCSV<T>(text:string):T[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const[headers,...body]=rows;return body.map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])) as T);}

export default function IndiaMauryanRelationships(){
  const[rows,setRows]=useState<RelationshipRow[]>([]);const[state,setState]=useState<'loading'|'ready'|'error'>('loading');const[error,setError]=useState('');const[attempt,setAttempt]=useState(0);const[selectedId,setSelectedId]=useState('court_core');
  useEffect(()=>{const controller=new AbortController();fetchClientText(dataUrl,{signal:controller.signal,label:'Mauryan regional relationships'}).then(text=>{const parsed=parseCSV<RelationshipRow>(text);if(parsed.length!==4||parsed.some(row=>!row.relation_id||!row.relation_title||!row.political_relationship||!row.administrative_instrument||!row.source_keys))throw new Error('The Mauryan evidence used an incompatible data contract.');setRows(parsed);setState('ready');}).catch(problem=>{if(controller.signal.aborted)return;setError(problem instanceof Error?problem.message:'The evidence could not be loaded.');setState('error');});return()=>controller.abort();},[attempt]);
  const selected=useMemo(()=>rows.find(row=>row.relation_id===selectedId)??rows[0],[rows,selectedId]);const retry=()=>{setRows([]);setError('');setState('loading');setAttempt(value=>value+1);};
  if(state!=='ready'||!selected)return <div className={`data-state india-maurya-state ${state}`} role={state==='error'?'alert':'status'}><b>{state==='error'?'The Mauryan evidence did not load':'Loading Mauryan relationships…'}</b><span>{state==='error'?error:'court · regional centers · Kalinga · neighbors'}</span>{state==='error'&&<button type="button" onClick={retry}>Retry evidence</button>}</div>;
  return <div className="india-maurya-chart"><nav aria-label="Choose a Mauryan regional relationship">{rows.map(row=><button type="button" key={row.relation_id} className={selected.relation_id===row.relation_id?'active':''} aria-pressed={selected.relation_id===row.relation_id} onClick={()=>setSelectedId(row.relation_id)}><span>{row.display_region}</span><b>{row.relation_title}</b></button>)}</nav><section aria-live="polite"><header><div><span>{selected.display_region}</span><h5>{selected.relation_title}</h5></div><strong>{selected.quantitative_anchor}</strong></header><div className="india-maurya-lanes"><article><span>Relationship</span><p>{selected.political_relationship}</p></article><article><span>Instrument</span><p>{selected.administrative_instrument}</p></article><article><span>Inscriptional window</span><p>{selected.inscriptional_evidence}</p></article></div><footer><span>Named places and peoples</span><p>{selected.named_places}</p></footer></section></div>;
}
