'use client';

import { useEffect, useMemo, useState } from 'react';
import { fetchClientText } from './lib/clientAsset';

type IronCase={case_id:string;place:string;region:string;first_start:string;first_end:string;adoption_start:string;adoption_end:string;first_window:string;adoption_window:string;evidence_kind:string;prior_metal:string;resource_and_fuel:string;production_system:string;skill_and_product:string;institutional_context:string;interpretation:string;source_keys:string;limits:string};
type Lens='prior_metal'|'resource_and_fuel'|'production_system'|'skill_and_product'|'institutional_context';

const REVISION='20260830-adoption1';
const dataUrl=`/data/iron-age/${REVISION}/iron-adoption-windows.csv`;
const order=['anatolia-near-east','cyprus','aegean','central-europe','north-china'];
const colors:Record<string,string>={'anatolia-near-east':'#9c4b3e',cyprus:'#a77835',aegean:'#536f8b','central-europe':'#6c6384','north-china':'#58764f'};
const lenses:Array<{key:Lens;label:string;short:string}>=[{key:'prior_metal',label:'Bronze did not vanish',short:'existing craft'},{key:'resource_and_fuel',label:'Ore + charcoal',short:'materials and heat'},{key:'production_system',label:'Furnace pathway',short:'bloomery or casting'},{key:'skill_and_product',label:'Smithing + quality',short:'variable products'},{key:'institutional_context',label:'Scale + demand',short:'exchange and organization'}];

function parseCSV<T>(text:string):T[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const[headers,...body]=rows;return body.map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])) as T);}
function position(value:number){return `${((value+2100)/1800)*100}%`;}
function year(value:number){return `${Math.abs(value)} BCE`;}
function label(value:string){return value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());}

export default function IronAdoptionClocks(){
  const[rows,setRows]=useState<IronCase[]>([]);const[state,setState]=useState<'loading'|'ready'|'error'>('loading');const[error,setError]=useState('');const[selected,setSelected]=useState('anatolia-near-east');const[lens,setLens]=useState<Lens>('production_system');const[attempt,setAttempt]=useState(0);
  useEffect(()=>{const controller=new AbortController();fetchClientText(dataUrl,{signal:controller.signal,label:'Iron-adoption chronology'}).then(text=>{const parsed=parseCSV<IronCase>(text);if(parsed.length!==5||new Set(parsed.map(row=>row.case_id)).size!==5||parsed.some(row=>!row.limits||!row.source_keys||lenses.some(item=>!row[item.key])||['first_start','first_end','adoption_start','adoption_end'].some(field=>!Number.isFinite(Number(row[field as keyof IronCase])))))throw new Error('The iron-adoption response used an incompatible schema.');setRows(parsed);setState('ready');}).catch(problem=>{if(controller.signal.aborted)return;setError(problem instanceof Error?problem.message:'The iron chronology could not be loaded.');setState('error');});return()=>controller.abort();},[attempt]);
  const active=useMemo(()=>rows.find(row=>row.case_id===selected)??rows[0],[rows,selected]);
  const retry=()=>{setRows([]);setError('');setState('loading');setAttempt(value=>value+1);};
  if(state!=='ready'||!active)return <div className={`data-state iron-adoption-data-state ${state}`} role={state==='error'?'alert':'status'}><b>{state==='error'?'The iron-adoption chronology did not load':'Loading five regional adoption windows…'}</b><span>{state==='error'?error:'first evidence · sustained use · production dependencies'}</span>{state==='error'&&<button type="button" onClick={retry}>Retry chronology</button>}</div>;

  return <div className="iron-adoption-chart" style={{'--iron-color':colors[active.case_id]} as React.CSSProperties}>
    <div className="iron-adoption-summary"><div><span>Regional windows</span><b>5</b><small>different clocks and pathways</small></div><div><span>Instant transitions</span><b>0</b><small>first evidence ≠ common use</small></div><div><span>Production chain</span><b>5 links</b><small>ore to institutions</small></div></div>
    <nav className="iron-adoption-tabs" aria-label="Choose a regional iron-adoption window">{order.map(id=>{const row=rows.find(item=>item.case_id===id)!;return <button type="button" key={id} className={selected===id?'active':''} aria-pressed={selected===id} onClick={()=>setSelected(id)} style={{'--tab-color':colors[id]} as React.CSSProperties}><i/><span><b>{row.place}</b><small>{row.adoption_window}</small></span></button>})}</nav>
    <section className="iron-adoption-timeline"><header><div><span>Two clocks · same metal</span><h5>First attestation is not an Iron Age</h5></div><small>Thin: first evidence · thick: wider adoption</small></header><div className="iron-adoption-axis"><div className="iron-adoption-ticks">{[-2000,-1600,-1200,-800,-400].map(tick=><span key={tick} style={{left:position(tick)}}>{year(tick)}</span>)}</div>{order.map(id=>{const row=rows.find(item=>item.case_id===id)!;return <button type="button" key={id} className={selected===id?'active':''} onClick={()=>setSelected(id)}><b>{row.place}</b><span className="iron-track"><i className="first" style={{left:position(Number(row.first_start)),width:`calc(${position(Number(row.first_end))} - ${position(Number(row.first_start))} + 3px)`,background:colors[id]}}/><i className="adoption" style={{left:position(Number(row.adoption_start)),width:`calc(${position(Number(row.adoption_end))} - ${position(Number(row.adoption_start))} + 3px)`,background:colors[id]}}/></span><small>{row.first_window}<br/>{row.adoption_window}</small></button>})}</div></section>
    <section className="iron-adoption-focus"><header><div><span>{active.region} · {label(active.evidence_kind)}</span><h5>{active.place}</h5></div><div><b>{active.first_window}</b><small>first clock</small><strong>{active.adoption_window}</strong><small>wider-adoption clock</small></div></header><p className="iron-adoption-reading">{active.interpretation}</p><nav className="iron-adoption-lenses" aria-label="Choose a production dependency">{lenses.map(item=><button type="button" key={item.key} className={lens===item.key?'active':''} aria-pressed={lens===item.key} onClick={()=>setLens(item.key)}><span>{item.label}</span><small>{item.short}</small></button>)}</nav><div className="iron-adoption-evidence"><span>{lenses.find(item=>item.key===lens)!.label}</span><p>{active[lens]}</p></div><div className="iron-adoption-limit"><div><span>What this does not prove</span><p>{active.limits}</p></div><div><span>Source keys</span><b>{active.source_keys}</b></div></div></section>
    <div className="cradle-downloads iron-adoption-downloads"><p><b>Iron was a production system.</b> The ranges do not measure annual output, market share, diffusion speed, hardness, or military power.</p><a href={dataUrl} download>Download evidence CSV ↓</a></div>
  </div>;
}
