'use client';

import { useEffect, useMemo, useState } from 'react';
import { fetchClientText } from './lib/clientAsset';

type MobilizationCase={case_id:string;sort_order:string;polity:string;start_year:string;end_year:string;date_label:string;metal_context:string;scale_value:string;scale_label:string;scale_scope:string;evidence_status:string;recruitment_system:string;equipment_system:string;supply_system:string;replacement_system:string;source_keys:string;interpretation:string;limits:string};
const REVISION='20260830-mobilization1';
const dataUrl=`/data/iron-age/${REVISION}/iron-mobilization-cases.csv`;
const colors:Record<string,string>={egypt_kadesh:'#9a6a32',pre_roman_civitates:'#677f55',carthage_215:'#806695',rome_212:'#bd1f2e'};

function parseCSV<T>(text:string):T[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const[headers,...body]=rows;return body.map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])) as T);}

export default function IronMobilizationLedger(){
  const[rows,setRows]=useState<MobilizationCase[]>([]);const[state,setState]=useState<'loading'|'ready'|'error'>('loading');const[error,setError]=useState('');const[selected,setSelected]=useState('rome_212');const[attempt,setAttempt]=useState(0);
  useEffect(()=>{const controller=new AbortController();fetchClientText(dataUrl,{signal:controller.signal,label:'Iron-age mobilization cases'}).then(text=>{const parsed=parseCSV<MobilizationCase>(text).sort((a,b)=>Number(a.sort_order)-Number(b.sort_order));if(parsed.length!==4||new Set(parsed.map(row=>row.case_id)).size!==4||parsed.some(row=>!row.source_keys||!row.limits||!row.equipment_system||!row.recruitment_system))throw new Error('The mobilization response used an incompatible schema.');const numeric=parsed.filter(row=>row.scale_value);if(numeric.length!==3||numeric.some(row=>!Number.isFinite(Number(row.scale_value))))throw new Error('The mobilization response contained invalid scale fields.');setRows(parsed);setState('ready');}).catch(problem=>{if(controller.signal.aborted)return;setError(problem instanceof Error?problem.message:'The mobilization comparison could not be loaded.');setState('error');});return()=>controller.abort();},[attempt]);
  const active=rows.find(row=>row.case_id===selected)??rows[0];
  const punic=useMemo(()=>rows.filter(row=>['carthage_215','rome_212'].includes(row.case_id)),[rows]);
  const retry=()=>{setRows([]);setError('');setState('loading');setAttempt(value=>value+1);};
  if(state!=='ready'||!active)return <div className={`data-state iron-mobilization-data-state ${state}`} role={state==='error'?'alert':'status'}><b>{state==='error'?'The mobilization ledger did not load':'Loading four mobilization cases…'}</b><span>{state==='error'?error:'equipment · recruitment · supply · replacement'}</span>{state==='error'&&<button type="button" onClick={retry}>Retry ledger</button>}</div>;
  return <div className="iron-mobilization-chart" style={{'--mobilization-color':colors[active.case_id]} as React.CSSProperties}>
    <nav className="iron-mobilization-tabs" aria-label="Choose a mobilization case">{rows.map(row=><button type="button" key={row.case_id} className={selected===row.case_id?'active':''} onClick={()=>setSelected(row.case_id)} style={{'--case-color':colors[row.case_id]} as React.CSSProperties}><span>{row.date_label}</span><b>{row.polity}</b><small>{row.scale_label}</small></button>)}</nav>
    <section className="iron-mobilization-focus"><header><div><span>{active.date_label}</span><h5>{active.polity}</h5></div><div><b>{active.scale_label}</b><small>{active.scale_scope}</small></div></header><p className="iron-mobilization-interpretation">{active.interpretation}</p><div className="iron-mobilization-ledger"><article><span>01 · Equipment</span><p>{active.equipment_system}</p></article><i>+</i><article><span>02 · Recruitment</span><p>{active.recruitment_system}</p></article><i>+</i><article><span>03 · Supply</span><p>{active.supply_system}</p></article><i>+</i><article><span>04 · Replacement</span><p>{active.replacement_system}</p></article></div><div className="iron-mobilization-context"><div><span>Metal context</span><p>{active.metal_context}</p></div></div></section>
    <section className="iron-mobilization-compare"><header><div><span>Only like-with-like values receive bars</span><h5>Two republics reached similar peaks differently</h5></div><small>Taylor strategic-deployment models · Second Punic War</small></header><div className="iron-mobilization-bars">{punic.map(row=><button type="button" key={row.case_id} className={selected===row.case_id?'active':''} onClick={()=>setSelected(row.case_id)}><span><b>{row.polity.replace(' and the Italian allies','')}</b><small>{row.date_label}</small></span><i style={{width:`${Number(row.scale_value)/185000*100}%`,background:colors[row.case_id]}}/><strong>{row.scale_label}</strong></button>)}</div><p>Carthage&apos;s approximately 170,000 and Rome&apos;s approximately 185,000 are close enough to reject a simple “iron made Rome uniquely massive” story. Their recruitment and supply architectures—not a fifteen-thousand-man precision margin—are the comparison.</p></section>
    <section className="iron-mobilization-limit"><div><p>{active.limits}</p></div></section>
  </div>;
}
