'use client';

import { useEffect, useMemo, useState } from 'react';
import { fetchClientText } from './lib/clientAsset';

type Sample={run:string;stage:'bloom'|'bar';phosphorus_wt_percent:string;sulfur_wt_percent:string;hardness_hv:string;hardness_sd:string;hardness_n:string;microstructure:string;forgeability:string;source_keys:string;limits:string};
type Lens='hardness'|'chemistry'|'structure';
const REVISION='20260830-quality1';
const dataUrl=`/data/iron-age/${REVISION}/iron-quality-experiments.csv`;
const order=['FEXP-1','FEXP-100','FEXP-5','FEXP-6'];
const colors:Record<string,string>={'FEXP-1':'#536f8b','FEXP-100':'#9c4b3e','FEXP-5':'#6f7f52','FEXP-6':'#8b6531'};

function parseCSV<T>(text:string):T[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const[headers,...body]=rows;return body.map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])) as T);}
const pct=(value:string)=>Math.min(100,Number(value)/1.2*100);

export default function IronQualityLab(){
  const[rows,setRows]=useState<Sample[]>([]);const[state,setState]=useState<'loading'|'ready'|'error'>('loading');const[error,setError]=useState('');const[selected,setSelected]=useState('FEXP-6');const[lens,setLens]=useState<Lens>('hardness');const[attempt,setAttempt]=useState(0);
  useEffect(()=>{const controller=new AbortController();fetchClientText(dataUrl,{signal:controller.signal,label:'Iron-quality experiment table'}).then(text=>{const parsed=parseCSV<Sample>(text);if(parsed.length!==8||new Set(parsed.map(row=>`${row.run}:${row.stage}`)).size!==8||parsed.some(row=>!row.limits||!row.source_keys||!Number.isFinite(Number(row.hardness_hv))))throw new Error('The iron-quality response used an incompatible schema.');setRows(parsed);setState('ready');}).catch(problem=>{if(controller.signal.aborted)return;setError(problem instanceof Error?problem.message:'The iron-quality comparison could not be loaded.');setState('error');});return()=>controller.abort();},[attempt]);
  const pairs=useMemo(()=>order.map(run=>({run,bloom:rows.find(row=>row.run===run&&row.stage==='bloom')!,bar:rows.find(row=>row.run===run&&row.stage==='bar')!})).filter(pair=>pair.bloom&&pair.bar),[rows]);
  const active=pairs.find(pair=>pair.run===selected)??pairs[0];
  const retry=()=>{setRows([]);setError('');setState('loading');setAttempt(value=>value+1);};
  if(state!=='ready'||!active)return <div className={`data-state iron-quality-data-state ${state}`} role={state==='error'?'alert':'status'}><b>{state==='error'?'The paired metal samples did not load':'Loading four bloom-to-bar comparisons…'}</b><span>{state==='error'?error:'hardness · chemistry · microstructure · forgeability'}</span>{state==='error'&&<button type="button" onClick={retry}>Retry samples</button>}</div>;
  const delta=Number(active.bar.hardness_hv)-Number(active.bloom.hardness_hv);
  return <div className="iron-quality-chart" style={{'--quality-color':colors[active.run]} as React.CSSProperties}>
    <nav className="iron-quality-tabs" aria-label="Choose a smelting experiment">{pairs.map(pair=><button type="button" key={pair.run} className={selected===pair.run?'active':''} onClick={()=>setSelected(pair.run)} style={{'--tab-color':colors[pair.run]} as React.CSSProperties}><i/><span><b>{pair.run}</b><small>{pair.bloom.forgeability}</small></span></button>)}</nav>
    <section className="iron-quality-overview"><header><div><span>Paired mean Vickers hardness</span><h5>Harder was not always easier to use</h5></div><small>Means shown without an uncertainty band · sample n stays visible below</small></header><div className="iron-quality-axis"><span>0</span><span>50</span><span>100</span><span>150 HV</span></div><div className="iron-quality-pairs">{pairs.map(pair=><button type="button" key={pair.run} className={selected===pair.run?'active':''} onClick={()=>setSelected(pair.run)}><b>{pair.run}</b><span className="quality-bars"><i className="bloom" style={{width:`${Number(pair.bloom.hardness_hv)/1.5}%`,background:colors[pair.run]}}/><i className="bar" style={{width:`${Number(pair.bar.hardness_hv)/1.5}%`,borderColor:colors[pair.run]}}/></span><small><strong>{pair.bloom.hardness_hv}</strong> bloom<br/><strong>{pair.bar.hardness_hv}</strong> bar</small><em className={pair.bloom.forgeability.startsWith('better')?'workable':'brittle'}>{pair.bloom.forgeability}</em></button>)}</div><div className="iron-quality-legend"><span><i/>bloom mean</span><span><i className="outline"/>bar mean</span><span>HV = Vickers hardness · not toughness</span></div></section>
    <section className="iron-quality-focus"><header><div><span>{active.run} · one bloom and a bar forged from a quarter</span><h5>{delta>=0?'Hardness rose after working':'The hardest bloom became a softer bar'}</h5></div><div><b>{active.bloom.hardness_hv} → {active.bar.hardness_hv} HV</b><small>{delta>=0?'+':''}{delta} HV · means from n={active.bloom.hardness_n} and n={active.bar.hardness_n}</small></div></header><nav className="iron-quality-lenses" aria-label="Choose an evidence lens"><button type="button" className={lens==='hardness'?'active':''} onClick={()=>setLens('hardness')}>Hardness + sampling</button><button type="button" className={lens==='chemistry'?'active':''} onClick={()=>setLens('chemistry')}>Sulfur + phosphorus</button><button type="button" className={lens==='structure'?'active':''} onClick={()=>setLens('structure')}>Microstructure + forging</button></nav>{lens==='hardness'?<div className="iron-quality-reading hardness"><article><span>Bloom</span><b>{active.bloom.hardness_hv} HV</b><small>SD {active.bloom.hardness_sd} · n={active.bloom.hardness_n}</small></article><article><span>Forged bar</span><b>{active.bar.hardness_hv} HV</b><small>SD {active.bar.hardness_sd} · n={active.bar.hardness_n}</small></article><p>These are indentation means on selected metallographic samples—not whole-object tests of toughness, edge retention, or battlefield performance.</p></div>:lens==='chemistry'?<div className="iron-quality-reading chemistry"><article><span>Sulfur · bloom → bar</span><b>{active.bloom.sulfur_wt_percent} → {active.bar.sulfur_wt_percent}%</b><i><em style={{width:`${pct(active.bloom.sulfur_wt_percent)}%`}}/><em style={{width:`${pct(active.bar.sulfur_wt_percent)}%`}}/></i></article><article><span>Phosphorus · bloom → bar</span><b>{active.bloom.phosphorus_wt_percent} → {active.bar.phosphorus_wt_percent}%</b><small>SEM–EDS averages; “&lt;” values remain detection bounds.</small></article><p>Impurities could raise hardness while worsening hot forgeability. Chemistry and use-quality therefore do not collapse into one direction.</p></div>:<div className="iron-quality-reading structure"><article><span>Bloom microstructure</span><p>{active.bloom.microstructure}</p></article><article><span>Bar microstructure</span><p>{active.bar.microstructure}</p></article><strong>{active.bar.forgeability}</strong></div>}</section>
  </div>;
}
