'use client';

import { useEffect, useMemo, useState } from 'react';
import { fetchClientText } from './lib/clientAsset';

type Run={series:string;run:string;context:string;furnace_model:string;ore_kg:string;charcoal_kg:string;bloom_kg:string;bloom_status:string;air_and_operation:string;reported_observation:string;source_keys:string;limits:string};
type Metric='inputs'|'fuel';

const REVISION='20260830-fuel1';
const dataUrl=`/data/iron-age/${REVISION}/iron-smelting-experiments.csv`;
const colors:Record<string,string>={'Meroe reconstruction':'#9c4b3e','Sehnde reconstruction':'#536f8b'};

function parseCSV<T>(text:string):T[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const[headers,...body]=rows;return body.map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])) as T);}
const number=(value:string)=>Number(value);
const ratio=(run:Run)=>number(run.bloom_kg)>0?number(run.charcoal_kg)/number(run.bloom_kg):null;
const ratioWidth=(value:number)=>`${Math.max(2,Math.min(100,(Math.log10(value)/3)*100))}%`;

export default function IronFuelExperiments(){
  const[rows,setRows]=useState<Run[]>([]);const[state,setState]=useState<'loading'|'ready'|'error'>('loading');const[error,setError]=useState('');const[selected,setSelected]=useState('MS1');const[series,setSeries]=useState('All');const[metric,setMetric]=useState<Metric>('inputs');const[attempt,setAttempt]=useState(0);
  useEffect(()=>{const controller=new AbortController();fetchClientText(dataUrl,{signal:controller.signal,label:'Experimental-smelting evidence'}).then(text=>{const parsed=parseCSV<Run>(text);if(parsed.length!==11||new Set(parsed.map(row=>row.run)).size!==11||parsed.some(row=>!row.limits||!row.source_keys||['ore_kg','charcoal_kg','bloom_kg'].some(field=>!Number.isFinite(Number(row[field as keyof Run])))))throw new Error('The experimental-smelting response used an incompatible schema.');setRows(parsed);setState('ready');}).catch(problem=>{if(controller.signal.aborted)return;setError(problem instanceof Error?problem.message:'The smelting comparison could not be loaded.');setState('error');});return()=>controller.abort();},[attempt]);
  const visible=useMemo(()=>series==='All'?rows:rows.filter(row=>row.series===series),[rows,series]);
  const active=useMemo(()=>rows.find(row=>row.run===selected)??visible[0]??rows[0],[rows,visible,selected]);
  const chooseSeries=(value:string)=>{setSeries(value);const next=value==='All'?rows[0]:rows.find(row=>row.series===value);if(next)setSelected(next.run);};
  const retry=()=>{setRows([]);setError('');setState('loading');setAttempt(value=>value+1);};
  if(state!=='ready'||!active)return <div className={`data-state iron-fuel-data-state ${state}`} role={state==='error'?'alert':'status'}><b>{state==='error'?'The experimental smelts did not load':'Loading eleven published smelting runs…'}</b><span>{state==='error'?error:'ore · charcoal · recovered bloom · run-specific limits'}</span>{state==='error'&&<button type="button" onClick={retry}>Retry experiments</button>}</div>;
  const activeRatio=ratio(active);
  return <div className="iron-fuel-chart" style={{'--fuel-color':colors[active.series]} as React.CSSProperties}>
    <div className="iron-fuel-controls"><div>{['All','Meroe reconstruction','Sehnde reconstruction'].map(value=><button type="button" key={value} className={series===value?'active':''} onClick={()=>chooseSeries(value)}>{value.replace(' reconstruction','')}</button>)}</div><div><button type="button" className={metric==='inputs'?'active':''} onClick={()=>setMetric('inputs')}>Inputs + bloom</button><button type="button" className={metric==='fuel'?'active':''} onClick={()=>setMetric('fuel')}>Fuel per bloom</button></div></div>
    <section className="iron-fuel-plot"><header><div><span>{metric==='inputs'?'Reported kilograms':'Derived ratio · logarithmic scale'}</span><h5>{metric==='inputs'?'The same inputs did not buy the same outcome':'Charcoal per kilogram of reported bloom'}</h5></div><small>{metric==='inputs'?'charcoal · ore · bloom':'1 · 10 · 100 · 1,000 kg charcoal / kg bloom'}</small></header><div className={`iron-fuel-runs ${metric}`}>{visible.map(run=>{const r=ratio(run);return <button type="button" key={run.run} className={active.run===run.run?'active':''} style={{'--run-color':colors[run.series]} as React.CSSProperties} onClick={()=>setSelected(run.run)}><span><b>{run.run}</b><small>{run.context}</small></span>{metric==='inputs'?<span className="iron-input-bars"><i className="charcoal" style={{width:`${number(run.charcoal_kg)/1.1}%`}}/><i className="ore" style={{width:`${number(run.ore_kg)/1.1}%`}}/><i className="bloom" style={{width:`${Math.max(1.5,number(run.bloom_kg)/1.1)}%`}}/></span>:<span className="iron-ratio-track">{r===null?<i className="failed"/>:<i style={{width:ratioWidth(r)}}/>}</span>}<strong>{metric==='inputs'?`${run.charcoal_kg} / ${run.ore_kg} / ${run.bloom_kg} kg`:r===null?'no recognizable bloom':number(run.bloom_kg)<.1?'trace bloom':`${r.toFixed(1)} : 1`}</strong></button>})}</div><div className="iron-fuel-legend">{metric==='inputs'?<><span><i className="charcoal"/>charcoal</span><span><i className="ore"/>ore</span><span><i className="bloom"/>reported bloom</span></>:<><span>Bar length uses a logarithmic scale.</span><span>Zero-bloom runs are categorical, not infinity.</span></>}</div></section>
    <section className="iron-fuel-focus"><header><div><span>{active.series} · {active.context}</span><h5>{active.run}: {active.bloom_status}</h5></div><div><b>{active.charcoal_kg} kg</b><small>charcoal</small><b>{active.ore_kg} kg</b><small>ore</small><strong>{active.bloom_kg} kg</strong><small>reported bloom</small></div></header><div className="iron-fuel-reading"><div><span>Operation</span><p>{active.air_and_operation}</p></div><div><span>Reported observation</span><p>{active.reported_observation}</p></div><div><span>Fuel / bloom</span><b>{activeRatio===null?'not defined':number(active.bloom_kg)<.1?'trace output':`${activeRatio.toFixed(1)} kg/kg`}</b><small>{activeRatio===null?'No recognizable bloom; metallic material may still have formed.':'Arithmetic from this run only.'}</small></div></div></section>
  </div>;
}
