'use client';

import { useEffect, useState } from 'react';
import { fetchClientText } from './lib/clientAsset';

type District={district_id:string;sort_order:string;district_label:string;peoples:string;material:string;reported_amount:string;reported_unit:string;additional_obligation:string;source_keys:string;interpretation:string;limits:string};
type Portfolio={case_id:string;sort_order:string;title:string;date_label:string;evidence_class:string;reported_obligation:string;political_logic:string;interpretation:string;limits:string;source_keys:string};
const REVISION='20260830-tribute1';
const districtUrl=`/data/persia/${REVISION}/persian-tribute-districts.csv`;
const portfolioUrl=`/data/persia/${REVISION}/persian-obligation-portfolios.csv`;

function parseCSV<T>(text:string):T[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const[headers,...body]=rows;return body.map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])) as T);}
const label=(value:string)=>value.replaceAll('_',' ');

export default function PersianTributeSystem(){
  const[districts,setDistricts]=useState<District[]>([]);const[portfolios,setPortfolios]=useState<Portfolio[]>([]);const[state,setState]=useState<'loading'|'ready'|'error'>('loading');const[error,setError]=useState('');const[mode,setMode]=useState<'portfolios'|'districts'>('portfolios');const[selectedDistrict,setSelectedDistrict]=useState('district_04');const[selectedPortfolio,setSelectedPortfolio]=useState('cilicia_mixed');const[attempt,setAttempt]=useState(0);
  useEffect(()=>{const controller=new AbortController();Promise.all([fetchClientText(districtUrl,{signal:controller.signal,label:'Herodotus tribute districts'}),fetchClientText(portfolioUrl,{signal:controller.signal,label:'Persian obligation portfolios'})]).then(([districtText,portfolioText])=>{const nextDistricts=parseCSV<District>(districtText).sort((a,b)=>Number(a.sort_order)-Number(b.sort_order));const nextPortfolios=parseCSV<Portfolio>(portfolioText).sort((a,b)=>Number(a.sort_order)-Number(b.sort_order));if(nextDistricts.length!==20||nextPortfolios.length!==7||new Set(nextDistricts.map(row=>row.district_id)).size!==20||new Set(nextPortfolios.map(row=>row.case_id)).size!==7)throw new Error('The tribute response used an incompatible evidence contract.');setDistricts(nextDistricts);setPortfolios(nextPortfolios);setState('ready');}).catch(problem=>{if(controller.signal.aborted)return;setError(problem instanceof Error?problem.message:'The tribute comparison could not be loaded.');setState('error');});return()=>controller.abort();},[attempt]);
  const district=districts.find(row=>row.district_id===selectedDistrict)??districts[0];const portfolio=portfolios.find(row=>row.case_id===selectedPortfolio)??portfolios[0];const maxSilver=Math.max(...districts.filter(row=>row.material==='silver').map(row=>Number(row.reported_amount)),1);const retry=()=>{setState('loading');setError('');setAttempt(value=>value+1);};
  if(state!=='ready'||!district||!portfolio)return <div className={`data-state persia-tribute-data-state ${state}`} role={state==='error'?'alert':'status'}><b>{state==='error'?'The tribute evidence did not load':'Loading twenty districts and seven obligation windows…'}</b><span>{state==='error'?error:'silver · horses · grain · gold dust · gifts · documentary taxes'}</span>{state==='error'&&<button type="button" onClick={retry}>Retry tribute evidence</button>}</div>;
  return <div className="persia-tribute-chart">
    <div className="persia-tribute-mode" role="group" aria-label="Choose a tribute evidence view"><button type="button" className={mode==='portfolios'?'active':''} onClick={()=>setMode('portfolios')}>How obligation worked</button><button type="button" className={mode==='districts'?'active':''} onClick={()=>setMode('districts')}>Herodotus&apos;s 20 districts</button></div>
    {mode==='portfolios'?<><nav className="persia-obligation-tabs" aria-label="Choose an obligation window">{portfolios.map(row=><button type="button" key={row.case_id} className={selectedPortfolio===row.case_id?'active':''} onClick={()=>setSelectedPortfolio(row.case_id)}><span>{row.date_label}</span><b>{row.title}</b></button>)}</nav><section className="persia-obligation-focus"><header><div><span>{label(portfolio.evidence_class)}</span><h5>{portfolio.title}</h5></div><small>{portfolio.date_label}</small></header><strong>{portfolio.reported_obligation}</strong><div><article><span>Political logic</span><p>{portfolio.political_logic}</p></article><article><span>What the evidence supports</span><p>{portfolio.interpretation}</p></article></div></section><section className="persia-tribute-limit"><div><span>What this window does not prove</span><p>{portfolio.limits}</p></div><div><span>Source keys</span><b>{portfolio.source_keys}</b></div></section></>:<><section className="persia-districts"><header><div><span>One internal Herodotean scale</span><h5>Nineteen silver assessments</h5></div><small>India stays separate as gold dust</small></header><div>{districts.map(row=><button type="button" key={row.district_id} className={selectedDistrict===row.district_id?'active':''} onClick={()=>setSelectedDistrict(row.district_id)}><span>{String(row.sort_order).padStart(2,'0')}</span><b>{row.district_label}</b>{row.material==='silver'?<i style={{width:`${Number(row.reported_amount)/maxSilver*100}%`}}/>:<em>gold dust · separate unit</em>}<small>{row.reported_amount} {row.reported_unit}</small></button>)}</div></section><section className="persia-district-focus"><header><div><span>District {district.sort_order} · {district.material.replace('_',' ')}</span><h5>{district.district_label}</h5></div><b>{district.reported_amount} {district.reported_unit}</b></header><p>{district.peoples}</p>{district.additional_obligation&&<strong>{district.additional_obligation}</strong>}<div><article><span>Interpretation</span><p>{district.interpretation}</p></article><article><span>Limit</span><p>{district.limits}</p></article></div><small>Sources: {district.source_keys}</small></section></>}
  </div>;
}
