'use client';

import { useEffect, useState } from 'react';
import { fetchClientText } from './lib/clientAsset';

type Segment={segment_id:string;sort_order:string;region:string;start_label:string;end_label:string;stages:string;parasangs:string;terrain_and_control:string;source_keys:string;limits:string};
type Evidence={evidence_id:string;sort_order:string;evidence_class:string;date_label:string;title:string;anchor_value:string;anchor_unit:string;observation:string;source_keys:string;interpretation:string;limits:string};
const REVISION='20260830-roads1';
const segmentUrl=`/data/persia/${REVISION}/persian-royal-road-segments.csv`;
const evidenceUrl=`/data/persia/${REVISION}/persian-road-evidence.csv`;
const colors=['#bd1f2e','#9b733b','#567b6d','#39728b','#806695','#6f5c4d'];

function parseCSV<T>(text:string):T[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const[headers,...body]=rows;return body.map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])) as T);}
const label=(value:string)=>value.replaceAll('_',' ');

export default function PersianRoadRelay(){
  const[segments,setSegments]=useState<Segment[]>([]);const[evidence,setEvidence]=useState<Evidence[]>([]);const[state,setState]=useState<'loading'|'ready'|'error'>('loading');const[error,setError]=useState('');const[selectedSegment,setSelectedSegment]=useState('lydia_phrygia');const[selectedEvidence,setSelectedEvidence]=useState('courier_relay');const[attempt,setAttempt]=useState(0);
  useEffect(()=>{const controller=new AbortController();Promise.all([fetchClientText(segmentUrl,{signal:controller.signal,label:'Royal Road itinerary'}),fetchClientText(evidenceUrl,{signal:controller.signal,label:'Road-and-relay evidence'})]).then(([segmentText,evidenceText])=>{const nextSegments=parseCSV<Segment>(segmentText).sort((a,b)=>Number(a.sort_order)-Number(b.sort_order));const nextEvidence=parseCSV<Evidence>(evidenceText).sort((a,b)=>Number(a.sort_order)-Number(b.sort_order));const stages=nextSegments.reduce((sum,row)=>sum+Number(row.stages),0);const parasangs=nextSegments.reduce((sum,row)=>sum+Number(row.parasangs),0);if(nextSegments.length!==6||nextEvidence.length!==4||stages!==111||parasangs!==450||nextSegments.some(row=>!row.source_keys||!row.limits)||nextEvidence.some(row=>!row.source_keys||!row.limits))throw new Error('The road response used an incompatible evidence contract.');setSegments(nextSegments);setEvidence(nextEvidence);setState('ready');}).catch(problem=>{if(controller.signal.aborted)return;setError(problem instanceof Error?problem.message:'The road comparison could not be loaded.');setState('error');});return()=>controller.abort();},[attempt]);
  const segment=segments.find(row=>row.segment_id===selectedSegment)??segments[0];const lens=evidence.find(row=>row.evidence_id===selectedEvidence)??evidence[0];
  const retry=()=>{setSegments([]);setEvidence([]);setError('');setState('loading');setAttempt(value=>value+1);};
  if(state!=='ready'||!segment||!lens)return <div className={`data-state persia-road-data-state ${state}`} role={state==='error'?'alert':'status'}><b>{state==='error'?'The road-and-relay evidence did not load':'Loading six itinerary segments…'}</b><span>{state==='error'?error:'stages · traveler clock · handoffs · provisioning'}</span>{state==='error'&&<button type="button" onClick={retry}>Retry evidence</button>}</div>;
  return <div className="persia-road-chart">
    <section className="persia-route"><header><div><span>Textual route strip</span><h5>Sardis → Susa</h5></div><small>450 parasangs retained · no kilometre conversion or invented geometry</small></header><div className="persia-route-strip" aria-label="Six Royal Road itinerary segments">{segments.map((row,index)=><button key={row.segment_id} type="button" className={row.segment_id===segment.segment_id?'active':''} style={{width:`${Number(row.parasangs)/4.5}%`,'--route-color':colors[index]} as React.CSSProperties} onClick={()=>setSelectedSegment(row.segment_id)}><i/><b>{row.region}</b><small>{row.stages} stages</small></button>)}</div><div className="persia-route-ends"><span>Sardis</span><span>Susa</span></div></section>
    <section className="persia-segment"><header><div><span>Selected segment · {segment.start_label} to {segment.end_label}</span><h5>{segment.region}</h5></div><div><b>{segment.stages} stages</b><small>{segment.parasangs} parasangs</small></div></header><p>{segment.terrain_and_control}</p><div><span>What it cannot prove</span><p>{segment.limits}</p><b>{segment.source_keys}</b></div></section>
    <section className="persia-evidence"><header><div><span>Four unlike evidence lenses</span><h5>How did distance become a relay problem?</h5></div><small>select a lens · blanks are unknown, not zero</small></header><nav aria-label="Choose a road-and-relay evidence lens">{evidence.map(row=><button type="button" key={row.evidence_id} className={row.evidence_id===lens.evidence_id?'active':''} onClick={()=>setSelectedEvidence(row.evidence_id)}><span>{row.date_label}</span><b>{row.title}</b><small>{row.anchor_value?`${row.anchor_value} ${row.anchor_unit}`:row.anchor_unit}</small></button>)}</nav><article><div><span>{label(lens.evidence_class)}</span><h6>{lens.title}</h6><b>{lens.anchor_value?`${lens.anchor_value} ${lens.anchor_unit}`:lens.anchor_unit}</b></div><div><p>{lens.observation}</p><strong>{lens.interpretation}</strong></div></article></section>
    <section className="persia-road-limit"><div><p>{lens.limits}</p></div></section>
  </div>;
}
