'use client';

import { useEffect, useState } from 'react';
import { fetchClientText } from './lib/clientAsset';

type CoalitionWindow={case_id:string;sort_order:string;title:string;date_label:string;source_class:string;contributors:string;command_link:string;battlefield_function:string;supply_support:string;coordination_test:string;reported_anchor:string;source_keys:string;interpretation:string;limits:string};
const REVISION='20260830-coalition1';
const dataUrl=`/data/persia/${REVISION}/persian-coalition-windows.csv`;
const colors:Record<string,string>={doriscus_catalogue:'#a52836',xerxes_depots:'#98743d',imperial_fleet:'#3e718c',cunaxa:'#7b638d',gaugamela:'#546f66',persepolis_substrate:'#6a7780'};

function parseCSV<T>(text:string):T[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const[headers,...body]=rows;return body.map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])) as T);}
const label=(value:string)=>value.replaceAll('_',' ');
const short=(value:string,max=122)=>value.length>max?`${value.slice(0,max).replace(/\s+\S*$/,'')}…`:value;

export default function PersianCoalitionArmy(){
  const[rows,setRows]=useState<CoalitionWindow[]>([]);const[state,setState]=useState<'loading'|'ready'|'error'>('loading');const[error,setError]=useState('');const[selected,setSelected]=useState('cunaxa');const[mode,setMode]=useState<'circuit'|'matrix'>('circuit');const[attempt,setAttempt]=useState(0);
  useEffect(()=>{const controller=new AbortController();fetchClientText(dataUrl,{signal:controller.signal,label:'Persian coalition army windows'}).then(text=>{const parsed=parseCSV<CoalitionWindow>(text).sort((a,b)=>Number(a.sort_order)-Number(b.sort_order));if(parsed.length!==6||new Set(parsed.map(row=>row.case_id)).size!==6||parsed.some(row=>!row.contributors||!row.command_link||!row.supply_support||!row.coordination_test||!row.source_keys||!row.limits))throw new Error('The coalition response used an incompatible evidence contract.');setRows(parsed);setState('ready');}).catch(problem=>{if(controller.signal.aborted)return;setError(problem instanceof Error?problem.message:'The coalition comparison could not be loaded.');setState('error');});return()=>controller.abort();},[attempt]);
  const active=rows.find(row=>row.case_id===selected)??rows[0];const retry=()=>{setRows([]);setError('');setState('loading');setAttempt(value=>value+1);};
  if(state!=='ready'||!active)return <div className={`data-state persia-coalition-data-state ${state}`} role={state==='error'?'alert':'status'}><b>{state==='error'?'The coalition evidence did not load':'Loading six military assembly windows…'}</b><span>{state==='error'?error:'contributors · command · battlefield function · supply · coordination'}</span>{state==='error'&&<button type="button" onClick={retry}>Retry coalition evidence</button>}</div>;
  const circuit=[['01 · Contributors',active.contributors],['02 · Command link',active.command_link],['03 · Battlefield function',active.battlefield_function],['04 · Supply and support',active.supply_support]];
  return <div className="persia-coalition-chart" style={{'--coalition-color':colors[active.case_id]} as React.CSSProperties}>
    <div className="persia-coalition-mode" role="group" aria-label="Choose a coalition army view"><button type="button" className={mode==='circuit'?'active':''} onClick={()=>setMode('circuit')}>Follow one assembly</button><button type="button" className={mode==='matrix'?'active':''} onClick={()=>setMode('matrix')}>Compare six windows</button></div>
    <nav className="persia-coalition-tabs" aria-label="Choose a military assembly window">{rows.map(row=><button type="button" key={row.case_id} className={selected===row.case_id?'active':''} onClick={()=>setSelected(row.case_id)} style={{'--case-color':colors[row.case_id]} as React.CSSProperties}><span>{row.date_label}</span><b>{row.title}</b><small>{label(row.source_class)}</small></button>)}</nav>
    {mode==='circuit'?<><section className="persia-coalition-focus"><header><div><span>{label(active.source_class)}</span><h5>{active.title}</h5></div><small>{active.date_label}</small></header><strong>{active.interpretation}</strong><div className="persia-coalition-circuit">{circuit.map(([stage,copy],index)=><div className="persia-coalition-stage" key={stage}><article><span>{stage}</span><p>{copy}</p></article>{index<circuit.length-1&&<i aria-hidden="true">→</i>}</div>)}</div><div className="persia-coalition-test"><span>Coordination test</span><p>{active.coordination_test}</p><b>{active.reported_anchor}</b></div></section></>:<section className="persia-coalition-matrix"><header><div><span>Six unlike windows</span><h5>Scale came from connecting systems</h5></div><small>select a row · cells are not scores</small></header><div className="persia-coalition-matrix-head"><b>Window</b><b>Contributors</b><b>Command</b><b>Support</b><b>Coordination</b></div>{rows.map(row=><button type="button" key={row.case_id} className={selected===row.case_id?'active':''} onClick={()=>setSelected(row.case_id)}><i style={{background:colors[row.case_id]}}/><span><b>{row.title}</b><small>{row.date_label}</small></span><p data-label="Contributors">{short(row.contributors)}</p><p data-label="Command">{short(row.command_link)}</p><p data-label="Support">{short(row.supply_support)}</p><p data-label="Coordination">{short(row.coordination_test)}</p></button>)}</section>}
  </div>;
}
