'use client';

import { useEffect, useMemo, useState } from 'react';
import { fetchClientText } from './lib/clientAsset';

type RecordRow={record_id:string;sort_order:string;kind:'system'|'conquest';system_role:string;start_year:string;end_year:string;date_label:string;title:string;evidence_class:string;observed_evidence:string;source_keys:string;interpretation:string;limits:string};
const dataUrl='/data/qin-han/20260830-mobilization1/qin-mobilizing-system.csv';

function parseCSV<T>(text:string):T[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const[headers,...body]=rows;return body.map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])) as T);}

export default function QinMobilizingSystem(){
  const[rows,setRows]=useState<RecordRow[]>([]);const[state,setState]=useState<'loading'|'ready'|'error'>('loading');const[error,setError]=useState('');const[selected,setSelected]=useState('interstate_pressure');const[attempt,setAttempt]=useState(0);
  useEffect(()=>{const controller=new AbortController();fetchClientText(dataUrl,{signal:controller.signal,label:'Qin mobilizing-system evidence'}).then(text=>{const parsed=parseCSV<RecordRow>(text).sort((a,b)=>Number(a.sort_order)-Number(b.sort_order));const system=parsed.filter(row=>row.kind==='system'),conquest=parsed.filter(row=>row.kind==='conquest');if(parsed.length!==11||system.length!==5||conquest.length!==6||parsed.some(row=>!row.record_id||!row.title||!row.observed_evidence||!row.source_keys||!row.limits))throw new Error('The mobilization response used an incompatible evidence contract.');setRows(parsed);setState('ready');}).catch(problem=>{if(controller.signal.aborted)return;setError(problem instanceof Error?problem.message:'The evidence could not be loaded.');setState('error');});return()=>controller.abort();},[attempt]);
  const system=useMemo(()=>rows.filter(row=>row.kind==='system'),[rows]);const conquests=useMemo(()=>rows.filter(row=>row.kind==='conquest'),[rows]);const active=rows.find(row=>row.record_id===selected)??rows[0];
  const retry=()=>{setRows([]);setError('');setState('loading');setAttempt(value=>value+1);};
  if(state!=='ready'||!active)return <div className={`data-state qin-mobilization-state ${state}`} role={state==='error'?'alert':'status'}><b>{state==='error'?'The mobilization evidence did not load':'Loading the mobilizing system…'}</b><span>{state==='error'?error:'pressure · households · rewards · reports · supply'}</span>{state==='error'&&<button type="button" onClick={retry}>Retry evidence</button>}</div>;
  return <div className="qin-mobilization-chart">
    <div className="qin-mobilization-summary"><div><span>Linked capacities</span><b>5</b><small>not one reform decree</small></div><div><span>Final sequence</span><b>230–221 BCE</b><small>six rival courts</small></div><div><span>Army totals</span><b>Excluded</b><small>ancient headline figures rejected</small></div></div>
    <section className="qin-system" aria-label="Five linked mobilizing capacities"><header><span>Generations of administrative competition</span><b>What had to work before the last conquests?</b></header><div>{system.map((row,index)=><button type="button" key={row.record_id} className={selected===row.record_id?'active':''} onClick={()=>setSelected(row.record_id)}><span>0{index+1}</span><b>{row.system_role}</b><small>{row.title}</small>{index<system.length-1&&<i aria-hidden="true">→</i>}</button>)}</div></section>
    <section className="qin-conquests" aria-label="Political endpoints of the six final conquests"><header><div><span>The last political endpoints</span><b>Nine years removed six rival courts</b></div><small>dates are not continuous boundaries</small></header><div>{conquests.map(row=><button type="button" key={row.record_id} className={selected===row.record_id?'active':''} onClick={()=>setSelected(row.record_id)}><b>{row.date_label.replace(' BCE','')}</b><span>{row.title}</span></button>)}</div></section>
    <section className="qin-record" aria-live="polite"><header><div><span>{active.kind==='system'?'Selected capacity':'Selected political endpoint'} · {active.evidence_class}</span><h5>{active.title}</h5></div><b>{active.date_label}</b></header><div className="qin-record-grid"><article><span>Observed evidence</span><p>{active.observed_evidence}</p></article><article><span>What it supports</span><p>{active.interpretation}</p></article><article><span>What it cannot establish</span><p>{active.limits}</p></article></div><footer><span>Source keys</span><b>{active.source_keys.split(';').join(' · ')}</b></footer></section>
    <div className="cradle-downloads qin-downloads"><p><b>Administration made conquest repeatable; it did not make control complete.</b> Qin is the best-documented winner, not the only Warring States reformer.</p><a href={dataUrl} download>Download 11 records ↓</a></div>
  </div>;
}
