'use client';

import { useEffect, useMemo, useState } from 'react';
import { fetchClientText } from './lib/clientAsset';

type StandardRow={record_id:string;sort_order:string;channel:string;date_label:string;standard_or_claim:string;observed_practice:string;sample_label:string;conforming_count:string;sample_count:string;result_label:string;source_keys:string;interpretation:string;limits:string};
const dataUrl='/data/qin-han/20260830-standardization1/qin-standardization-practice.csv';

function parseCSV<T>(text:string):T[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const[headers,...body]=rows;return body.map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])) as T);}

export default function QinStandardizationPractice(){
  const[rows,setRows]=useState<StandardRow[]>([]);const[state,setState]=useState<'loading'|'ready'|'error'>('loading');const[error,setError]=useState('');const[selected,setSelected]=useState('measure_certification');const[attempt,setAttempt]=useState(0);
  useEffect(()=>{const controller=new AbortController();fetchClientText(dataUrl,{signal:controller.signal,label:'Qin standardization evidence'}).then(text=>{const parsed=parseCSV<StandardRow>(text).sort((a,b)=>Number(a.sort_order)-Number(b.sort_order));if(parsed.length!==6||parsed.some(row=>!row.record_id||!row.channel||!row.standard_or_claim||!row.observed_practice||!row.source_keys||!row.limits))throw new Error('The standardization response used an incompatible evidence contract.');for(const row of parsed){if(Boolean(row.conforming_count)!==Boolean(row.sample_count))throw new Error('A bounded sample is missing one of its counts.');}setRows(parsed);setState('ready');}).catch(problem=>{if(controller.signal.aborted)return;setError(problem instanceof Error?problem.message:'The evidence could not be loaded.');setState('error');});return()=>controller.abort();},[attempt]);
  const active=rows.find(row=>row.record_id===selected)??rows[0];const quantitative=useMemo(()=>rows.filter(row=>row.sample_count),[rows]);
  const retry=()=>{setRows([]);setError('');setState('loading');setAttempt(value=>value+1);};
  if(state!=='ready'||!active)return <div className={`data-state qin-standard-state ${state}`} role={state==='error'?'alert':'status'}><b>{state==='error'?'The standardization evidence did not load':'Loading norms and local traces…'}</b><span>{state==='error'?error:'measure · script · tablet · tally'}</span>{state==='error'&&<button type="button" onClick={retry}>Retry comparison</button>}</div>;
  return <div className="qin-standard-chart">
    <div className="qin-standard-thesis"><span>Standardization ≠ sameness</span><strong>The center defined interfaces. Local offices decided how literally to realize them.</strong></div>
    <nav className="qin-standard-tabs" aria-label="Choose one standardization evidence window">{rows.map((row,index)=><button type="button" key={row.record_id} className={selected===row.record_id?'active':''} onClick={()=>setSelected(row.record_id)}><span>0{index+1}</span><b>{row.channel}</b><small>{row.result_label}</small></button>)}</nav>
    <section className="qin-standard-circuit"><article><span>Formal norm or later claim</span><h5>{active.channel}</h5><p>{active.standard_or_claim}</p></article><i aria-hidden="true">→</i><article><span>Excavated or epigraphic trace</span><h5>{active.date_label}</h5><p>{active.observed_practice}</p></article></section>
    {active.sample_count?<section className="qin-standard-meter"><header><div><span>Published sample</span><b>{active.sample_label}</b></div><strong>{active.result_label}</strong></header><div><i style={{width:`${Number(active.conforming_count)/Number(active.sample_count)*100}%`}}/><span>{active.conforming_count}</span><em>{Number(active.sample_count)-Number(active.conforming_count)} outside this criterion</em></div></section>:<section className="qin-standard-qualitative"><span>Object or inscription</span><b>{active.result_label}</b></section>}
    <section className="qin-standard-overview"><header><span>Four directly counted comparisons</span><b>Rules survived. Literal compliance varied by feature.</b></header>{quantitative.map(row=><button type="button" key={row.record_id} className={selected===row.record_id?'active':''} onClick={()=>setSelected(row.record_id)}><span>{row.channel}</span><div><i style={{width:`${Number(row.conforming_count)/Number(row.sample_count)*100}%`}}/></div><b>{row.result_label}</b></button>)}</section>
  </div>;
}
