'use client';

import { useEffect, useState } from 'react';
import ChartFooter from './components/ChartFooter';
import { fetchClientText } from './lib/clientAsset';

type Row={case_id:string;polity:string;date_label:string;scale_value:string;scale_label:string;recruitment_system:string;replacement_system:string};
type Mode='deployment'|'equipment';
const dataUrl='/data/iron-age/20260830-mobilization1/iron-mobilization-cases.csv';
const colors:Record<string,string>={carthage_215:'#8b6b9d',rome_212:'#bd1f2e'};
function parseCSV(text:string):Row[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const[headers,...body]=rows;return body.map(values=>Object.fromEntries(headers.map((key,index)=>[key,values[index]??''])) as Row);}

export default function RomanAllianceComparison(){
  const[rows,setRows]=useState<Row[]>([]);const[state,setState]=useState<'loading'|'ready'|'error'>('loading');const[mode,setMode]=useState<Mode>('deployment');
  useEffect(()=>{const controller=new AbortController();fetchClientText(dataUrl,{signal:controller.signal,label:'Punic War mobilization comparison'}).then(text=>{const selected=parseCSV(text).filter(row=>['carthage_215','rome_212'].includes(row.case_id));if(selected.length!==2||selected.some(row=>!Number.isFinite(Number(row.scale_value))))throw new Error('The mobilization comparison used an incompatible schema.');setRows(selected);setState('ready');}).catch(()=>{if(!controller.signal.aborted)setState('error');});return()=>controller.abort();},[]);
  if(state!=='ready')return <div className={`data-state roman-alliance-state ${state}`} role={state==='error'?'alert':'status'}><b>{state==='error'?'The mobilization comparison did not load':'Loading the Punic War comparison…'}</b></div>;
  return <div className="roman-alliance-comparison">
    <header className="roman-alliance-heading"><span>SECOND PUNIC WAR · LIKE-FOR-LIKE MODELS</span><h4>Rome won because its Italian alliance could survive defeat</h4><p>Carthage matched Rome&apos;s peak deployment. The difference was how each republic rebuilt armies.</p></header>
    <nav className="roman-alliance-modes" aria-label="Choose a military comparison"><button type="button" className={mode==='deployment'?'active':''} onClick={()=>setMode('deployment')}>Strategic deployment</button><button type="button" className={mode==='equipment'?'active':''} onClick={()=>setMode('equipment')}>Worked metal</button></nav>
    {mode==='deployment'?<><div className="roman-alliance-bars">{rows.map(row=><article key={row.case_id}><div><b>{row.polity.replace(' and the Italian allies','')}</b><span>{row.date_label}</span></div><i><em style={{width:`${Number(row.scale_value)/185000*100}%`,background:colors[row.case_id]}} /></i><strong>{row.scale_label}</strong></article>)}</div><div className="roman-alliance-takeaway"><strong>Similar peaks, different foundations</strong><p>Taylor reconstructs approximately 170,000 Carthaginian and 185,000 Roman troops deployed across simultaneous theaters. That small modeled gap cannot explain victory. Rome&apos;s advantage was a durable core of citizens, Latin colonies, and Italian allies that still furnished armies after catastrophic defeats.</p></div><div className="roman-alliance-systems">{rows.map(row=><article key={row.case_id}><h5>{row.polity.replace(' and the Italian allies','')}</h5><p><b>Recruitment:</b> {row.recruitment_system}</p><p><b>Replacement:</b> {row.replacement_system}</p></article>)}</div><ChartFooter source="Michael J. Taylor, Soldiers and Silver (2020)" note="The bars are Taylor's strategic-deployment models, not battlefield counts. They compare 215 BCE Carthage with 212 BCE Rome and do not imply a 15,000-man precision margin." dataHref={dataUrl}/></>:<><div className="roman-equipment-bars"><article><b>Roman heavy infantry</b><i><em style={{width:'100%'}} /></i><strong>125</strong></article><article><b>Nearest comparator</b><i><em style={{width:'80%'}} /></i><strong>100</strong></article></div><div className="roman-alliance-takeaway"><strong>Better equipped did not mean cheaper</strong><p>Devereaux&apos;s bounded third–second-century BCE model puts about 25% more worked iron and bronze on a Roman heavy infantryman than on the nearest comparator. Rome combined mass mobilization with material-intensive soldiers; the public evidence does not support kilograms for every rival.</p></div><ChartFooter source="Bret Devereaux's comparative panoply model" note="Relative index only: nearest comparator = 100. Iron and bronze are combined; this is not a kilogram estimate or a time series." dataHref="/data/rome/20260830-client4/equipment-comparison.csv"/></>}
  </div>;
}
