'use client';

import { useEffect, useRef, useState } from 'react';

type Point=[number,number];
type Geometry={type:string;arcs:unknown};
type Topology={transform:{scale:Point;translate:Point};arcs:Point[][];objects:Record<string,{geometries:Geometry[]}>};
type GeoGeometry={type:'Polygon'|'MultiPolygon';coordinates:Point[][]|Point[][][]};
type GeoFeature={properties:{Name:string;FromYear:number;ToYear:number;Area:number};geometry:GeoGeometry};
type GeoCollection={features:GeoFeature[]};
type MapData={land:Topology;borders:Topology;rivers:Topology;polities:GeoCollection};

const MIN_YEAR=-500,MAX_YEAR=476;
const romanNames=new Set(['Roman Republic','Roman Empire','Eastern Roman Empire','Western Roman Empire','Gallic Empire']);
const colors:Record<string,string>={'Roman Republic':'#ad2332','Roman Empire':'#ad2332','Eastern Roman Empire':'#2d6898','Western Roman Empire':'#ad2e3e','Gallic Empire':'#527b8f','Achaemenid Empire':'#9b709f','Carthage':'#c59a3e','(Macedonian Empire)':'#5f8fa2','Antigonid Macedonia':'#5f8fa2','Seleucid Empire':'#d18b42','Ptolemaic Kingdom':'#4f9291','Parthian Empire':'#8b6b9d','Sasanian Empire':'#76558a','Etruscans':'#a17c55','Greek City-States':'#6a91ad','Galatia':'#7f9c61','Kingdom of Numidia':'#b07e4b','Illyrian Kingdom':'#77946d','Nabataeans':'#b16f67','Vandal Kingdom':'#8a7456','Visigothic Kingdom':'#789159','Ostrogothic Kingdom':'#627f54','Kingdom of the Franks':'#527b7f','Kingdom of the Suebi':'#92795b','Burgundian Kingdom':'#7e6d91','Brythons':'#81916a'};
const cities:Array<[number,number,string]>=[[12.5,41.9,'Rome'],[-5.98,37.39,'Hispalis'],[2.35,48.86,'Lutetia'],[-.13,51.5,'Londinium'],[23.73,37.98,'Athens'],[29,41.01,'Constantinople'],[10.32,36.85,'Carthage'],[36.28,33.51,'Damascus'],[29.92,31.2,'Alexandria']];
const events=[[-500,'Early Republic'],[-338,'Latin War won'],[-264,'First Punic War'],[-218,'Hannibal invades'],[-202,'Zama'],[-146,'Carthage destroyed'],[-49,'Civil War'],[-27,'Augustus'],[117,'Maximum extent'],[212,'Universal citizenship'],[293,'Tetrarchy'],[312,'Constantine'],[395,'East–West courts'],[410,'Rome sacked'],[439,'Vandals take Carthage'],[476,'Western court ends']] as const;

const VIEW={west:-12,east:63,south:20,north:58};
function project([lon,lat]:Point,w:number,h:number):Point{const x=((lon-VIEW.west)/(VIEW.east-VIEW.west))*w;const m=(v:number)=>Math.log(Math.tan(Math.PI/4+(v*Math.PI/180)/2));return[x,((m(VIEW.north)-m(lat))/(m(VIEW.north)-m(VIEW.south)))*h];}
function decodeArc(topology:Topology,index:number):Point[]{const reversed=index<0,arc=topology.arcs[reversed?~index:index];let x=0,y=0;const points=arc.map(([dx,dy])=>{x+=dx;y+=dy;return[x*topology.transform.scale[0]+topology.transform.translate[0],y*topology.transform.scale[1]+topology.transform.translate[1]] as Point;});return reversed?points.reverse():points;}
function topoLines(topology:Topology,geometry:Geometry):Point[][]{const lines=geometry.type==='LineString'?[geometry.arcs]:geometry.arcs as number[][];return(lines as number[][]).map(line=>line.flatMap((arc,i)=>{const p=decodeArc(topology,arc);return i?p.slice(1):p;}));}
function topoRings(topology:Topology,geometry:Geometry):Point[][]{const polygons=geometry.type==='Polygon'?[geometry.arcs]:geometry.arcs as number[][][];return(polygons as number[][][]).flatMap(poly=>poly.map(ring=>ring.flatMap((arc,i)=>{const p=decodeArc(topology,arc);return i?p.slice(1):p;})));}
function geoRings(geometry:GeoGeometry):Point[][]{return geometry.type==='Polygon'?geometry.coordinates as Point[][]:(geometry.coordinates as Point[][][]).flat();}
function makePath(ctx:CanvasRenderingContext2D,rings:Point[][]){ctx.beginPath();rings.forEach(ring=>ring.forEach((p,i)=>{const[x,y]=project(p,ctx.canvas.width,ctx.canvas.height);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}));}
function label(ctx:CanvasRenderingContext2D,text:string,lon:number,lat:number,color='#27343d'){const[x,y]=project([lon,lat],ctx.canvas.width,ctx.canvas.height);ctx.fillStyle=color;ctx.font='600 11px Arial';ctx.textAlign='center';ctx.fillText(text,x,y);}
function featureLabel(feature:GeoFeature){const names:Record<string,string>={'(Macedonian Empire)':'MACEDON','Antigonid Macedonia':'MACEDON','Greek City-States':'GREEK CITY-STATES','Kingdom of Numidia':'NUMIDIA','Roman Republic':'ROME','Roman Empire':'ROMAN EMPIRE','Eastern Roman Empire':'EASTERN ROMAN EMPIRE','Western Roman Empire':'WESTERN ROMAN EMPIRE'};return names[feature.properties.Name]||feature.properties.Name.toUpperCase();}
function drawFeature(ctx:CanvasRenderingContext2D,feature:GeoFeature,color:string,showLabel=true){const rings=geoRings(feature.geometry);makePath(ctx,rings);ctx.fillStyle=`${color}c4`;ctx.fill('evenodd');ctx.strokeStyle='rgba(42,49,54,.62)';ctx.lineWidth=1;ctx.stroke();if(!showLabel||feature.properties.Area<35000)return;const points=rings.flat().filter(([lon,lat])=>lon>=VIEW.west&&lon<=VIEW.east&&lat>=VIEW.south&&lat<=VIEW.north);if(!points.length)return;const minLon=Math.min(...points.map(p=>p[0])),maxLon=Math.max(...points.map(p=>p[0])),minLat=Math.min(...points.map(p=>p[1])),maxLat=Math.max(...points.map(p=>p[1]));label(ctx,featureLabel(feature),(minLon+maxLon)/2,(minLat+maxLat)/2);}
function displayYear(year:number){return year<0?`${Math.abs(year)} BCE`:year===0?'1 BCE → 1 CE':`${year} CE`;}
function narrative(year:number):[string,string]{if(year<-338)return['Rome is one Italian republic','The annual clock begins before Rome dominates even the Italian peninsula.'];if(year<-264)return['Rome becomes the leading Italian power','The Latin settlement and allied system give Rome a deep military base.'];if(year<-202)return['Rome and Carthage contest the western sea','Two expanding systems collide across Sicily, Iberia, Africa, and Italy.'];if(year<-146)return['Rome becomes a Mediterranean power','Carthage survives, but Roman armies increasingly intervene east and west.'];if(year<-27)return['The Republic acquires an empire','Provincial conquest and civil wars transform the political system.'];if(year<117)return['One imperial state around the Mediterranean','The Principate consolidates provinces and pushes toward the Rhine, Danube, and Euphrates.'];if(year<235)return['The empire at continental scale','Rome holds most territory steady after Trajan’s brief eastern maximum.'];if(year<293)return['Crisis and recovery','Civil war, invasion, and fiscal strain contract and reorganize the empire.'];if(year<=312)return['Four courts, one Roman Empire','The Tetrarchy divides administrative responsibility—not sovereignty—among imperial courts.'];if(year<395)return['A single empire with shifting courts','Constantine reunifies the state; later emperors again govern from multiple regional courts.'];if(year<476)return['Eastern and western imperial courts','Separate fiscal and military commands respond to increasingly different strategic worlds.'];return['The western court is gone; Rome continues east','Successor kingdoms occupy the West while the eastern Roman state survives.'];}

export default function RomanMap(){
  const canvas=useRef<HTMLCanvasElement>(null);const[data,setData]=useState<MapData|null>(null);const[year,setYear]=useState(117);const[playing,setPlaying]=useState(false);
  useEffect(()=>{Promise.all([fetch('/data/land.topojson').then(r=>r.json()),fetch('/data/borders.topojson').then(r=>r.json()),fetch('/data/rivers.topojson').then(r=>r.json()),fetch('/data/ancient-polities.geojson').then(r=>r.json())]).then(([land,borders,rivers,polities])=>setData({land,borders,rivers,polities}));},[]);
  useEffect(()=>{if(!playing)return;const timer=window.setInterval(()=>setYear(value=>value>=MAX_YEAR?MIN_YEAR:value===-1?1:value+1),65);return()=>window.clearInterval(timer);},[playing]);
  const context=narrative(year);
  useEffect(()=>{if(!data||!canvas.current)return;const ctx=canvas.current.getContext('2d');if(!ctx)return;const w=ctx.canvas.width,h=ctx.canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#dcecf2';ctx.fillRect(0,0,w,h);
    data.land.objects['10m_land'].geometries.forEach(g=>{makePath(ctx,topoRings(data.land,g));ctx.fillStyle='#ece9df';ctx.fill('evenodd');ctx.strokeStyle='#b8b9b2';ctx.lineWidth=.8;ctx.stroke();});
    data.rivers.objects['10m_rivers_lake_centerlines'].geometries.forEach(g=>{makePath(ctx,topoLines(data.rivers,g));ctx.strokeStyle='rgba(111,163,186,.55)';ctx.lineWidth=.55;ctx.stroke();});
    data.borders.objects.geo_lines.geometries.forEach(g=>{makePath(ctx,topoLines(data.borders,g));ctx.strokeStyle='rgba(122,125,121,.3)';ctx.lineWidth=.45;ctx.stroke();});
    const active=data.polities.features.filter(f=>f.properties.FromYear<=year&&f.properties.ToYear>=year).sort((a,b)=>b.properties.Area-a.properties.Area);const others=active.filter(f=>!romanNames.has(f.properties.Name)),rome=active.filter(f=>romanNames.has(f.properties.Name));others.forEach(f=>drawFeature(ctx,f,colors[f.properties.Name]||'#849078'));
    if(year<=-50)label(ctx,'GALLIC PEOPLES · NO SINGLE STATE',-1,49,'rgba(63,91,57,.86)');
    if(year>=293&&year<=312&&rome.length){const layer=document.createElement('canvas');layer.width=w;layer.height=h;const lctx=layer.getContext('2d')!;rome.forEach(f=>drawFeature(lctx,f,'#ad2332',false));lctx.globalCompositeOperation='source-atop';const blocks=[[-12,7,'#346e91'],[7,18,'#a62d3c'],[18,33,'#d37c33'],[33,63,'#c6a244']] as const;blocks.forEach(([a,b,color])=>{const[x]=project([a,30],w,h),[x2]=project([b,30],w,h);lctx.fillStyle=color;lctx.fillRect(x,0,x2-x,h);});lctx.globalCompositeOperation='source-over';ctx.drawImage(layer,0,0);label(ctx,'CONSTANTIUS',-3,52,'#fff');label(ctx,'MAXIMIAN',9,44,'#fff');label(ctx,'DIOCLETIAN',23,34,'#fff');label(ctx,'GALERIUS',40,40,'#fff');}else rome.forEach(f=>drawFeature(ctx,f,colors[f.properties.Name]||'#ad2332'));
    cities.forEach(([lon,lat,name])=>{const[x,y]=project([lon,lat],w,h);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x,y,3.2,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#18222c';ctx.lineWidth=1.4;ctx.stroke();ctx.fillStyle='#18222c';ctx.font='600 9px Arial';ctx.textAlign='left';ctx.fillText(name,x+6,y-5);});ctx.fillStyle='rgba(54,105,129,.72)';ctx.font='italic 13px Georgia';ctx.fillText('Atlantic Ocean',42,255);ctx.fillText('Mediterranean Sea',440,436);
  },[data,year]);
  const setSafeYear=(value:number)=>{setPlaying(false);setYear(value===0?1:value);};
  return <div className="map-module"><div className="map-heading"><div><span>Roman territorial history · annual timeline</span><h4>{context[0]}</h4><p>{context[1]}</p></div><div className="map-date"><b>{displayYear(year)}</b><small>one-year resolution</small></div></div><div className="map-stage"><canvas ref={canvas} width="1100" height="570" aria-label={`Political map of Rome and neighboring polities in ${displayYear(year)}`} /><div className="map-key"><span><i className="roman"/>Roman polity</span><span><i className="neighbor-key"/>Seshat/Cliopatria polities</span></div></div><div className="timeline-control annual"><button className="step" onClick={()=>setSafeYear(Math.max(MIN_YEAR,year-1))} type="button" aria-label="Previous year">−1</button><button className="play" onClick={()=>setPlaying(v=>!v)} type="button" aria-label={playing?'Pause timeline':'Play timeline'}>{playing?'Ⅱ':'▶'}</button><button className="step" onClick={()=>setSafeYear(Math.min(MAX_YEAR,year+1))} type="button" aria-label="Next year">+1</button><div className="timeline-track"><input aria-label="Year in Roman history" type="range" min={MIN_YEAR} max={MAX_YEAR} step="1" value={year} onChange={e=>setSafeYear(Number(e.target.value))}/><div className="year-ticks"><button onClick={()=>setSafeYear(-500)} type="button">500 BCE</button><button onClick={()=>setSafeYear(-250)} type="button">250 BCE</button><button onClick={()=>setSafeYear(1)} type="button">1 CE</button><button onClick={()=>setSafeYear(250)} type="button">250 CE</button><button onClick={()=>setSafeYear(476)} type="button">476 CE</button></div></div></div><div className="event-jumps">{events.map(([eventYear,name])=><button className={year===eventYear?'active':''} onClick={()=>setSafeYear(eventYear)} type="button" key={eventYear}><b>{displayYear(eventYear)}</b><span>{name}</span></button>)}</div><div className="map-foot"><p><b>Every slider step is one year.</b> A boundary remains in place until the next dated Seshat geometry; event buttons jump without changing that annual clock. The four colors from 293–312 are administrative portfolios inside one Roman Empire.</p><p>Political geometry: Seshat Cliopatria, CC BY 4.0, simplified for display. Physical basemap: Natural Earth. Ancient borders remain historical reconstructions.</p></div></div>;
}
