'use client';

import { useEffect, useState } from 'react';
import ChartFooter from './components/ChartFooter';
import { fetchClientText } from './lib/clientAsset';

type Row={outcome:string;outcome_order:number;period:string;region:'Europe'|'MENA';coefficient:number;standard_error:number;significant_10pct:'yes'|'no';interpretation:string;source_keys:string;note:string};
const DATA_URL='/data/rome/20260831-roads1/roman-road-persistence.csv';
const MIN=-0.6;const MAX=2.2;

function parseCSV(text:string):Row[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let index=0;index<text.length;index+=1){const character=text[index];if(character==='"'&&quoted&&text[index+1]==='"'){cell+='"';index+=1;}else if(character==='"')quoted=!quoted;else if(character===','&&!quoted){row.push(cell);cell='';}else if((character==='\n'||character==='\r')&&!quoted){if(character==='\r'&&text[index+1]==='\n')index+=1;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=character;}if(cell||row.length){row.push(cell);rows.push(row);}const[headers,...body]=rows;return body.map(values=>{const item=Object.fromEntries(headers.map((header,index)=>[header,values[index]??'']));return {...item,outcome_order:Number(item.outcome_order),coefficient:Number(item.coefficient),standard_error:Number(item.standard_error)} as Row;});}
function left(value:number){return `${((value-MIN)/(MAX-MIN))*100}%`;}

export default function RomanAfterlivesChart(){
  const[rows,setRows]=useState<Row[]>([]);const[view,setView]=useState<'evidence'|'alternatives'>('evidence');const[error,setError]=useState('');
  useEffect(()=>{const controller=new AbortController();fetchClientText(`${DATA_URL}?v=20260831-roads1`,{signal:controller.signal,label:'Roman road persistence evidence'}).then(text=>{const parsed=parseCSV(text);if(parsed.length!==8||new Set(parsed.map(row=>row.outcome)).size!==4||parsed.some(row=>!Number.isFinite(row.coefficient)||!Number.isFinite(row.standard_error)))throw new Error('The road-persistence comparison was incomplete.');setRows(parsed);}).catch(reason=>{if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:'The comparison could not be loaded.');});return()=>controller.abort();},[]);
  const outcomes=[...new Map(rows.sort((a,b)=>a.outcome_order-b.outcome_order).map(row=>[row.outcome,row])).keys()];
  return <div className="roman-road-legacy">
    <header><span>ROMAN ROAD DENSITY · EUROPE AND MENA</span><h4>Roman roads persisted where later societies kept using roads</h4><p>The same ancient network predicts modern roads and activity in Europe—but not where caravan routes replaced wheeled transport.</p></header>
    <nav aria-label="Choose a Roman legacy view"><button type="button" className={view==='evidence'?'active':''} onClick={()=>setView('evidence')}>Road persistence</button><button type="button" className={view==='alternatives'?'active':''} onClick={()=>setView('alternatives')}>Other Roman afterlives</button></nav>
    {error?<div className="data-state error" role="alert"><b>The road-persistence evidence did not load</b><p>{error}</p></div>:view==='evidence'?<div className="road-persistence">
      <div className="road-persistence-legend"><span><i className="europe"/>Europe</span><span><i className="mena"/>Middle East &amp; North Africa</span><small>Coefficient on log Roman-road density · whiskers show ±1.96 standard errors</small></div>
      <div className="road-coefficient-axis"><span>−0.6</span><span>0</span><span>0.6</span><span>1.2</span><span>1.8</span><span>2.2</span></div>
      <div className="road-coefficient-rows">{outcomes.map(outcome=><article key={outcome}><div><b>{outcome}</b><span>{rows.find(row=>row.outcome===outcome)?.period}</span></div><div className="road-coefficient-track"><i className="zero" style={{left:left(0)}}/>{rows.filter(row=>row.outcome===outcome).map(row=>{const low=row.coefficient-1.96*row.standard_error;const high=row.coefficient+1.96*row.standard_error;return <span className={row.region==='Europe'?'europe':'mena'} key={row.region} style={{left:left(row.coefficient)}}><em style={{left:`-${(row.coefficient-low)/(MAX-MIN)*100}%`,width:`${(high-low)/(MAX-MIN)*100}%`}}/><i/><strong>{row.coefficient.toFixed(3)}{row.significant_10pct==='yes'?'*':' NS'}</strong></span>;})}</div></article>)}</div>
      <div className="road-persistence-takeaway"><b>The ancient advantage survived only with continued use.</b><p>Both regions show settlement associations around 500 CE. By the modern period, only Europe retains statistically significant road, night-light, and population relationships.</p></div>
    </div>:<div className="roman-legacy-alternatives"><article><span>STATE</span><b>977 more years</b><p>The eastern Roman state continued from the end of the western court in 476 to Constantinople&apos;s conquest in 1453.</p></article><article><span>LANGUAGE</span><b>Gradual divergence</b><p>Latin became Romance vernaculars through regional change, not one dated institutional handoff.</p></article><article><span>LAW</span><b>Recovery, not continuity</b><p>Justinianic texts had little western influence for centuries before their medieval scholarly revival.</p></article><div><b>Why roads lead this insight</b><p>Roads offer the strongest measurable legacy test: the same imperial infrastructure can be compared where its use continued and where it was abandoned. The alternatives remain consequential, but they do not share one defensible numerical scale.</p></div></div>}
    <ChartFooter source="Dalgaard, Kaarsen, Olsson & Selaya (2022), Table 5" note="Log–log OLS coefficients with the paper's full controls. Asterisks mark significance at 10% or better; NS means not significant. The design supports a maintenance mechanism, not a universal effect of Roman pavement on modern prosperity." dataHref={DATA_URL}/>
  </div>;
}
