'use client';
import {useEffect,useMemo,useState} from 'react';
import {fetchClientText} from './lib/clientAsset';

type Row={case_id:string;region:string;period:string;incoming_label:string;incoming_percent:string;remaining_percent:string;display_anchor:string;comparison:string;language_evidence:string;source_keys:string;limits:string};
const dataUrl='/data/steppe/20260901-migration1/steppe-migration-outcomes.csv';
function parseCSV<T>(text:string):T[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const[headers,...body]=rows;return body.map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])) as T);}

export default function SteppeMigrationOutcomes(){const[rows,setRows]=useState<Row[]>([]);const[state,setState]=useState<'loading'|'ready'|'error'>('loading');const[error,setError]=useState('');const[attempt,setAttempt]=useState(0);const[selectedId,setSelectedId]=useState('corded_ware');useEffect(()=>{const controller=new AbortController();fetchClientText(dataUrl,{signal:controller.signal,label:'steppe migration evidence'}).then(text=>{const parsed=parseCSV<Row>(text);if(parsed.length!==4||parsed.some(row=>!row.case_id||!row.region||!row.display_anchor||Number.isNaN(Number(row.incoming_percent))||Number.isNaN(Number(row.remaining_percent))))throw new Error('The migration evidence used an incompatible data contract.');setRows(parsed);setState('ready');}).catch(problem=>{if(controller.signal.aborted)return;setError(problem instanceof Error?problem.message:'The migration evidence could not be loaded.');setState('error');});return()=>controller.abort();},[attempt]);const selected=useMemo(()=>rows.find(row=>row.case_id===selectedId)??rows[0],[rows,selectedId]);if(state!=='ready'||!selected)return <div className={`data-state steppe-migration-state ${state}`} role={state==='error'?'alert':'status'}><b>{state==='error'?'The migration comparison did not load':'Loading migration outcomes…'}</b><span>{state==='error'?error:'mixture · replacement · sex bias · language'}</span>{state==='error'&&<button type="button" onClick={()=>{setRows([]);setError('');setState('loading');setAttempt(value=>value+1);}}>Retry evidence</button>}</div>;return <div className="steppe-migration-chart"><div className="steppe-migration-bars" aria-label="Published ancestry estimates across four steppe-linked migration cases">{rows.map(row=>{const incoming=Number(row.incoming_percent);const remaining=Number(row.remaining_percent);return <button type="button" key={row.case_id} className={selected.case_id===row.case_id?'active':''} aria-pressed={selected.case_id===row.case_id} onClick={()=>setSelectedId(row.case_id)}><span><b>{row.region}</b><small>{row.period}</small></span><i><em style={{width:`${incoming}%`}}/><em style={{width:`${remaining}%`}}/></i><strong>{row.display_anchor}</strong></button>;})}</div><section aria-live="polite"><header><div><span>{selected.incoming_label}</span><h5>{selected.region}</h5></div><strong>{selected.display_anchor}</strong></header><div><article><span>What the genomes show</span><p>{selected.comparison}</p></article><article><span>Language is a separate inference</span><p>{selected.language_evidence}</p></article></div></section></div>}
