'use client';

import { useEffect, useMemo, useState } from 'react';
import { fetchClientText } from './lib/clientAsset';

type StageRow={stage_id:string;stage_order:string;year_start:string;year_end:string;display_period:string;stage_title:string;evidence:string;capability:string;military_reach:string;quantitative_anchor:string;source_keys:string;limits:string};
const dataUrl='/data/steppe/20260831-mobility1/horse-mobility-stages.csv';
function parseCSV<T>(text:string):T[]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const[headers,...body]=rows;return body.map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])) as T);}
export default function SteppeHorseMobility(){const[rows,setRows]=useState<StageRow[]>([]);const[state,setState]=useState<'loading'|'ready'|'error'>('loading');const[error,setError]=useState('');const[attempt,setAttempt]=useState(0);const[selectedId,setSelectedId]=useState('botai_husbandry');useEffect(()=>{const controller=new AbortController();fetchClientText(dataUrl,{signal:controller.signal,label:'horse mobility stages'}).then(text=>{const parsed=parseCSV<StageRow>(text);if(parsed.length!==4||parsed.some(row=>!row.stage_id||!row.stage_title||!row.evidence||!row.capability||!row.source_keys))throw new Error('The horse mobility evidence used an incompatible data contract.');setRows(parsed);setState('ready');}).catch(problem=>{if(controller.signal.aborted)return;setError(problem instanceof Error?problem.message:'The evidence could not be loaded.');setState('error');});return()=>controller.abort();},[attempt]);const selected=useMemo(()=>rows.find(row=>row.stage_id===selectedId)??rows[0],[rows,selectedId]);const retry=()=>{setRows([]);setError('');setState('loading');setAttempt(value=>value+1);};if(state!=='ready'||!selected)return <div className={`data-state steppe-mobility-state ${state}`} role={state==='error'?'alert':'status'}><b>{state==='error'?'The horse-mobility evidence did not load':'Loading horse-mobility stages…'}</b><span>{state==='error'?error:'husbandry · breeding · chariots · cavalry'}</span>{state==='error'&&<button type="button" onClick={retry}>Retry evidence</button>}</div>;return <div className="steppe-mobility-chart"><nav aria-label="Choose a horse-mobility stage">{rows.map(row=><button type="button" key={row.stage_id} className={selected.stage_id===row.stage_id?'active':''} aria-pressed={selected.stage_id===row.stage_id} onClick={()=>setSelectedId(row.stage_id)}><span>{row.display_period}</span><b>{row.stage_title}</b></button>)}</nav><section aria-live="polite"><header><div><span>{selected.display_period}</span><h5>{selected.stage_title}</h5></div><strong>{selected.quantitative_anchor}</strong></header><div className="steppe-mobility-lanes"><article><span>Evidence</span><p>{selected.evidence}</p></article><article><span>New capability</span><p>{selected.capability}</p></article><article><span>Military limit</span><p>{selected.military_reach}</p></article></div></section></div>}
