import type { Metadata } from 'next';
import EvidencePanel from '../components/EvidencePanel';
import HistoryPageShell from '../components/HistoryPageShell';
import QinMobilizingSystem from '../QinMobilizingSystem';

export const metadata:Metadata={title:'Qin and Han China',description:'How interstate competition, registration, rewards, reporting, and logistics built a durable imperial repertoire.',openGraph:{title:'Qin and Han China — How Everything Evolved',description:'The last conquests took nine years. The mobilizing system took generations.',images:[]},twitter:{card:'summary',title:'Qin and Han China — How Everything Evolved',description:'A source-bounded visual argument about administration before unification.',images:[]}};

const pending=[
  ['02','Standardization made a larger territory legible','Weights, measures, scripts, roads, and legal categories did not make every locality identical. This insight will compare what the center standardized, what people actually used, and where the evidence stops.'],
  ['03','Grain and infrastructure converted ecology into logistics','Canals, roads, frontier works, granaries, and conscript labor connected environmental management to military reach. This insight will keep excavated records separate from transmitted headline totals.'],
  ['04','Han rule combined commanderies, kingdoms, and frontier bargains','The Han did not simply preserve one Qin template. This insight will show direct administration, delegated kingdoms, elite bargains, and frontier arrangements as changing portfolios.'],
  ['05','Collapse broke regimes—not the imperial repertoire','Qin fell quickly and Han rule fractured, but later reunifiers reused and redesigned parts of the imperial repertoire. This insight will distinguish institutional descent, revival, and retrospective memory.'],
];

export default function QinHanPage(){return <HistoryPageShell
  title="Qin and Han China"
  eyebrow="475 BCE–220 CE · war · administration · empire"
  standfirst="The last conquests took nine years. The mobilizing system took generations: rival states learned to count households, assign obligations, reward service, make counties report, and move supplies."
  status="draft"
  progress="1 of 5 insights live"
  published="August 2026"
  introduction={<><p>Qin&apos;s victory in 221 BCE can look abrupt when history is told as six conquests and one First Emperor. The institutions behind it were not. Across the Warring States, governments competed to register households, connect people to taxes and service, redirect rank and land, discipline local offices, and supply armies across widening distances.</p><p>Qin is the best-documented winner, not the only reforming state. Its surviving laws, letters, and county archive reveal capabilities that transmitted doctrine often compresses into one reformer&apos;s program. The documents also reveal shortages, uneven control, and the continuing difficulty of ruling new territory.</p><p>This opening argument therefore compares two clocks. Five capacities developed across generations; six rival courts fell between 230 and 221 BCE. The visual does not infer army totals, casualty counts, continuous borders, or one numerical “state capacity” score.</p></>}
  insightLabels={['Qin won by making mobilization administrative','Standardization made a larger territory legible','Grain and infrastructure converted ecology into logistics','Han rule combined commanderies, kingdoms, and frontier bargains','Collapse broke regimes—not the imperial repertoire']}
  methods={<><p>The five capacities are a causal synthesis, not five dated inventions. Warring States competition, household registration, ranked rewards, county reporting, and assigned transfers are retained as separate evidence windows because their sources and dates differ.</p><p>Brian Lander&apos;s peer-reviewed synthesis anchors the gradual, interstate character of reform and the Liye county archive. Chun Fung Tong&apos;s documentary study anchors the 224–223 BCE soldier letter, 220 BCE armament transfers, horizontal and vertical logistics, and recorded shortages. The received <i>Book of Lord Shang</i> is treated as layered fourth–third-century doctrine rather than one verbatim decree.</p><p>The six conquest dates follow the retrospective Qin annals in Sima Qian&apos;s <i>Shiji</i>. They mark the political removal of rival courts, not annual territorial boundaries or complete local pacification. Zhao&apos;s main court fell in 228 BCE while Dai survived to 222 BCE.</p><p>Ancient headline army sizes, casualty totals, and transport-loss percentages are excluded. No population series, territory series, combat-power estimate, or state-capacity index is reconstructed.</p><EvidencePanel page="qin-han"/></>}
>
  <section className="insight qin-mobilization-insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">Competition selected for states able to count households, assign obligations, reward service, make counties report, and move supplies.</p><h3>Victory was administrative before it was territorial</h3><p>The final sequence was fast: Han in 230 BCE, Zhao&apos;s main court in 228, Wei in 225, Chu in 223, Yan and Dai in 222, and Qi in 221. But a list of fallen courts hides the system that made repeated campaigning possible.</p><p>Household registers connected individuals to land, taxes, corvée, and military eligibility. Ranked rewards made farming and dangerous service routes to status. County bureaus recorded people, tools, boats, embankments, debts, and obligations. Transfers then moved soldiers and armaments across commanderies—imperfectly and with documented shortages.</p><p>That was not a uniquely Qin discovery. Rival states also reformed under pressure. Qin&apos;s distinction is that it won, expanded its administrative categories into new territories, and left unusually rich evidence of how the machinery worked and failed.</p><a className="source-link" href="https://doi.org/10.1017/jch.2022.19">Read the political-ecology synthesis ↗</a></div><div className="viz-card qin-mobilization-viz"><div className="viz-title"><div><span>Five capacities + six political endpoints</span><h4>What made conquest repeatable?</h4></div><small>453–208 BCE evidence windows · no state-capacity score</small></div><QinMobilizingSystem/><p className="viz-note"><b>Method:</b> Select a capacity or conquest endpoint to inspect its evidence, interpretation, and limit. The chain is an argument about linked functions—not a measured sequence, annual series, or proof of complete control.</p></div></section>
  {pending.map(([number,title,copy])=><section className="insight insight-placeholder" key={number}><div className="insight-copy"><span className="insight-number">{number}</span><p className="claim">Research milestone</p><h3>{title}</h3><p>{copy}</p></div><div className="viz-card placeholder-card"><span>Evidence reconstruction in progress</span><h4>{title}</h4><p>This panel will publish only after its source registry, downloadable dataset, inference limits, production checks, and mobile interaction are complete.</p></div></section>)}
</HistoryPageShell>}
