import type { Metadata } from 'next';
import EvidencePanel from '../components/EvidencePanel';
import HistoryPageShell from '../components/HistoryPageShell';
import QinMobilizingSystem from '../QinMobilizingSystem';
import QinStandardizationPractice from '../QinStandardizationPractice';
import QinLogisticsEcology from '../QinLogisticsEcology';

export const metadata:Metadata={title:'Qin and Han China',description:'How interstate competition, registration, rewards, reporting, and logistics built a durable imperial repertoire.',openGraph:{title:'Qin and Han China — How Everything Evolved',description:'The last conquests took nine years. The mobilizing system took generations.',images:[]},twitter:{card:'summary',title:'Qin and Han China — How Everything Evolved',description:'A source-bounded visual argument about administration before unification.',images:[]}};

const pending=[
  ['04','Han rule combined commanderies, kingdoms, and frontier bargains','The Han did not simply preserve one Qin template. This insight will show direct administration, delegated kingdoms, elite bargains, and frontier arrangements as changing portfolios.'],
  ['05','Collapse broke regimes—not the imperial repertoire','Qin fell quickly and Han rule fractured, but later reunifiers reused and redesigned parts of the imperial repertoire. This insight will distinguish institutional descent, revival, and retrospective memory.'],
];

export default function QinHanPage(){return <HistoryPageShell
  title="Qin and Han China"
  eyebrow="475 BCE–220 CE · war · administration · empire"
  standfirst="The last conquests took nine years. The mobilizing system took generations: rival states learned to count households, assign obligations, reward service, make counties report, and move supplies."
  status="draft"
  progress="3 of 5 insights live"
  published="August 2026"
  introduction={<><p>Qin&apos;s victory in 221 BCE can look abrupt when history is told as six conquests and one First Emperor. The institutions behind it were not. Across the Warring States, governments competed to register households, connect people to taxes and service, redirect rank and land, discipline local offices, and supply armies across widening distances.</p><p>Qin is the best-documented winner, not the only reforming state. Its surviving laws, letters, and county archive reveal capabilities that transmitted doctrine often compresses into one reformer&apos;s program. The documents also reveal shortages, uneven control, and the continuing difficulty of ruling new territory.</p><p>This opening argument therefore compares two clocks. Five capacities developed across generations; six rival courts fell between 230 and 221 BCE. The visual does not infer army totals, casualty counts, continuous borders, or one numerical “state capacity” score.</p></>}
  insightLabels={['Qin won by making mobilization administrative','Standardization made a larger territory legible','Grain and infrastructure converted ecology into logistics','Han rule combined commanderies, kingdoms, and frontier bargains','Collapse broke regimes—not the imperial repertoire']}
  methods={<><p>The five capacities are a causal synthesis, not five dated inventions. Warring States competition, household registration, ranked rewards, county reporting, and assigned transfers are retained as separate evidence windows because their sources and dates differ.</p><p>Brian Lander&apos;s peer-reviewed synthesis anchors the gradual, interstate character of reform and the Liye county archive. Chun Fung Tong&apos;s documentary study anchors the 224–223 BCE soldier letter, 220 BCE armament transfers, horizontal and vertical logistics, and recorded shortages. The received <i>Book of Lord Shang</i> is treated as layered fourth–third-century doctrine rather than one verbatim decree.</p><p>The six conquest dates follow the retrospective Qin annals in Sima Qian&apos;s <i>Shiji</i>. They mark the political removal of rival courts, not annual territorial boundaries or complete local pacification. Zhao&apos;s main court fell in 228 BCE while Dai survived to 222 BCE.</p><p>The standardization comparison keeps six unlike evidence windows separate. Staack&apos;s twenty-five upward reports and twenty-two grain tallies are bounded Qianling samples. Their row-specific proportions are not averaged. Škrabal&apos;s scoop is one object biography; Galambos&apos;s epigraphic chronology challenges a sudden script shift without denying official written norms.</p><p>The logistics comparison keeps productive irrigation, corridor engineering, route records, ration reporting, storage archaeology, recurrent maintenance, and retrospective labor criticism in different evidence classes. Its shared timeline is an index to dated windows, not an annual infrastructure or throughput series. The Western Han Capital Granary is not used to back-calculate a missing Qin store.</p><p>Ancient headline army sizes, casualty totals, megaproject workforce counts, and transport-loss percentages are excluded. No population series, territory series, combat-power estimate, literacy rate, empire-wide compliance rate, annual grain flow, labor share, or state-capacity index is reconstructed.</p><EvidencePanel page="qin-han"/></>}
>
  <section className="insight qin-mobilization-insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">Competition selected for states able to count households, assign obligations, reward service, make counties report, and move supplies.</p><h3>Victory was administrative before it was territorial</h3><p>The final sequence was fast: Han in 230 BCE, Zhao&apos;s main court in 228, Wei in 225, Chu in 223, Yan and Dai in 222, and Qi in 221. But a list of fallen courts hides the system that made repeated campaigning possible.</p><p>Household registers connected individuals to land, taxes, corvée, and military eligibility. Ranked rewards made farming and dangerous service routes to status. County bureaus recorded people, tools, boats, embankments, debts, and obligations. Transfers then moved soldiers and armaments across commanderies—imperfectly and with documented shortages.</p><p>That was not a uniquely Qin discovery. Rival states also reformed under pressure. Qin&apos;s distinction is that it won, expanded its administrative categories into new territories, and left unusually rich evidence of how the machinery worked and failed.</p><a className="source-link" href="https://doi.org/10.1017/jch.2022.19">Read the political-ecology synthesis ↗</a></div><div className="viz-card qin-mobilization-viz"><div className="viz-title"><div><span>Five capacities + six political endpoints</span><h4>What made conquest repeatable?</h4></div><small>453–208 BCE evidence windows · no state-capacity score</small></div><QinMobilizingSystem/><p className="viz-note"><b>Method:</b> Select a capacity or conquest endpoint to inspect its evidence, interpretation, and limit. The chain is an argument about linked functions—not a measured sequence, annual series, or proof of complete control.</p></div></section>
  <section className="insight qin-standard-insight"><div className="insight-copy"><span className="insight-number">02</span><p className="claim">Qin made administration more mutually legible by defining shared objects, scripts, dimensions, and record fields—not by making every local practice identical.</p><h3>A standard was an interface, not sameness</h3><p>The 221 BCE measure edict did not require every useful object to be melted down. One palace scoop already in service was certified with the First Emperor&apos;s inscription, then re-inscribed and supplemented under the Second Emperor. Standards traveled through reusable objects and copyable templates.</p><p>Official script worked similarly. Qin small-seal writing became an epigraphic norm, but surviving inscriptions do not show one instantaneous shift into a uniform hand. “Unified writing” is a later political story about convergence—not evidence that spoken languages or every scribal practice became one.</p><p>Local documents show what administrators actually prioritized. In twenty-five Qianling reports, every tablet stayed close to the common 23 cm length, but none met the ordinance&apos;s width tolerance and fourteen exceeded the character limit. Grain tallies preserved shared content more consistently than one visual layout.</p><a className="source-link" href="https://doi.org/10.1017/S0041977X23000228">Read the document comparison ↗</a></div><div className="viz-card qin-standard-viz"><div className="viz-title"><div><span>Six norm-to-practice windows</span><h4>How uniform was standardization?</h4></div><small>222–208 BCE local archive · no empire-wide compliance rate</small></div><QinStandardizationPractice/><p className="viz-note"><b>Method:</b> Select one object, script, tablet, or tally window. Proportions apply only to the published sample in that row; qualitative windows and quantitative rows are never averaged into one score.</p></div></section>
  <section className="insight qin-logistics-insight"><div className="insight-copy"><span className="insight-number">03</span><p className="claim">Imperial logistics was not one canal, road, wall, or granary. It was a maintained loop that turned water, fields, grain, records, stores, transport, and labor into reach.</p><h3>Infrastructure worked as an ecology</h3><p>Zhengguo and Dujiangyan enlarged productive landscapes in Qin&apos;s core and a conquered region. The Ling Canal then shows the other side of hydraulic power: a short engineered crossing could join the much longer natural corridors of two drainage basins.</p><p>Movement still depended on information and storage. A late-Qin route record broke a grain corridor into measured legs. A Qianling order required granaries and communes to report whether rations were sufficient for soldiers and hard laborers. Under Han, storage and waterways into the capital expanded further.</p><p>None of this maintained itself. Early Han law and documents show officials relying on local communities for hydraulic decisions and recurrent labor. The same machinery could also concentrate labor on walls, roads, palaces, and tombs so aggressively that later observers made exploitation central to Qin&apos;s fall.</p><a className="source-link" href="https://doi.org/10.1163/24689246-20240008">Read the water-management evidence ↗</a></div><div className="viz-card qin-logistics-viz"><div className="viz-title"><div><span>Eight source-bounded logistics windows</span><h4>How did grain become imperial reach?</h4></div><small>316 BCE–25 CE evidence windows · no annual throughput or labor total</small></div><QinLogisticsEcology/><p className="viz-note"><b>Method:</b> Select one productive, storage, transport, maintenance, or extraction window. Dates locate unlike evidence on a common axis; bars do not measure output, cost, workforce, or importance.</p></div></section>
  {pending.map(([number,title,copy])=><section className="insight insight-placeholder" key={number}><div className="insight-copy"><span className="insight-number">{number}</span><p className="claim">Research milestone</p><h3>{title}</h3><p>{copy}</p></div><div className="viz-card placeholder-card"><span>Evidence reconstruction in progress</span><h4>{title}</h4><p>This panel will publish only after its source registry, downloadable dataset, inference limits, production checks, and mobile interaction are complete.</p></div></section>)}
</HistoryPageShell>}
