import type { Metadata } from 'next';
import AlphaChronology from '../components/AlphaChronology';
import AlphaPendingInsight from '../components/AlphaPendingInsight';
import ChartFooter from '../components/ChartFooter';
import HistoryPageShell from '../components/HistoryPageShell';
import InventionPayoff from '../InventionPayoff';

export const metadata:Metadata={title:'The Great Divergence',description:'Five visual arguments about wages, energy, ecology, institutions, empire, and the timing of divergence.',openGraph:{title:'The Great Divergence — How Everything Evolved',description:'Northwestern Europe’s urban wage advantage was visible before factories dominated output.',images:[]},twitter:{card:'summary',title:'The Great Divergence — How Everything Evolved',description:'Northwestern Europe’s urban wage advantage was visible before factories dominated output.',images:[]}};
const labels=['Northwestern Europe’s urban wage advantage was visible before factories dominated output','High wages and cheap energy made labor-saving invention unusually profitable','Coal and New World resources loosened land constraints','Institutions mattered through particular markets and state capacities—not one score','The divergence was regional and late, not an eternal West–East gap'];
const events=[
  {year:1,displayYear:'1700–49',label:'London · 4.16',detail:'Modeled full-year building-laborer family earnings were 4.16 times a bare-bones family basket.',kind:'subsistence ratio'},
  {year:2,displayYear:'1750–99',label:'London · 3.51',detail:'The London ratio remained well above one in the second half of the century.',kind:'subsistence ratio'},
  {year:3,displayYear:'1700–49',label:'Amsterdam · 4.20',detail:'Amsterdam’s reconstruction was slightly above London’s in the first half-century.',kind:'subsistence ratio'},
  {year:4,displayYear:'1750–99',label:'Amsterdam · 3.77',detail:'The Amsterdam ratio also remained above three in the second half-century.',kind:'subsistence ratio'},
  {year:5,displayYear:'1700–99',label:'Beijing · 1.25 → 1.04',detail:'Beijing’s two half-century estimates sat much closer to the bare-bones threshold.',kind:'two reconstructed periods'},
];
export default function GreatDivergencePage(){return <HistoryPageShell title="The Great Divergence" eyebrow="1500–1800 CE" standfirst="Before industrialization transformed output, wages, energy, ecology, states, and empire had already created unequal incentives and constraints." status="draft" progress="2 of 5 insights live" published="August 2026" insightLabels={labels}
  introduction={<><p>The Great Divergence was not one date or one cause. It was a widening set of regional differences in wages, energy prices, land constraints, institutions, imperial resources, and eventually mechanized production.</p><p>The five claims begin with comparable urban wage baskets, then test the mechanisms linking those differences to invention, coal, overseas resources, institutions, and timing.</p></>}
  methods={<><p>The opening comparison reproduces Allen, Murphy, and Schneider’s building-laborer subsistence ratios. A ratio of one means modeled full-time family earnings just covered the authors’ bare-bones family basket.</p><p>These are city and occupational reconstructions with assumptions about workdays, family structure, prices, and consumption. They are not GDP, median income, welfare for every worker, or proof of one divergence date.</p></>}>
  <section className="insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">A worker-price reconstruction places London and Amsterdam far above Beijing before 1800.</p><h3>{labels[0]}</h3><p>In both halves of the eighteenth century, reconstructed building-laborer earnings in London and Amsterdam bought more than three bare-bones family baskets. Beijing’s estimate remained close to one.</p><p>The gap is informative because the method makes cities comparable. It remains a modeled urban-sector comparison, not a complete ranking of European and Chinese living standards.</p></div><div className="viz-card"><div className="viz-title"><div><span>Urban building laborers · reconstructed subsistence ratios</span><h4>{labels[0]}</h4></div><small>one equals a bare-bones family basket</small></div><AlphaChronology title="The wage gap preceded factory dominance" subtitle="Two half-century estimates per city" events={events}/><ChartFooter source="Allen, Murphy, and Schneider (2012)" note="Ratios assume full-year employment and a standardized bare-bones family basket. They describe selected cities and workers, not entire economies." dataHref="/data/great-divergence/20260831-alpha1/urban-subsistence-ratios.csv"/></div></section>
  <section className="insight"><div className="insight-copy"><span className="insight-number">02</span><p className="claim">In one influential adoption calculation, the same machine paid handsomely in England and lost money in India.</p><h3>{labels[1]}</h3><p>A spinning jenny substituted a small machine for many hours of hand spinning. Allen estimates that buying one returned 38% in England, 2.5% in France, and −5.2% in India under the same central productivity and utilization assumptions.</p><p>The result isolates an incentive: labor-saving machinery was more attractive where labor was expensive relative to capital. It does not make factor prices the only cause of industrialization.</p></div><div className="viz-card"><div className="viz-title"><div><span>Spinning jenny · modeled private return</span><h4>{labels[1]}</h4></div><small>central adoption calculation</small></div><InventionPayoff/><ChartFooter source="Robert C. Allen (2009)" note="Modeled returns depend on wages, machine prices, productivity, utilization, maintenance, and a ten-year machine life. The high-wage explanation is influential and debated." dataHref="/data/great-divergence/20260901-incentives1/spinning-jenny-returns.csv"/></div></section>
  <AlphaPendingInsight number="03" title={labels[2]} question="How much land, timber, fiber, food, and energy did accessible coal and overseas ecologies effectively add?"/>
  <AlphaPendingInsight number="04" title={labels[3]} question="Which finance, property, taxation, warfare, and market institutions changed incentives—and where do simple institutional scores fail?"/>
  <AlphaPendingInsight number="05" title={labels[4]} question="How do regional comparisons replace an old story of timeless European superiority with a late, uneven divergence?"/>
  </HistoryPageShell>}
