import type { Metadata } from 'next';
import AlphaChronology from '../components/AlphaChronology';
import AlphaPendingInsight from '../components/AlphaPendingInsight';
import ChartFooter from '../components/ChartFooter';
import HistoryPageShell from '../components/HistoryPageShell';
import FortressAdaptation from '../FortressAdaptation';

export const metadata:Metadata={title:'Gunpowder Empires',description:'Five visual arguments about firearms, fortification, armies, drill, and fiscal scale.',openGraph:{title:'Gunpowder Empires — How Everything Evolved',description:'Gunpowder warfare rewarded fiscal scale more than possession of cannon.',images:[]},twitter:{card:'summary',title:'Gunpowder Empires — How Everything Evolved',description:'Gunpowder warfare rewarded fiscal scale more than possession of cannon.',images:[]}};
const labels=['Gunpowder warfare rewarded fiscal scale more than possession of cannon','Cannon made walls evolve—not disappear','Firearms worked with cavalry and logistics—not instead of them','Drill converted guns into repeatable battlefield fire','Gunpowder states remained politically diverse'];
const events=[
  {year:1,displayYear:'1470s',label:'1× baseline',detail:'The comparison normalizes the largest armies of the 1470s to one.',kind:'comparison baseline'},
  {year:2,displayYear:'England',label:'2.8×',detail:'The largest English armies of the seventeenth century were 2.8 times the 1470s comparison.',kind:'published multiplier'},
  {year:3,displayYear:'France',label:'3.8×',detail:'The largest French armies were 3.8 times the 1470s comparison.',kind:'published multiplier'},
  {year:4,displayYear:'Spain',label:'15×',detail:'The largest Spanish armies were fifteen times the 1470s comparison.',kind:'published multiplier'},
  {year:5,displayYear:'1590s',label:'4.5× cost',detail:'Spain’s annual war cost was 4.5 times its level in the 1540s.',kind:'different measure and baseline'},
];
export default function GunpowderEmpiresPage(){return <HistoryPageShell title="Gunpowder Empires" eyebrow="1450–1800 CE" standfirst="Cannon changed walls; muskets changed infantry; paying for both changed states." status="draft" progress="2 of 5 insights live" published="August 2026" insightLabels={labels}
  introduction={<><p>Gunpowder did not hand victory to everyone who acquired it. The durable advantage came from building fortifications, training formations, maintaining supply, and repeatedly paying large forces.</p><p>The five claims follow that system from fiscal scale to walls, combined arms, drill, and the political diversity of the states that used it.</p></>}
  methods={<><p>The opening visual reproduces four multipliers reported by Kenkel and Paine from military-history estimates. It keeps the army and war-cost comparisons separate.</p><p>These European comparisons demonstrate rising scale and cost, not a global census of Ottoman, Safavid, Mughal, or European forces and not a gunpowder-only causal estimate.</p></>}>
  <section className="insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">The expensive part of the gunpowder revolution was sustaining the system around the weapon.</p><h3>{labels[0]}</h3><p>Cannon-resistant fortresses and professional infantry pushed armies and war budgets upward. Spain’s largest-army multiplier dwarfed England’s and France’s in this published comparison.</p><p>The values show scale, not battlefield quality. They also compare European states rather than all early modern gunpowder powers.</p></div><div className="viz-card"><div className="viz-title"><div><span>European military scale · published multipliers</span><h4>{labels[0]}</h4></div><small>army and cost measures remain separate</small></div><AlphaChronology title="Gunpowder warfare became a fiscal contest" subtitle="Largest-army and annual-cost multipliers" events={events}/><ChartFooter source="Kenkel and Paine (2023)" note="Army multipliers compare seventeenth-century maxima with the 1470s. Spain’s war-cost multiplier compares the 1590s with the 1540s and is not added to the army series." dataHref="/data/gunpowder-empires/20260831-alpha1/military-scale-multipliers.csv"/></div></section>
  <section className="insight"><div className="insight-copy"><span className="insight-number">02</span><p className="claim">The answer to cannon was more engineering.</p><h3>{labels[1]}</h3><p>Artillery punished tall stone curtains. Fortification responded with earth-backed mass, lower profiles, angled bastions, and layered approaches.</p><p>Those choices changed the contest instead of ending it. Select an adaptation to see the artillery problem it answered—and what the evidence cannot measure.</p></div><div className="viz-card"><div className="viz-title"><div><span>Artillery problem → defensive response</span><h4>{labels[1]}</h4></div><small>four design mechanisms · no fortress score</small></div><FortressAdaptation/><ChartFooter source="Peter Lorge (2008); Geoffrey Parker (2004); UNESCO Venetian Works of Defence" note="These are design mechanisms documented in scholarly synthesis and surviving fortifications. They do not produce universal dimensions, breach times, costs, or a single fortress-strength score." dataHref="/data/gunpowder-empires/20260901-fortress1/artillery-fortress-adaptations.csv"/></div></section>
  <AlphaPendingInsight number="03" title={labels[2]} question="How did Ottoman, Safavid, Mughal, and European armies combine guns with horses, siege trains, transport, and provisioning?"/>
  <AlphaPendingInsight number="04" title={labels[3]} question="When did volley fire, unit rotation, and standardized drill make individual firearms into an organizational weapon?"/>
  <AlphaPendingInsight number="05" title={labels[4]} question="Why did similar weapons coexist with empires, republics, composite monarchies, and different fiscal bargains?"/>
  </HistoryPageShell>}
