import type { Metadata } from 'next';
import AlphaChronology from '../components/AlphaChronology';
import AlphaPendingInsight from '../components/AlphaPendingInsight';
import ChartFooter from '../components/ChartFooter';
import HistoryPageShell from '../components/HistoryPageShell';
import SilkRouteRerouting from '../SilkRouteRerouting';

export const metadata:Metadata={title:'Silk Roads',description:'Five visual arguments about oasis economies, shifting routes, merchants, religions, and maritime exchange.',openGraph:{title:'Silk Roads — How Everything Evolved',description:'At Turfan, textiles, grain, and coins all functioned as money.',images:[]},twitter:{card:'summary',title:'Silk Roads — How Everything Evolved',description:'At Turfan, textiles, grain, and coins all functioned as money.',images:[]}};
const labels=['At Turfan, textiles, grain, and coins all functioned as money','The Silk Roads survived by rerouting around political and ecological bottlenecks','Sogdian merchants connected states without belonging to one empire','Religions traveled by translation and institutions—not cargo alone','Sea routes carried more bulk than overland caravans'];
const events=[
  {year:1,displayYear:'273–796 CE',label:'Textiles',detail:'Bolts and pieces of cloth served as payment, stores of value, and units in documented local transactions.',kind:'documented money'},
  {year:2,displayYear:'273–796 CE',label:'Grain',detail:'Grain functioned as another payment medium in the oasis economy.',kind:'documented money'},
  {year:3,displayYear:'273–796 CE',label:'Coins',detail:'Coins circulated alongside commodity monies rather than replacing them everywhere.',kind:'documented money'},
];
export default function SilkRoadsPage(){return <HistoryPageShell title="Silk Roads" eyebrow="200 BCE–1500 CE" standfirst="Long-distance exchange emerged from many local markets, routes, languages, and political systems." status="draft" progress="2 of 5 insights live" published="August 2026" insightLabels={labels}
  introduction={<><p>There was no single road running continuously from Rome to China. Trans-Eurasian exchange depended on changing chains of oasis towns, pastoral routes, imperial corridors, mountain passes, and sea lanes.</p><p>The five claims begin with ordinary transactions at Turfan, then ask how routes shifted, merchants crossed states, religions moved through translation, and maritime exchange complemented overland traffic.</p></>}
  methods={<><p>The first visual follows Hansen and Rong’s study of documents preserved around Turfan. Their 273–796 CE evidence shows textiles, grain, and coins all functioning as money; it does not measure their market shares or the value of total trade.</p><p>The second visual combines three route mechanisms from UNESCO, Encyclopaedia Iranica, and Valerie Hansen’s archaeological synthesis. It compares network structure and reasons for rerouting; it does not reconstruct annual paths, traffic shares, travel times, hydrology, security, or one complete transcontinental itinerary.</p><p>Turfan was one important northern-route oasis, not a representative sample of every Silk Road economy. Local payments do not prove that the same instruments circulated end to end.</p></>}>
  <section className="insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">At Turfan, textiles, grain, and coins all functioned as money.</p><h3>{labels[0]}</h3><p>The documents preserved in Turfan’s dry climate show an economy more ordinary—and more interesting—than caravans carrying luxury silk from one empire to another. Residents paid with cloth, grain, and coins across more than five centuries.</p><p>Long-distance exchange rested on local institutions that could price goods, settle obligations, recycle materials, and bridge currencies. The “road” worked because oasis economies worked.</p></div><div className="viz-card"><div className="viz-title"><div><span>Turfan oasis · documentary evidence</span><h4>{labels[0]}</h4></div><small>273–796 CE · three coexisting monies</small></div><AlphaChronology title="One oasis economy used three kinds of money" subtitle="Contracts and excavated documents" events={events}/><ChartFooter source="Hansen & Rong (2013)" note="The evidence shows coexistence, not market shares or total trade values. Turfan is one oasis and does not establish a universal Silk Road currency system." dataHref="/data/silk-roads/20260831-alpha1/turfan-money-forms.csv"/></div></section>
  <section className="insight silk-routes-insight"><div className="insight-copy"><span className="insight-number">02</span><p className="claim">A durable network did not need a permanent path. It needed alternate links.</p><h3>{labels[1]}</h3><p>The Silk Roads crossed territory where deserts blocked direct travel, rivers moved or dried, and rival states made some corridors dangerous. Their strength was not one engineered highway; it was the ability to fork, detour, and reconnect through viable nodes.</p><p>The Taklamakan routes split around the desert. Roman merchants could seek northern alternatives to Parthian territory. Central Asian river corridors changed with water. Most exchange moved through local legs and intermediaries rather than one end-to-end caravan.</p><p>That redundancy made the network persistent even while every particular route remained contingent.</p></div><div className="viz-card silk-routes-viz"><div className="viz-title"><div><span>Four bottlenecks · four rerouting responses</span><h4>{labels[1]}</h4></div></div><SilkRouteRerouting/><ChartFooter source="UNESCO Silk Roads; Encyclopaedia Iranica; Hansen (2012)" note="The cases identify network structure and rerouting mechanisms. They do not estimate annual paths, traffic shares, travel times, river levels, safety, or one complete itinerary." dataHref="/data/silk-roads/20260831-routes1/silk-route-rerouting.csv"/></div></section>
  <AlphaPendingInsight number="03" title={labels[2]} question="Which Sogdian letters, contracts, colonies, and multilingual networks show merchants coordinating across political borders?"/>
  <AlphaPendingInsight number="04" title={labels[3]} question="How did monasteries, translators, pilgrims, scripts, and patronage move Buddhism, Christianity, Islam, and other traditions?"/>
  <AlphaPendingInsight number="05" title={labels[4]} question="Which goods moved overland, which moved by sea, and where can transport constraints support a bounded scale comparison?"/>
  </HistoryPageShell>}
