import type { Metadata } from 'next';
import HistoryPageShell from '../components/HistoryPageShell';
import EvidencePanel from '../components/EvidencePanel';
import MilitaryCapacityChart from '../MilitaryCapacityChart';
import RomanFiscalChart from '../RomanFiscalChart';
import RomanMap from '../RomanMap';
import WesternCollapseChart from '../WesternCollapseChart';

export const metadata: Metadata = {
  title: 'Rome',
  description: 'An evidence-led visual history of how Rome expanded, mobilized power, financed empire, changed, and endured.',
  openGraph: {
    title: 'Rome — How Everything Evolved',
    description: 'A visual history of Roman territory, military capacity, imperial finance, and the western court’s contraction.',
    images: [],
  },
  twitter: { card: 'summary', title: 'Rome — How Everything Evolved', description: 'A visual history of Roman territory, military capacity, imperial finance, and the western court’s contraction.', images: [] },
};

export default function RomePage() {
  return (
    <HistoryPageShell
      title="Rome"
      eyebrow="Iron Age · Mediterranean · state capacity"
      standfirst="A city on the Tiber brought most Mediterranean coastlands under one state—and remained a continental-scale power for centuries."
      status="draft"
      progress="4 of 5 insights live"
      published="August 2026"
      insightHeading={<>See the empire.<br />Then see what sustained it.</>}
      introduction={<><p>Rome’s history is almost a millennium of expansion, consolidation, division, and survival. Seeing the whole arc matters: the Republic’s Italian coalition, the Mediterranean empire, the Tetrarchy’s four courts, the loss of the western provinces, and the Roman state that continued in the East.</p><p>We begin with four basic questions. Where was Rome? How could it keep replacing armies? How did it pay for them? And what happened when the western court’s taxable territory contracted faster than its military obligations?</p><p>Ancient numbers are fragmentary. The visuals distinguish dated observations, unlike kinds of military totals, regional tax rates, modern budget reconstructions, and fiscal-equivalent models rather than smoothing them into false precision.</p></>}
      methods={<><p>This is a working page. Four of five planned insights are live. Territorial geometry comes from the Seshat Global History Databank’s Cliopatria dataset and is simplified for web display over a Natural Earth physical basemap. Annual playback does not imply annual observations: each sourced boundary persists until the next dated geometry.</p><p>The military chart separates unlike evidence rather than manufacturing uniformity. Seven Roman anchors are shown in four short, definition-consistent segments; blank years are evidence gaps, not zeroes. Rival dots are reported or reconstructed forces from particular campaigns. The only fifth-century Roman total shown is explicitly eastern, and its plotted date foregrounds the scholarly dispute over when the eastern Notitia Dignitatum describes.</p><p>The fiscal chart reproduces Duncan-Jones’s published central-budget scenarios as reported by Mattingly. Shares may be compared within a snapshot; nominal totals across dates may not. Tax and pay observations retain their distinct bases, places, destinations, and units. No surviving evidence supports a single empire-wide tax rate or an annual Roman revenue series.</p><p>The collapse timeline is a chronology, not a causal score. The African bars reproduce Heather’s fiscal-equivalent model using Elton’s maintenance costs; they are neither an observed headcount decline nor a continuous western army series. Valentinian’s 445 law supports a one-eighth assessment only for its two named surviving provinces. The chart treats 476 as the end of the western court, not the end of the Roman state.</p><EvidencePanel page="rome" /></>}
    >
      <section className="insight map-insight">
        <div className="insight-copy"><span className="insight-number">01</span><p className="claim">At its height, Rome governed territory across Europe, North Africa, and western Asia.</p><h3>From one city to three continents</h3><p>Press play to follow more than nine centuries of Roman political geography. The map begins with a small state in central Italy, reaches its greatest extent under Trajan, then changes meaning: one empire with four courts, two imperial administrations, and finally an eastern empire without a western emperor.</p><p>The important change is not only size. Watch the political form change while the Roman name endures. Hover or select any polity to inspect the exact dated reconstruction used in each annual frame.</p></div>
        <RomanMap />
      </section>
      <section className="insight manpower-insight">
        <div className="insight-copy"><span className="insight-number">02</span><p className="claim">Rome could replace large armies without equipping them cheaply.</p><h3>Why Rome won: deep mobilization, expensive soldiers</h3><p>The graph compares Roman deployments or establishments with forces reported for particular rival campaigns. Those are different quantities, so the chart draws seven Roman estimates as short, separately defined segments and rivals as isolated campaign dots.</p><p>The striking argument is multiplicative but not literally measurable in tonnes. During the third and second centuries BCE, Rome repeatedly fielded unusually large forces while its heavy infantry carried expensive mail, unusually substantial helmets, swords, and iron-intensive pila. Devereaux’s comparative panoply model estimates about 25% more worked metal—iron and bronze—per Roman heavy infantryman than the nearest comparison.</p><p>The earlier version assigned exact kilograms, smooth rival series, and broad Roman filler estimates. The surviving evidence cannot support that precision, so those values are gone. What remains is checkable: an ancient deployment, an explicit unit model, published establishment estimates, cited campaign observations, and one bounded relative equipment comparison.</p><a className="source-link" href="https://acoup.blog/2022/10/28/fireside-friday-october-28-2022-the-book-project/">Read Devereaux’s public summary ↗</a></div>
        <div className="viz-card manpower-viz-v2"><div className="viz-title"><div><span>Force estimates + observed campaigns</span><h4>How much army could Rome keep replacing?</h4></div><small>500 BCE–500 CE · no annual rival interpolation</small></div><MilitaryCapacityChart /><p className="viz-note"><b>Method:</b> Seven Roman points appear in short segments only when their polity, scope, and estimation family are comparable; blank years are not interpolated. Rival outlined points are individual campaign forces, not a polity’s total capacity. The comparison excludes theoretical liability pools. Equipment is shown separately as a relative third–second-century BCE index because the cited public source does not publish defensible absolute metal masses for every army.</p></div>
      </section>
      <section className="insight fiscal-insight">
        <div className="insight-copy"><span className="insight-number">03</span><p className="claim">Rome taxed many things in many ways—but spent roughly three quarters of its central budget on the military.</p><h3>How Rome paid for empire</h3><p>There was no single Roman tax rate. Sicily could owe a share of its grain; traders crossing the Gallic customs district paid a duty; citizens funded veterans through taxes on inheritances and auctions; land and person taxes varied across provincial systems.</p><p>The unity was on the spending side. Duncan-Jones’s reconstructions put the army at about 72–77% of central imperial expenditure around 150 CE and 74–77% around 215 CE. The state moved money and produce from farms, ports, and households toward soldiers, frontiers, and the capital.</p><p>That was Rome’s fiscal achievement—and its vulnerability. A permanent army required permanent extraction. The chart shows two reconstructed budgets, not surviving accounts, and refuses to turn scattered rates into a fictional empire-wide average.</p><a className="source-link" href="https://acoup.blog/2023/11/03/collections-how-to-roman-republic-101-addenda-the-provinces/">Read Devereaux on provincial taxation ↗</a></div>
        <div className="viz-card fiscal-viz"><div className="viz-title"><div><span>Central expenditure + fiscal observations</span><h4>The Roman state was a military machine</h4></div><small>123 BCE–215 CE · rates retain their original base</small></div><RomanFiscalChart /><p className="viz-note"><b>Method:</b> Budget categories reproduce the low and high scenarios in Duncan-Jones’s reconstruction as presented by Mattingly. Fiscal observations retain their original unit, geography, payer, and destination. Nominal sestertii are not converted into modern money or treated as purchasing power.</p></div>
      </section>
      <section className="insight collapse-insight">
        <div className="insight-copy"><span className="insight-number">04</span><p className="claim">The western court lost taxable territory while crises kept demanding armies; losing Africa made recovery far harder.</p><h3>Why the western court fell</h3><p>There was no single “fall of Rome.” Between 395 and 476, civil wars redirected Roman armies, armed coalitions crossed frontiers, treaties substituted land and local resources for direct pay, provinces left central control, and major reconquests failed.</p><p>Africa made that spiral visible. When the Vandals seized Carthage and the richest provinces in 439, the court lost revenue that could sustain field armies. Peter Heather’s model puts the lost or damaged African revenues at the annual maintenance equivalent of about 58,000 infantry—or more than 30,000 cavalry. Those are fiscal equivalents, not soldiers observed leaving the rolls.</p><p>The western state still tried to recover. That matters: collapse was contingent, not a smooth inevitable decline. But its failures in 461 and 468 left a smaller revenue base facing the same need for military force. In 476 the western imperial office ended; the Roman state in the East did not.</p><a className="source-link" href="https://acoup.blog/2021/07/30/collections-the-queens-latin-or-who-were-the-romans-part-v-saving-and-losing-an-empire/">Read Devereaux on saving and losing an empire ↗</a></div>
        <div className="viz-card collapse-viz"><div className="viz-title"><div><span>Chronology + published fiscal model</span><h4>Territory paid for armies—until it did not</h4></div><small>395–476 CE · western court only</small></div><WesternCollapseChart /><p className="viz-note"><b>Method:</b> Twelve selected events show interacting pressures and recovery attempts without assigning causal scores. Heather’s African revenue model uses Elton’s annual soldier-maintenance costs. Valentinian III’s 445 law independently anchors the one-eighth assessment in the two named remaining African provinces.</p></div>
      </section>
      <section className="coming-insights" aria-labelledby="next-insights"><div><span className="insight-number">05</span><h3 id="next-insights">The final Rome argument</h3><p>A draft label means the page is honest about what remains. This is the next visual claim, not empty decoration.</p></div><ol><li><b>What Rome changed</b><span>Land, labor, roads, language, law, cities, and eastern survival.</span></li></ol></section>
    </HistoryPageShell>
  );
}
