import type { Metadata } from 'next';
import AlphaChronology from '../components/AlphaChronology';
import AlphaPendingInsight from '../components/AlphaPendingInsight';
import AndeanEcologicalFloors from '../AndeanEcologicalFloors';
import ChartFooter from '../components/ChartFooter';
import HistoryPageShell from '../components/HistoryPageShell';

export const metadata:Metadata={title:'Andean Worlds and the Inka',description:'Five visual arguments about roads, ecological floors, labor, knotted records, and conquest.',openGraph:{title:'Andean Worlds and the Inka — How Everything Evolved',description:'Roads turned ecological extremes into imperial reach.',images:[]},twitter:{card:'summary',title:'Andean Worlds and the Inka — How Everything Evolved',description:'Roads turned ecological extremes into imperial reach.',images:[]}};
const labels=['Roads turned ecological extremes into imperial reach','Households combined resources from different ecological floors','Labor obligations moved value without coin taxes','Knotted cords made people and stores administratively legible','Spanish conquest captured a civil war as well as an emperor'];
const events=[
  {year:1,displayYear:'30,000+ km',label:'Andean road network',detail:'UNESCO describes the Qhapaq Ñan and associated structures as a network exceeding thirty thousand kilometres.',kind:'full network estimate'},
  {year:2,displayYear:'4 routes',label:'Cusco as a junction',detail:'Four principal routes began at Cusco and connected to lower-order roads and cross-connections.',kind:'network organization'},
  {year:3,displayYear:'6,600+ m',label:'Extreme relief',detail:'The network linked high mountain terrain above 6,600 metres to coasts, forests, valleys, and deserts.',kind:'topographic range'},
  {year:4,displayYear:'4,200 km',label:'Imperial reach',detail:'UNESCO describes the fifteenth-century empire as extending up to 4,200 kilometres along the Andes.',kind:'north–south extent'},
  {year:5,displayYear:'616.06 km',label:'Inscribed sample',detail:'The World Heritage property preserves 137 component areas and 308 associated archaeological sites.',kind:'selected heritage subset'},
];
export default function AndesPage(){return <HistoryPageShell title="Andean Worlds and the Inka" eyebrow="1000 BCE–1533 CE" standfirst="Ecological complementarity, labor obligations, records, and roads coordinated one of history’s most vertical political landscapes." status="draft" progress="2 of 5 insights live" published="August 2026" insightLabels={labels}
  introduction={<><p>Andean societies coordinated coasts, valleys, high plateaus, and mountain slopes without reducing them to one ecological core. The Inka expanded this older regional knowledge into an imperial system of roads, labor, storage, and record-keeping.</p><p>The five claims move from physical integration to ecological portfolios, labor taxation, knotted records, and the civil war that made Spanish capture unusually consequential.</p></>}
  methods={<><p>The first visual uses UNESCO’s current statement of outstanding universal value for the Qhapaq Ñan. Its figures describe several scopes: the full network, imperial extent, topographic reach, route organization, and the selected World Heritage property.</p><p>The ecological-floor comparison preserves four unlike windows: early-colonial visitas reconstructed by Murra and Wachtel, archaeology and landscape evidence from Sama, and archaeobotany from Tiwanaku colonies. They show multiple ways to reach unlike production zones—not one universal Andean constitution.</p><p>The network includes pre-Inka infrastructure expanded and standardized under Tawantinsuyu. Road length does not measure traffic, travel speed, state control, or the equal intensity of rule.</p></>}>
  <section className="insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">More than 30,000 kilometres of roads connected peaks, coasts, forests, valleys, and deserts.</p><h3>{labels[0]}</h3><p>In the Andes, distance was vertical as well as horizontal. Roads, bridges, stairs, drainage, lodging, and storage allowed messengers, armies, officials, caravans, and communities to cross ecological zones that produced different things.</p><p>The achievement was not merely mileage. It was a political interface that joined inherited local routes to four main roads radiating from Cusco.</p></div><div className="viz-card"><div className="viz-title"><div><span>Qhapaq Ñan · fifteenth-century maximum</span><h4>{labels[0]}</h4></div><small>full network and heritage subset distinguished</small></div><AlphaChronology title="The road system crossed an extreme landscape" subtitle="UNESCO network measures" events={events}/><ChartFooter source="UNESCO World Heritage Centre, Qhapaq Ñan" note="Measures have different scopes. The 616.06 km World Heritage property is a selected sample of a network exceeding 30,000 km; none of the figures measures traffic or uniform control." dataHref="/data/andes/20260831-alpha1/qhapaq-nan-scale.csv"/></div></section>
  <section className="insight"><div className="insight-copy"><span className="insight-number">02</span><p className="claim">Andean communities reached across altitude instead of specializing in one ecological floor.</p><h3>{labels[1]}</h3><p>Highlands, valleys, forests, and coasts produced different resources. Communities joined them through outlying settlements, caravans, migration, and—under the Inka—state-directed relocation and labor.</p><p>The four cases are not one system. They show how ecological complementarity could be organized by households, ethnic polities, colonies, or an empire.</p></div><div className="viz-card"><div className="viz-title"><div><span>Four evidence windows · different institutions</span><h4>{labels[1]}</h4></div><small>600–1100 CE to early colonial visitas</small></div><AndeanEcologicalFloors/><ChartFooter source="Murra (1972); Baitzel & Rivera (2019); Garvin Suero et al. (2023); Wachtel (1982)" note="Cases preserve their original evidence and scope. Distances and elevations are anchors, not a verticality score; colonial visitas are not direct pre-Inka censuses." dataHref="/data/andes/20260901-floors1/andean-ecological-floor-access.csv"/></div></section>
  <AlphaPendingInsight number="03" title={labels[2]} question="Which labor obligations built roads, farmed state lands, supplied armies, and staffed workshops—and how did reciprocity constrain extraction?"/>
  <AlphaPendingInsight number="04" title={labels[3]} question="What could khipu record about people, tribute, stores, labor, and hierarchy without alphabetic writing?"/>
  <AlphaPendingInsight number="05" title={labels[4]} question="How did succession conflict, epidemic disruption, local alliances, steel, horses, and capture interact after Cajamarca?"/>
  </HistoryPageShell>}
