import type { Metadata } from 'next';
import AlphaChronology from '../components/AlphaChronology';
import AlphaPendingInsight from '../components/AlphaPendingInsight';
import ChartFooter from '../components/ChartFooter';
import HistoryPageShell from '../components/HistoryPageShell';
import MongolOperationalSystem from '../MongolOperationalSystem';

export const metadata:Metadata={title:'Mongol Eurasia',description:'Five visual arguments about disease ecology, armies, relays, merchants, and successor states.',openGraph:{title:'Mongol Eurasia — How Everything Evolved',description:'Mongol-era integration connected disease ecologies as well as markets.',images:[]},twitter:{card:'summary',title:'Mongol Eurasia — How Everything Evolved',description:'Mongol-era integration connected disease ecologies as well as markets.',images:[]}};
const labels=['Mongol-era integration connected disease ecologies as well as markets','Mounted armies won through organization, intelligence, and remounts','Relay stations made continental command faster','The empire protected merchants selectively—not uniformly','Successor states localized Mongol institutions instead of simply disappearing'];
const events=[
  {year:1,displayYear:'1338–39',label:'Dated epidemic burials',detail:'Tombstone inscriptions at cemeteries near Lake Issyk-Kul name pestilence as the cause of death.',kind:'historical and archaeological context'},
  {year:2,displayYear:'7 people',label:'Ancient DNA screening',detail:'Researchers sampled seven individuals from Kara-Djigach and Burana.',kind:'sample universe'},
  {year:3,displayYear:'3 positives',label:'Plague DNA',detail:'Three individuals from Kara-Djigach showed evidence of ancient Yersinia pestis DNA.',kind:'pathogen detection'},
  {year:4,displayYear:'2 genomes',label:'One recovered strain',detail:'Two reconstructed genomes were probably identical and represent the same epidemic strain.',kind:'genome reconstruction'},
  {year:5,displayYear:'Ancestral',label:'Pandemic diversification',detail:'The strain sits at the most recent common ancestor of the major diversification associated with the second plague pandemic.',kind:'phylogenetic placement'},
];
export default function MongolEurasiaPage(){return <HistoryPageShell title="Mongol Eurasia" eyebrow="1206–1500 CE" standfirst="Conquest joined courts, routes, merchants, messengers, ecosystems, and successor states across an unprecedented continental space." status="draft" progress="2 of 5 insights live" published="August 2026" insightLabels={labels}
  introduction={<><p>Mongol conquest did more than enlarge a polity. It reorganized military mobility, diplomacy, postal relays, commerce, and movement across Eurasia—while successor khanates adapted those systems to different societies.</p><p>The five claims start with the epidemiological downside of connection, then turn to armies, relays, merchant protection, and institutional localization after imperial unity fractured.</p></>}
  methods={<><p>The first visual reproduces the sample and headline conclusions of Spyrou and colleagues’ ancient-DNA study. Tombstone dates, screened individuals, positive samples, reconstructed genomes, and phylogenetic placement are unlike observations.</p><p>The paper supports a Central Eurasian source for the second plague pandemic. It explicitly says the means of westward transmission remain unknown; proximity to trans-Asian networks does not prove a route or make Mongol rule a sole cause.</p></>}>
  <section className="insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">A plague strain from 1338–1339 Central Eurasia was ancestral to published Black Death genomes.</p><h3>{labels[0]}</h3><p>The same connected world that moved envoys, merchants, animals, and goods also placed distant disease ecologies within reach of one another. Ancient DNA now anchors one crucial moment near Lake Issyk-Kul.</p><p>The genetics locates an ancestral strain. It does not reveal the exact route west, assign causality to trade alone, or turn the pandemic into a simple by-product of Mongol policy.</p></div><div className="viz-card"><div className="viz-title"><div><span>Kara-Djigach and Burana · ancient DNA</span><h4>{labels[0]}</h4></div><small>sample, detection, and ancestry kept separate</small></div><AlphaChronology title="Central Eurasian graves preserve a pandemic ancestor" subtitle="Historical and genomic evidence" events={events}/><ChartFooter source="Spyrou et al. (2022)" note="Two reconstructed genomes represent one strain ancestral to published fourteenth-century western Eurasian genomes. The study does not identify a westward route or prove Mongol rule caused transmission." dataHref="/data/mongol-eurasia/20260831-alpha1/black-death-origin-evidence.csv"/></div></section>
  <section className="insight"><div className="insight-copy"><span className="insight-number">02</span><p className="claim">Mongol mobility was organized—not just fast.</p><h3>{labels[1]}</h3><p>Horses mattered, but an individual rider is not an army. Decimal command units, scouts, spare mounts, and separated columns converted steppe mobility into repeatable operational choices.</p><p>The evidence is strongest for the system’s parts, not a single numerical “Mongol advantage.” Select a mechanism to see the problem it solved and the limit of what survives.</p></div><div className="viz-card"><div className="viz-title"><div><span>Command + information + endurance</span><h4>{labels[1]}</h4></div><small>four evidence windows · no power score</small></div><MongolOperationalSystem/><ChartFooter source="Timothy May (2015, 2024); H. Desmond Martin (1943), using Meng Hong" note="Organizational units, reported scouting, spare horses, and campaign movements are unlike evidence. No annual army size, speed, or causal share is reconstructed." dataHref="/data/mongol-eurasia/20260901-operations1/mongol-operational-system.csv"/></div></section>
  <AlphaPendingInsight number="03" title={labels[2]} question="Where did stations, fresh mounts, provisions, passports, and local obligations make long-distance imperial communication work?"/>
  <AlphaPendingInsight number="04" title={labels[3]} question="Which merchants received capital, protection, tax privileges, or coercive backing—and where did war and fragmentation still interrupt exchange?"/>
  <AlphaPendingInsight number="05" title={labels[4]} question="How did Yuan, Ilkhanid, Chaghatayid, and Golden Horde institutions combine steppe rule with Chinese, Persian, Islamic, and Rus political systems?"/>
  </HistoryPageShell>}
