import type { Metadata } from 'next';
import ChartFooter from '../components/ChartFooter';
import EvidencePanel from '../components/EvidencePanel';
import HistoryPageShell from '../components/HistoryPageShell';
import IndusMetrology from '../IndusMetrology';
import IndiaMonsoonStrategies from '../IndiaMonsoonStrategies';
import IndiaMauryanRelationships from '../IndiaMauryanRelationships';
import IndiaUrbanRevival from '../IndiaUrbanRevival';
import IndiaNetworksBeyondEmpire from '../IndiaNetworksBeyondEmpire';

export const metadata:Metadata={title:'India from cities to empires',description:'Five visual arguments about Indus coordination, monsoon ecologies, urban revival, Mauryan rule, and networks that outlasted states.',openGraph:{title:'India from cities to empires — How Everything Evolved',description:'The Indus coordinated cities without monumentalizing rulers.',images:[]},twitter:{card:'summary',title:'India from cities to empires — How Everything Evolved',description:'Published weights and the archaeology of power in the Indus cities.',images:[]}};

const labels=[
  'Indus cities coordinated without monumentalizing rulers',
  'Indus farmers answered rainfall risk with different crop calendars',
  'Cities returned before one empire united them',
  'One Mauryan empire contained several kinds of rule',
  'Goods, production knowledge, and courtly language traveled farther than Indian empires',
];

export default function IndiaPage(){return <HistoryPageShell
  title="India from cities to empires"
  eyebrow="2600 BCE–550 CE · cities · ecology · empire · networks"
  standfirst="South Asia repeatedly coordinated across distance without one enduring political center."
  status="reviewed"
  progress="5 of 5 insights live"
  published="August 2026"
  introduction={<><p>South Asian history did not move from one civilization to one empire. The Indus cities coordinated measurements, objects, and urban systems across great distances; later political and economic centers emerged in different ecological zones; Mauryan rulers joined many of those worlds without governing every region in the same way.</p><p>The five arguments on this page ask what made coordination possible when political borders were unstable or invisible. The first begins with a striking Indus combination: a shared system of small stone weights and no securely identified tradition of palaces, royal tombs, great temples, or monuments centered on named rulers.</p><p>That combination does not prove that the Indus had no rulers. It shows that complex urban coordination did not require rulers to advertise themselves in the same monumental forms seen in several contemporary states.</p></>}
  insightLabels={labels}
  methods={<><p>The weight comparison transcribes J. Mark Kenoyer&apos;s Table 9.3, which republishes means and sample sizes from the Harappa Archaeological Research Project, M. S. Vats&apos;s Harappa excavations, and E. J. H. Mackay&apos;s Mohenjo-daro excavations. Each plotted point divides a published series mean by its category ratio. The vertical reference is 0.857 grams, Hemmy&apos;s fitted unit in the official 1931 Mohenjo-daro report.</p><p>The chart preserves the high-ratio HARP deviation instead of removing it. Sample sizes vary from one to ninety-four; the points therefore are not equally precise. The weights were generally small and should not be treated as evidence for bulk-grain markets, one price system, or universal everyday exchange.</p><p>Adam Green&apos;s peer-reviewed review anchors the absence panel. “No clear identification” means that a century of excavation has not securely identified palaces, elaborate royal tombs, large temples, or ruler-aggrandizing monuments. It does not prove that the Indus lacked rulers, elites, inequality, ritual institutions, or coercion. The undeciphered script sharply limits claims about office, taxation, law, and political scale.</p><p>The crop-calendar comparison transcribes Bates and Choi&apos;s regional synthesis rather than combining incompatible site assemblages. Percentages are shown only for their published Harappa and Khirsara anchors. Crop presence and assemblage shares are not acreage, output, yield, caloric intake, or population diet; only about 20% of Harappa&apos;s archaeobotanical assemblage had been published.</p><p>The urban-revival sequence follows Reshma Sawant&apos;s three broad phases and Monica Smith&apos;s argument that South Asian cities should be analyzed separately from territorial states. The seven fortified sites are named examples, not a census. Pottery, coins, streets, wells, drains, fortifications, and scripts have different chronologies and do not form one urbanization index or prove that iron, trade, religion, or empire was the sole cause.</p><p>The Mauryan comparison reads Ashoka&apos;s edicts as evidence for different political relationships, not as a complete map. Royal inspection schedules are prescriptions rather than observed travel; four regional centers are not a full province list; separate Kalinga edicts do not measure compliance; and welfare claims among neighboring peoples do not establish annexation.</p><p>The network comparison deliberately uses three unlike evidence windows rather than drawing one diffusion map. Khao Sam Kaeo combines technological and workshop evidence; Berenike combines a preserved commodity find with port archaeology; Pollock&apos;s Sanskrit cosmopolis describes a shared literary-political practice among distinct courts. None measures total trade, population belief, ethnicity, territorial dependence, or a continuous “Indianized” zone.</p><EvidencePanel page="india"/></>}
>
  <section className="insight india-metrology-insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">Harappa and Mohenjo-daro shared a carefully graduated weight system, yet their cities did not center visible palaces, royal tombs, or monuments to named rulers.</p><h3>{labels[0]}</h3><p>In the published weight series, classes from one to 160 units repeatedly imply a small base close to 0.857 grams. Hemmy&apos;s excavation report found the Harappa and Mohenjo-daro systems effectively identical despite roughly 500 miles between the cities.</p><p>That precision is evidence for shared conventions, not automatically for one king or one state. The weights have no written value marks, the script remains undeciphered, and newer scholarship finds no securely identified palace, royal tomb, large temple, or ruler-aggrandizing monument.</p><p>The result is more interesting than “mysterious standardization.” Indus institutions coordinated people who could recognize the same material rules while political authority remained comparatively quiet in the surviving monumental record.</p></div><div className="viz-card india-metrology-viz"><div className="viz-title"><div><span>Published weights + archaeological absence</span><h4>{labels[0]}</h4></div><small>c. 2600–1900 BCE · three excavation series</small></div><IndusMetrology/><ChartFooter source="Kenoyer (2010), Table 9.3; Hemmy in Marshall (1931); Green (2021)" note="Dots are published series means divided by their category ratios. Shared metrology does not identify one ruler or state; missing monumental signals do not prove that elites were absent." dataHref="/data/india/20260831-metrology1/indus-weight-series.csv"/></div></section>
  <section className="insight india-monsoon-insight"><div className="insight-copy"><span className="insight-number">02</span><p className="claim">The Indus world did not run on one agricultural calendar. Farmers matched winter rain, summer monsoons, and local water conditions with different crop strategies.</p><h3>{labels[1]}</h3><p>At Harappa, published plant remains are dominated by winter wheat and barley; summer millets increased but never exceeded 7% of the assemblage. That pattern may reflect the supply demands of a large city, although most of the excavated material remains unpublished.</p><p>Khirsara in Gujarat moved in another direction: an early assemblage that was 90% barley became more mixed, then shifted toward summer pearl millet, rice, and sorghum. At Masudpur VII in the northeast, farmers used winter and summer seasons throughout the Indus sequence and kept adding crops.</p><p>The comparison replaces “one Indus agriculture” with regional choices. It does not turn crop remains into acreage, yields, diets, or proof that diversity alone made settlements resilient.</p></div><div className="viz-card india-monsoon-viz"><div className="viz-title"><div><span>Archaeobotanical crop calendars</span><h4>{labels[1]}</h4></div><small>three sites · three regional strategies</small></div><IndiaMonsoonStrategies/><ChartFooter source="Bates & Choi (2023)" note="Crop remains are archaeological assemblages, not acreage, output, or population diets. Harappa is incompletely published; qualitative rows are not converted into percentages." dataHref="/data/india/20260831-monsoon1/indus-cropping-strategies.csv"/></div></section>
  <section className="insight india-urban-insight"><div className="insight-copy"><span className="insight-number">03</span><p className="claim">By 600–300 BCE, northern South Asia already had rival urban polities, fortifications, planned streets, wells, drains, coins, and writing. Mauryan unification came afterward.</p><h3>{labels[2]}</h3><p>The first phase was politically plural. Kosala, Vatsa, Magadha, and Avanti were four notable rival monarchies, while other Janapadas used monarchical or non-monarchical constitutions.</p><p>The archaeology is urban before it is uniformly imperial: Sawant names seven fortified-site examples from Charsada to Ujjain and identifies streets, lanes, brick and ring wells, drainage, early coinage, script, and Northern Black Polished Ware across the period.</p><p>Magadha became supreme by the fourth century BCE, and Mauryan rule then widened political and economic connections. But the sequence matters: empire integrated an urban world it did not create from scratch.</p></div><div className="viz-card india-urban-viz"><div className="viz-title"><div><span>Urban fabric + political order</span><h4>{labels[2]}</h4></div><small>600 BCE–300 CE · three broad phases</small></div><IndiaUrbanRevival/><ChartFooter source="Sawant (2023); Smith (2006)" note="Phases combine asynchronous regional evidence. Named sites and dynasties are examples, not complete censuses; urban features are not combined into one score or attributed to one cause." dataHref="/data/india/20260831-urban1/early-historic-urban-phases.csv"/></div></section>
  <section className="insight india-maurya-insight"><div className="insight-copy"><span className="insight-number">04</span><p className="claim">Ashoka&apos;s inscriptions describe direct inspection from the court, delegated regional government, special post-conquest orders in Kalinga, and relations with independent neighbors.</p><h3>{labels[3]}</h3><p>The empire did not meet every region through one administrative template. The court ordered five-year inspection tours from Pataliputra and three-year tours from Ujjain and Taxila; princes and senior officers worked through regional centers.</p><p>Recently conquered Kalinga received a different intervention. Separate edicts at Dhauli and Jaugada instructed local officials on justice and asked unconquered border peoples to trust the king.</p><p>Major Rock Edict II then named southern peoples and Hellenistic kings beyond Ashoka&apos;s domain. The same ruler could command, delegate, reassure, and negotiate. One imperial name covered several political relationships.</p></div><div className="viz-card india-maurya-viz"><div className="viz-title"><div><span>Court orders + regional relationships</span><h4>{labels[3]}</h4></div><small>third century BCE · four inscriptional windows</small></div><IndiaMauryanRelationships/><ChartFooter source="Ashoka's edicts, trans. Thapar; Chakravarti (2014)" note="Edict locations and named centers are evidence windows, not complete borders or a control-intensity scale. Royal prescriptions do not prove uniform implementation." dataHref="/data/india/20260831-maurya1/mauryan-regional-relationships.csv"/></div></section>
  <section className="insight india-networks-insight"><div className="insight-copy"><span className="insight-number">05</span><p className="claim">South Asian goods, production knowledge, and courtly language reached ports and courts that no Indian empire governed.</p><h3>{labels[4]}</h3><p>At Khao Sam Kaeo on the Thai-Malay Peninsula, local workshops combined South Asian, Southeast Asian, and Western Han technical traditions. More than one thousand studied glass samples and three copper-alloy traditions reveal an exchange crossroads—not a foreign colony.</p><p>At Berenike in Roman Egypt, one Indian-made vessel preserved 7.55 kilograms of South Indian black pepper. Other ceramics, textiles, teak, and Tamil-Brahmi writing show that monsoon exchange carried commodities and people into Roman territory.</p><p>From the fourth and fifth centuries CE, distinct Southeast Asian courts also adopted Sanskrit for political and literary expression. Materials, skills, and languages traveled on overlapping networks; armies and administrators did not have to follow.</p></div><div className="viz-card india-networks-viz"><div className="viz-title"><div><span>Three crossings · three carriers</span><h4>{labels[4]}</h4></div><small>fourth century BCE–fifth century CE onward</small></div><IndiaNetworksBeyondEmpire/><ChartFooter source="Lankton et al. (2006); Murillo-Barroso et al. (2010); Bellina (2018); Seland (2014); Pollock (2006)" note="The cases use unlike archaeological and textual evidence. They show connections beyond political rule, not total flows, one continuous cultural zone, or population affiliation." dataHref="/data/india/20260831-networks1/india-networks-beyond-empires.csv"/></div></section>
</HistoryPageShell>}
