import type { Metadata } from 'next';
import AlphaChronology from '../components/AlphaChronology';
import AlphaPendingInsight from '../components/AlphaPendingInsight';
import ChartFooter from '../components/ChartFooter';
import HistoryPageShell from '../components/HistoryPageShell';
import HellenisticCapitalMachines from '../HellenisticCapitalMachines';

export const metadata:Metadata={title:'Hellenistic Kingdoms',description:'Five visual arguments about coalition armies, capitals, soldiers, money, and cultural change after Alexander.',openGraph:{title:'Hellenistic Kingdoms — How Everything Evolved',description:'Hellenistic armies were multinational systems, not Macedonian replicas.',images:[]},twitter:{card:'summary',title:'Hellenistic Kingdoms — How Everything Evolved',description:'Hellenistic armies were multinational systems, not Macedonian replicas.',images:[]}};
const labels=['Hellenistic armies were multinational systems, not Macedonian replicas','Hellenistic capitals turned imperial resources into visible kingship','Kings paid soldiers with land, cash, and privilege','Coinage made rival kingdoms legible to each other','Greek institutions spread without making populations Greek'];
const events=[
  {year:1,displayYear:'25,000',label:'Ptolemaic phalangites',detail:'Polybius assigns the main Macedonian-style phalanx to commanders from Aspendus and Aspendian service.',kind:'transmitted contingent'},
  {year:2,displayYear:'20,000',label:'Ptolemaic Egyptians',detail:'Egyptian troops were trained and equipped for service in the Macedonian manner.',kind:'transmitted contingent'},
  {year:3,displayYear:'8,000',label:'Ptolemaic Greek mercenaries',detail:'A large hired Greek contingent fought alongside royal, Egyptian, Libyan, Cretan, Thracian, and Gallic units.',kind:'transmitted contingent'},
  {year:4,displayYear:'6,000',label:'Ptolemaic Thracians and Gauls',detail:'Four thousand were drawn from Egypt and two thousand were recent arrivals from Europe.',kind:'transmitted contingent'},
  {year:5,displayYear:'30,000',label:'Seleucid phalangites',detail:'Ten thousand Silver Shields and twenty thousand other Macedonian-style phalangites formed the infantry core.',kind:'transmitted contingent'},
  {year:6,displayYear:'10,000',label:'Seleucid Arabs',detail:'An Arab contingent under Zabdibelus formed one large component of Antiochus’s line.',kind:'transmitted contingent'},
  {year:7,displayYear:'5,000',label:'Seleucid eastern peoples',detail:'Medes, Cissians, Cadusians, and Carmanians were grouped under Aspasianus.',kind:'transmitted contingent'},
  {year:8,displayYear:'5,000',label:'Seleucid Greek mercenaries',detail:'Hired Greek troops fought beside Iranian, Arab, Anatolian, Cretan, and Thracian units.',kind:'transmitted contingent'},
];
export default function HellenisticKingdomsPage(){return <HistoryPageShell title="Hellenistic Kingdoms" eyebrow="323–30 BCE" standfirst="Alexander’s successors ruled through armies, cities, and institutions assembled from many populations." status="draft" progress="2 of 5 insights live" published="August 2026" insightLabels={labels}
  introduction={<><p>Alexander’s conquests did not leave one empire. They produced competing royal states that fought over revenue, cities, soldiers, and legitimacy from the Mediterranean to Central Asia.</p><p>The five claims focus on how these kingdoms assembled diverse armies, concentrated resources in capitals, rewarded service, standardized exchange, and spread Greek civic forms without making their populations culturally uniform.</p></>}
  methods={<><p>The first visual transcribes selected unit figures from Polybius’s account of Raphia in 217 BCE. They are ancient reported numbers, not audited payrolls. The Oxford Classical Dictionary notes a textual ambiguity over whether the twenty thousand Egyptians were included in or additional to the twenty-five-thousand phalanx.</p><p>The second visual compares unlike evidence for four royal capitals: Strabo’s later description of Alexandria, modern syntheses of the Seleucid court, and Pergamon’s excavated acropolis. It identifies institutional mechanisms rather than population, revenue, expenditure, traffic, or consent.</p><p>The visuals do not sum a new Raphia total, calculate ethnic shares, treat unit labels as fixed identities, or combine capitals into a scale or power score.</p></>}>
  <section className="insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">At Raphia, both kings assembled armies from many regions and military traditions.</p><h3>{labels[0]}</h3><p>Polybius’s order of battle puts Egyptians trained in Macedonian methods beside Greek mercenaries, Libyans, Cretans, Thracians, and Gauls for Ptolemy IV. Antiochus III fielded Macedonian-style phalangites with Arabs, Iranian peoples, Greeks, Cretans, Thracians, and others.</p><p>The phalanx remained central, but the kingdom’s real military technology was organizational: recruiting, paying, supplying, and commanding unlike contingents as one royal army.</p></div><div className="viz-card"><div className="viz-title"><div><span>Battle of Raphia · 217 BCE</span><h4>{labels[0]}</h4></div><small>selected transmitted contingents · no recomputed total</small></div><AlphaChronology title="Two royal armies, many recruiting pools" subtitle="Polybius’s order of battle" events={events}/><ChartFooter source="Polybius 5.65–5.79; Oxford Classical Dictionary" note="Ancient troop figures are transmitted estimates. The Egyptian/phalanx total is textually ambiguous, so the chart does not recompute army totals or ethnic shares." dataHref="/data/hellenistic-kingdoms/20260831-alpha1/raphia-contingents.csv"/></div></section>
  <section className="insight hellenistic-capitals-insight"><div className="insight-copy"><span className="insight-number">02</span><p className="claim">A royal capital made extraction persuasive by turning it into harbours, palaces, festivals, libraries, and monuments.</p><h3>{labels[1]}</h3><p>Hellenistic kings inherited territories too large and diverse to rule through one civic assembly. Their capitals drew resources and representatives toward a court, then staged the dynasty as prosperous, learned, victorious, and worth approaching.</p><p>The mechanism took different forms. Alexandria joined Nile and sea traffic to a palace quarter. The mobile Seleucid court used several regional residences. Antioch’s festivals brought civic elites before the king. Pergamon made dynastic victory into an excavated urban landscape.</p><p>These were political machines, not just large cities—and their monumentality is much easier to observe than the taxes, labor, and negotiations that sustained it.</p></div><div className="viz-card hellenistic-capitals-viz"><div className="viz-title"><div><span>Four royal capitals · unlike evidence windows</span><h4>{labels[1]}</h4></div></div><HellenisticCapitalMachines/><ChartFooter source="Strabo 17.1; Strootman (2014); Encyclopaedia Iranica; Metropolitan Museum of Art" note="Ancient description, court history, and excavation answer different questions. The comparison does not estimate population, revenue, expenditure, traffic, or political consent." dataHref="/data/hellenistic-kingdoms/20260831-capitals1/royal-capital-machines.csv"/></div></section>
  <AlphaPendingInsight number="03" title={labels[2]} question="Where did settlements, cleruchies, pay, tax privileges, and royal gifts turn military service into durable institutions?"/>
  <AlphaPendingInsight number="04" title={labels[3]} question="How did shared denominations, royal portraits, mints, and bullion zones make payments comparable while kingdoms remained rivals?"/>
  <AlphaPendingInsight number="05" title={labels[4]} question="Where did Greek language and civic institutions coexist with Egyptian, Babylonian, Iranian, Jewish, and other durable traditions?"/>
  </HistoryPageShell>}
