import type { Metadata } from 'next';
import PersianRoadRelay from '../PersianRoadRelay';
import PersianSatrapalPortfolios from '../PersianSatrapalPortfolios';
import PersianTributeSystem from '../PersianTributeSystem';
import PersianCoalitionArmy from '../PersianCoalitionArmy';
import EvidencePanel from '../components/EvidencePanel';
import HistoryPageShell from '../components/HistoryPageShell';

export const metadata:Metadata={title:'Persia and territorial empire',description:'How Achaemenid roads, relays, provinces, tribute, and negotiated rule made territory governable.',openGraph:{title:'Persia and territorial empire — How Everything Evolved',description:'The road did not abolish distance. It reorganized who and what had to move.',images:[]},twitter:{card:'summary',title:'Persia and territorial empire — How Everything Evolved',description:'A source-bounded Royal Road itinerary and relay comparison.',images:[]}};

export default function PersiaPage(){return <HistoryPageShell
  title="Persia and territorial empire"
  eyebrow="550–330 BCE · roads · provinces · tribute"
  standfirst="The Achaemenid achievement was not ruling every place in the same way. It was making distant places answerable through roads, relays, provincial bargains, tribute, and coalition armies."
  status="draft"
  progress="4 of 5 insights live"
  published="August 2026"
  introduction={<><p>The Achaemenid Empire joined lands from the Aegean and Egypt to Central and South Asia. No ruler could see, count, tax, provision, or command that space directly. Imperial scale depended on institutions that translated distance into stages, provinces, obligations, and negotiated relationships.</p><p>This page begins with the Royal Road because it exposes both achievement and limit. Herodotus gives a six-part Sardis–Susa itinerary and describes a relay of fresh carriers, while the Persepolis Fortification archive preserves a regional administrative world of authorizations, road stations, and provisions. These are related windows—not one complete imperial timetable.</p><p>The first four insights compare relays, five satrapal portfolios, seven forms of obligation, and six military assembly windows. Provinces were interfaces rather than standardized boxes; extraction and armies joined unlike local systems to royal purposes. The final insight will test institutional afterlives without treating dynasty, empire, or cultural influence as the same thing.</p></>}
  insightLabels={['Persian roads made distance a relay problem','Satrapies combined royal appointment with negotiated local rule','Tribute was a political relationship, not one tax rate','Imperial armies were coalitions of distinct military systems','Persian institutions outlasted the Achaemenid dynasty']}
  methods={<><p>Herodotus&apos;s six itinerary segments retain his stages and parasangs. The route strip is proportional to parasangs but is not a surveyed map; it does not convert parasangs into kilometres or infer exact coordinates, station spacing, traffic, construction, or travel speed.</p><p>The ninety-day journey is Herodotus&apos;s arithmetic. His relay description establishes successive horses and riders but does not state a Sardis–Susa courier duration. Later seven-day claims are therefore not plotted.</p><p>The Persepolis Fortification archive demonstrates provisioning, authorization, and road-station practice in a surviving regional archive centered on Persis and Elam. It is not an empire-wide postal census.</p><p>The satrapy comparison keeps five unlike evidence windows separate. Behistun is royal self-presentation; Herodotus is a later Greek narrative; the Arshama letters are a bounded estate and administrative archive; Caria and Dascylium depend on regional syntheses of literary, epigraphic, and archaeological evidence. The comparison does not make Herodotus&apos;s tribute districts identical to satrapies, infer one universal bureaucracy, or compute autonomy, loyalty, tax, or control scores.</p><p>The tribute comparison preserves Herodotus&apos;s twenty reported districts as a literary accounting model and uses cuneiform documentary scholarship as a separate counterweight. Only nineteen silver rows share a bar scale. Indian gold dust, Cilician horses, Egyptian grain, frontier gifts, service, and the Apadana relief remain unlike evidence. No modern currency, per-capita burden, tax rate, or empire-wide revenue total is inferred.</p><p>The coalition comparison preserves catalogues, campaign narratives, and a regional administrative archive as unlike source classes. Ancient headline army and ship totals are excluded. Herodotus&apos;s catalogue counts remain labels rather than soldiers; Xenophon cannot establish every Cunaxa command exchange; Arrian&apos;s Gaugamela order was written centuries after the battle from lost sources; and the Persepolis archive is not a campaign supply ledger.</p><EvidencePanel page="persia"/></>}
>
  <section className="insight persia-road-insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">Achaemenid roads did not abolish distance. Staffed stages, stores, authorizations, and fresh carriers made messages move differently from travelers.</p><h3>The road made movement relayable</h3><p>Herodotus describes the Sardis–Susa route as six regional segments totaling 111 stages and 450 parasangs. His own arithmetic gives an ordinary journey of ninety days. That is a supported road, not a small empire.</p><p>The courier system changed the unit that moved. A horse and rider carried the message for one stage, then passed it onward. The dispatch could continue through weather and darkness because exhaustion belonged to each carrier rather than to the message.</p><p>The Persepolis Fortification archive shows the administrative layer underneath: sealed authorizations, provisions issued to travelers and messengers, road-station vouchers, stores, and local personnel. The famous riders were the visible edge of a provisioning and accounting system.</p><a className="source-link" href="https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0126%3Abook%3D5%3Achapter%3D52">Read Herodotus&apos;s itinerary ↗</a></div><div className="viz-card persia-road-viz"><div className="viz-title"><div><span>Itinerary + relay mechanism + administrative archive</span><h4>How did Persia reorganize distance?</h4></div><small>509–480 BCE evidence windows · no speed score</small></div><PersianRoadRelay/><p className="viz-note"><b>Method:</b> The route strip preserves Herodotus&apos;s six segments and relative parasang totals. Traveler time, relay mechanics, and regional administrative practice remain separate evidence classes.</p></div></section>
  <section className="insight persia-satrapy-insight"><div className="insight-copy"><span className="insight-number">02</span><p className="claim">Satrapies were not identical provincial boxes. Royal appointees worked through different cities, dynasties, districts, households, and military communities.</p><h3>A satrapy was an interface, not a copy</h3><p>Darius&apos;s Behistun inscription shows the direct version: the king says he ordered Dādarši, his servant and satrap in Bactria, to suppress the Margian revolt. Herodotus shows a different western portfolio, where Artaphrenes summoned Ionian city envoys, compelled inter-city agreements, measured land, and reassessed tribute after revolt.</p><p>Egypt kept its own districts, indigenous fiscal officials, temples, and multilingual administrative practices beneath a Persian top office. Arsames could send sealed Aramaic orders from outside Egypt while local agents and institutions did the work. Caria instead joined empire to a powerful local dynasty with its own fleet, administrators, coinage, and monumental program.</p><p>The pattern is neither loose tolerance nor uniform centralization. The court appointed or confirmed high-level governors, demanded results, and intervened in crises. Provincial effectiveness came from connecting that royal authority to local knowledge and organizations the empire did not replace.</p><a className="source-link" href="https://www.iranicaonline.org/articles/achaemenid-satrapies/">Read the administrative synthesis ↗</a></div><div className="viz-card persia-satrapy-viz"><div className="viz-title"><div><span>Five provincial portfolios · five evidence classes</span><h4>What did a satrapy actually connect?</h4></div><small>522–334 BCE · no autonomy or control score</small></div><PersianSatrapalPortfolios/><p className="viz-note"><b>Method:</b> Select a case to follow top office → local partners → obligation → royal connection → visible action. The portfolios are source-bounded administrative windows, not a complete list of satrapies or one provincial hierarchy.</p></div></section>
  <section className="insight persia-tribute-insight"><div className="insight-copy"><span className="insight-number">03</span><p className="claim">Achaemenid extraction did not reduce every province to one comparable percentage. Silver schedules, horses, grain, gold dust, service, and gifts encoded different obligations and statuses.</p><h3>Obligation was a portfolio, not a rate</h3><p>Herodotus organizes imperial revenue into twenty districts, but even his tidy account refuses one common unit. Nineteen districts are assessed in Babylonian talents of silver. India instead delivers gold dust measured in Euboic talents; Cilicia adds horses; Egypt provisions a garrison.</p><p>The differences were political, not merely accounting noise. Cilicia&apos;s reported silver assessment partly supported a local cavalry guard. Peoples beyond the regular tribute list brought gold, ebony, ivory, people, or frankincense on different calendars. A gift could be a regulated sign of status rather than voluntary generosity.</p><p>Cuneiform documents from Babylonia and Iran complicate the Greek schedule further: assessments appear in silver, barley, flour, livestock, beer, provisions, and service. The Apadana reliefs picture twenty-three delegations bearing distinctive goods, but that royal image is an argument about ordered diversity—not an annual fiscal ledger.</p><a className="source-link" href="https://www.iranicaonline.org/articles/achaemenid-taxation/">Read the documentary synthesis ↗</a></div><div className="viz-card persia-tribute-viz"><div className="viz-title"><div><span>Twenty districts + seven obligation windows</span><h4>What did imperial obligation look like?</h4></div><small>ca. 515–mid-5th century BCE · no common tax rate</small></div><PersianTributeSystem/><p className="viz-note"><b>Method:</b> One view preserves Herodotus&apos;s district schedule; the other compares unlike forms of obligation. Only the nineteen silver rows share an internal Herodotean scale. Gold dust, horses, grain, gifts, services, documents, and royal imagery remain separate.</p></div></section>
  <section className="insight persia-coalition-insight"><div className="insight-copy"><span className="insight-number">04</span><p className="claim">Persia&apos;s military scale came from assembling distinct infantry, cavalry, fleets, mercenaries, commanders, and provisioning systems—not from turning them into one uniform army.</p><h3>The army was an assembly</h3><p>The empire could call on formations whose skills came from different places and institutions: Persian and Median cores, Central Asian cavalry, Phoenician and Egyptian maritime systems, regional levies, and Greek mercenaries. Herodotus&apos;s catalogue is imperfect, but its equipment and command differences are the point.</p><p>Scale therefore depended on interfaces. National and regional commanders linked contingents upward; royal commanders turned them into wings, centers, and fleets; depots, markets, wagons, animals, authorizations, and road stations had to put food and movement underneath the plan.</p><p>Those interfaces could fail. At Cunaxa, Cyrus&apos;s intended strike at the royal center did not emerge from the reported order passed through an interpreter; the Greeks won their local fight while Cyrus died. At Gaugamela, the surviving later account preserves a far more explicit left–center–right design. Neither case yields a trustworthy total army size.</p><a className="source-link" href="https://www.iranicaonline.org/articles/army-i/">Read the military evidence synthesis ↗</a></div><div className="viz-card persia-coalition-viz"><div className="viz-title"><div><span>Six source windows · four assembly layers</span><h4>How did many military systems become one campaign?</h4></div><small>509–331 BCE · no accepted army totals</small></div><PersianCoalitionArmy/><p className="viz-note"><b>Method:</b> Follow one source window or compare contributors, command, support, and coordination across six windows. Catalogue labels are not soldiers; the visual assigns no ethnic share, equipment rank, or combat-power score.</p></div></section>
  <section className="insight insight-placeholder"><div className="insight-copy"><span className="insight-number">05</span><p className="claim">This argument remains in the evidence audit.</p><h3>Institutions survived dynasties</h3><p>The visual will publish only when its sources, definitions, and inference limits are strong enough to support a historical comparison.</p><span className="status status-research">research</span></div></section>
</HistoryPageShell>}
