import type { Metadata } from 'next';
import PersianRoadRelay from '../PersianRoadRelay';
import EvidencePanel from '../components/EvidencePanel';
import HistoryPageShell from '../components/HistoryPageShell';

export const metadata:Metadata={title:'Persia and territorial empire',description:'How Achaemenid roads, relays, provinces, tribute, and negotiated rule made territory governable.',openGraph:{title:'Persia and territorial empire — How Everything Evolved',description:'The road did not abolish distance. It reorganized who and what had to move.',images:[]},twitter:{card:'summary',title:'Persia and territorial empire — How Everything Evolved',description:'A source-bounded Royal Road itinerary and relay comparison.',images:[]}};

export default function PersiaPage(){return <HistoryPageShell
  title="Persia and territorial empire"
  eyebrow="550–330 BCE · roads · provinces · tribute"
  standfirst="The Achaemenid achievement was not ruling every place in the same way. It was making distant places answerable through roads, relays, provincial bargains, tribute, and coalition armies."
  status="draft"
  progress="1 of 5 insights live"
  published="August 2026"
  introduction={<><p>The Achaemenid Empire joined lands from the Aegean and Egypt to Central and South Asia. No ruler could see, count, tax, provision, or command that space directly. Imperial scale depended on institutions that translated distance into stages, provinces, obligations, and negotiated relationships.</p><p>This page begins with the Royal Road because it exposes both achievement and limit. Herodotus gives a six-part Sardis–Susa itinerary and describes a relay of fresh carriers, while the Persepolis Fortification archive preserves a regional administrative world of authorizations, road stations, and provisions. These are related windows—not one complete imperial timetable.</p><p>The next four insights will test satrapal rule, tribute, coalition armies, and institutional afterlives without turning diverse provinces into one tax rate, army, or centralization score.</p></>}
  insightLabels={['Persian roads made distance a relay problem','Satrapies combined royal appointment with negotiated local rule','Tribute was a political relationship, not one tax rate','Imperial armies were coalitions of distinct military systems','Persian institutions outlasted the Achaemenid dynasty']}
  methods={<><p>Herodotus&apos;s six itinerary segments retain his stages and parasangs. The route strip is proportional to parasangs but is not a surveyed map; it does not convert parasangs into kilometres or infer exact coordinates, station spacing, traffic, construction, or travel speed.</p><p>The ninety-day journey is Herodotus&apos;s arithmetic. His relay description establishes successive horses and riders but does not state a Sardis–Susa courier duration. Later seven-day claims are therefore not plotted.</p><p>The Persepolis Fortification archive demonstrates provisioning, authorization, and road-station practice in a surviving regional archive centered on Persis and Elam. It is not an empire-wide postal census.</p><EvidencePanel page="persia"/></>}
>
  <section className="insight persia-road-insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">Achaemenid roads did not abolish distance. Staffed stages, stores, authorizations, and fresh carriers made messages move differently from travelers.</p><h3>The road made movement relayable</h3><p>Herodotus describes the Sardis–Susa route as six regional segments totaling 111 stages and 450 parasangs. His own arithmetic gives an ordinary journey of ninety days. That is a supported road, not a small empire.</p><p>The courier system changed the unit that moved. A horse and rider carried the message for one stage, then passed it onward. The dispatch could continue through weather and darkness because exhaustion belonged to each carrier rather than to the message.</p><p>The Persepolis Fortification archive shows the administrative layer underneath: sealed authorizations, provisions issued to travelers and messengers, road-station vouchers, stores, and local personnel. The famous riders were the visible edge of a provisioning and accounting system.</p><a className="source-link" href="https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0126%3Abook%3D5%3Achapter%3D52">Read Herodotus&apos;s itinerary ↗</a></div><div className="viz-card persia-road-viz"><div className="viz-title"><div><span>Itinerary + relay mechanism + administrative archive</span><h4>How did Persia reorganize distance?</h4></div><small>509–480 BCE evidence windows · no speed score</small></div><PersianRoadRelay/><p className="viz-note"><b>Method:</b> The route strip preserves Herodotus&apos;s six segments and relative parasang totals. Traveler time, relay mechanics, and regional administrative practice remain separate evidence classes.</p></div></section>
  {['Satrapies negotiated rule','Tribute was political','Armies were coalitions','Institutions survived dynasties'].map((title,index)=><section className="insight insight-placeholder" key={title}><div className="insight-copy"><span className="insight-number">0{index+2}</span><p className="claim">This argument remains in the evidence audit.</p><h3>{title}</h3><p>The visual will publish only when its sources, definitions, and inference limits are strong enough to support a historical comparison.</p><span className="status status-research">research</span></div></section>)}
</HistoryPageShell>}
