import type { Metadata } from 'next';
import EvidencePanel from '../components/EvidencePanel';
import HistoryPageShell from '../components/HistoryPageShell';
import UrukUrbanizationChart from '../UrukUrbanizationChart';
import UrukWaterChart from '../UrukWaterChart';
import UrukGrainChart from '../UrukGrainChart';
import UrukWritingChart from '../UrukWritingChart';
import UrukFragilityChart from '../UrukFragilityChart';
import ChartFooter from '../components/ChartFooter';

export const metadata:Metadata={
  title:'Uruk and the first states',
  description:'An evidence-led visual history of how cities, landscapes, food, administration, and coercion combined in early Mesopotamia.',
  openGraph:{title:'Uruk and the first states — How Everything Evolved',description:'A visual history of the bundle of systems behind the first Mesopotamian states.',images:[]},
  twitter:{card:'summary',title:'Uruk and the first states — How Everything Evolved',description:'How cities, landscapes, food, administration, and coercion combined in early Mesopotamia.',images:[]},
};

export default function UrukPage(){return <HistoryPageShell
  title="Uruk and the first states"
  eyebrow="First cities · Mesopotamia · information"
  standfirst="The first states were not one invention. Dense settlement, managed landscapes, storable food, accounting, and organized labor reinforced one another."
  status="reviewed"
  progress="5 of 5 insights live"
  published="August 2026"
  insightLabels={['Uruk became the first known city to reach 250 hectares','Uruk grew by domesticating a moving waterscape','Grain gave institutions power because harvests were easy to count and collect','Writing began as institutional memory','Powerful—and fragile—population machines']}
  introduction={<><p>By the late fourth millennium BCE, Uruk was at the center of an urban world unlike the villages that preceded it. But “the state” did not arrive on a single date. Archaeology instead shows overlapping changes in settlement scale, waterways and wetlands, staple production, institutional accounting, labor, ritual, and violence.</p><p>This page asks five ordered questions. Did cities and states develop on the same clock? What ecology sustained concentration? Which foods were easiest for institutions to appropriate? What did the first writing actually record? And why were early states powerful yet fragile?</p><p>All five insights begin with what the evidence can distinguish: approximate settlement footprints are not populations or constitutions; visible palaeochannels are not one dated river map; a global cereal-appropriability model is not a local causal test; surviving proto-cuneiform records do not prove writing was invented solely for taxes; and archaeological contraction, provisioning, or walls do not yield a slavery count or one collapse score.</p></>}
  methods={<><p>This page publishes five arguments. The urbanization chronology keeps settlement footprints, public institutions, record-keeping, and political interpretation in separate lanes. Phase ranges are not annual observations, hectares are not converted into population, and the chart assigns no precise birthday to the state.</p><p>The water visual keeps unlike spatial and chronological evidence apart. Jotheri et al.’s CC BY map is a mixed-age alluvial palimpsest, not a reconstruction of 3300 BCE. Altaweel et al.’s M38 borehole predates Uruk’s urban peak; later directly dated canals and texts constrain what can be claimed but cannot be projected backward into a precise Uruk network.</p><p>The grain visual reproduces two matched 2SLS coefficients from Cook et al.’s replication of Mayshar, Moav, and Pascali: Table 1 column 3 for the full 952-society sample and Table 7 column 3 after winsorizing the thirty-one most cereal-advantaged observations. The one-to-five hierarchy outcome is ordinal, and neither coefficient is a local estimate for Uruk. Direct Late Uruk records, regional deltaic evidence, and later Ur III archive-bias comparisons retain separate roles.</p><p>The writing genre shares reproduce Robert Englund’s language exactly as bounded values: less than 1% lexical for Uruk IV and close to 20% for Uruk III. The corpus counts reproduce Born and Kelley’s 19 May 2020 CDLI snapshot while keeping unlike units on separate axes.</p><p>The fragility ladder preserves eight unlike observations: settlement concentration, disputed provisioning vessels, fortification, excavated conflict and mass deposition, deliberate institutional dispersal, peripheral coexistence, and regional reversal. It assigns no common magnitude, coercion share, disease rate, or causal score. No unpublished Anki text is evidence.</p><EvidencePanel page="uruk" /></>}
>
  <section className="insight uruk-urban-insight"><div className="insight-copy"><span className="insight-number">01</span><h3>Uruk became the first known city to reach 250 hectares</h3><p>By about 3100 BCE, Uruk covered roughly 250 hectares. That was nearly twice the maximum published footprint of Tell Brak, an earlier northern city that had reached about 130 hectares.</p><p>Scale changed what a city could coordinate. Uruk joined dense settlement to monumental precincts, mass production, sealing, accounting, and the earliest surviving proto-cuneiform archives. By the early third millennium its footprint approached 400 hectares.</p><p>Area is not population. Khirbet al-Fakhar covered an even wider 300-hectare scatter earlier, but archaeologists describe it as sparse, discontinuous, short-lived, and possibly seasonal—not a dense city. Uruk’s distinction is the concentration of urban life at unprecedented scale.</p></div><div className="viz-card uruk-urban-viz"><div className="viz-title"><div><span>Published settlement footprints in fourth- and early third-millennium Mesopotamia</span><h4>Uruk became the first known city to reach 250 hectares</h4></div></div><UrukUrbanizationChart/><ChartFooter source="Emberling et al. (2023), McMahon (2020), and Lawrence & Wilkinson (2015)" note="Hectares measure approximate settlement footprints, not population. Survey coverage, density, chronology, and edge definitions differ; Khirbet al-Fakhar was a sparse and possibly seasonal settlement." dataHref="/data/uruk-urbanization-clocks.csv" /></div></section>
  <section className="insight uruk-water-insight"><div className="insight-copy"><span className="insight-number">02</span><h3>Uruk grew by domesticating a moving waterscape</h3><p>Uruk did not rise on an empty desert plain. The southern alluvium was a shifting freshwater mosaic of rivers, marshes, levees, flood basins, fish, reeds, and cultivable ground.</p><p>People made that ecology more reliable and more connected. Geoarchaeology in the Uruk region finds artificial canals superimposed on natural channel patterns, with a long-lived canal interval beginning in the early fourth millennium BCE. Waterways irrigated fields, moved bulky goods, and linked settlements to wetlands and one another.</p><p>That was domestication without total control. Channels migrated, silted, were reopened, and changed function. The resulting infrastructure helped sustain unprecedented urban concentration, but the evidence does not identify one hydraulic bureaucracy—or make water the sole cause of the state.</p></div><div className="viz-card uruk-water-viz"><div className="viz-title"><div><span>Natural channels, artificial canals, irrigation, and transport in southern Mesopotamia</span><h4>Uruk grew by domesticating a moving waterscape</h4></div></div><UrukWaterChart/><ChartFooter source="Jotheri et al. (2018, 2025), Altaweel et al. (2019), and Egberts et al. (2023)" note="The overview map combines channels of different ages, and the preserved Eridu network accumulated over millennia. It demonstrates water management at scale, not a single 3300 BCE canal plan or one central builder." dataHref="/data/uruk-water-ecology.csv" /></div></section>
  <section className="insight uruk-grain-insight"><div className="insight-copy"><span className="insight-number">03</span><h3>Grain gave institutions power because harvests were easy to count and collect</h3><p>Dry cereal harvests made political extraction practical. Grain ripened in a visible season, stood above ground, divided into standard measures, traveled as dry bulk, and survived in storage. Institutions could count it before it disappeared and move it after collection.</p><p>That mechanism is visible at Uruk. Proto-cuneiform accounts classified grain alongside fields, labor, animals, dried fruit, and fish. Writing made obligations durable; measures made unlike deliveries comparable; storage separated collection from later consumption.</p><p>A global study of 952 preindustrial societies found that primary cereal cultivation was associated with greater political hierarchy. A robustness study showed that the estimate weakens when the most cereal-advantaged cases are capped. The comparison supports a serious mechanism, while Uruk’s tablets show how institutions used it.</p></div><div className="viz-card uruk-grain-viz"><div className="viz-title"><div><span>Cereal appropriability, a 952-society comparison, and direct Uruk records</span><h4>Grain gave institutions power because harvests were easy to count and collect</h4></div></div><UrukGrainChart/><ChartFooter source="Mayshar, Moav & Pascali (2022), Cook et al. (2023, 2026), and Late Uruk textual evidence" note="The global estimates use an ordinal hierarchy scale and are not a local causal estimate for Uruk. The archive records institutional attention rather than diet or economic shares; grain was one of several managed resources." dataHref="/data/uruk-grain-state-evidence.csv" /></div></section>
  <section className="insight uruk-writing-insight"><div className="insight-copy"><span className="insight-number">04</span><h3>Writing began as institutional memory</h3><p>Proto-cuneiform appears at Uruk around 3350–3000 BCE. Its first job was not literature. Tablets made deliveries, rations, labor, land, and other institutional transactions durable beyond the people who witnessed them.</p><p>The archive makes that priority visible. In the earliest Uruk IV phase, lexical lists were less than 1% of surviving tablets. Administrative records made up more than 99%. In Uruk III, lexical lists expanded to roughly one fifth as scribes began teaching and organizing the sign system.</p><p>Writing therefore changed what institutions could remember. A claim could travel, be checked, and outlast a conversation. The tablets do not show that writing was invented only for taxation—and the surviving archive is incomplete—but administration overwhelmingly shaped its earliest known use.</p></div><div className="viz-card uruk-writing-viz"><div className="viz-title"><div><span>Administrative records and lexical lists in the surviving proto-cuneiform archive</span><h4>Writing began as institutional memory</h4></div></div><UrukWritingChart/><ChartFooter source="Robert K. Englund (2011), with the ORACC Digital Corpus of Cuneiform Lexical Texts" note="The shares are published descriptions of surviving tablets: less than 1% lexical in Uruk IV and close to 20% in Uruk III. Administrative shares are the complementary remainder; excavation, survival, publication, and classification shape the archive." dataHref="/data/uruk-writing-corpus.csv" /></div></section>
  <section className="insight uruk-fragility-insight"><div className="insight-copy"><span className="insight-number">05</span><p className="claim">Early institutions concentrated people and labor. They never eliminated violence, exit, local autonomy, or reversal.</p><h3>Powerful—and fragile—population machines</h3><p>Concentration was itself a political technology. Northern settlement surveys show rural decline around expanding centers; mass-produced vessels and institutional buildings show provisioning at scale; walls protected dense places and sorted movement through gates.</p><p>None of that made control complete. Hamoukar’s burned buildings preserve more than 1,000 small sling bullets and over 130 heavier clay missiles. At Shakhi Kora, four phases of supra-household food production ended in deliberate dismantling and dispersal. At Hacinebi, a distinct Mesopotamian enclave coexisted with a local community rather than replacing it.</p><p>The result is not a universal collapse theory. A wall is not a coercion rate, a ration bowl is not proof of slavery, and a missing ceramic phase is not a death count. Early states were powerful because they assembled people and resources; they were fragile because people, institutions, and regional ties could reorganize outside the center.</p><a className="source-link" href="https://doi.org/10.15184/aqy.2024.189">Read the reversible-centralization evidence ↗</a></div><div className="viz-card uruk-fragility-viz"><div className="viz-title"><div><span>Archaeological evidence ladder</span><h4>How strong was early-state control?</h4></div><small>4200–3100 BCE · unlike evidence kept separate</small></div><UrukFragilityChart/><p className="viz-note"><b>Method:</b> Site-level excavations, regional surveys, artifact-function debates, and later syntheses keep their own dates and inference limits. Counts are displayed only inside their original case; they are never added, scored, or treated as a common measure of state strength.</p></div></section>
</HistoryPageShell>}
