import type { Metadata } from 'next';
import EvidencePanel from '../components/EvidencePanel';
import HistoryPageShell from '../components/HistoryPageShell';
import UrukUrbanizationChart from '../UrukUrbanizationChart';
import UrukWaterChart from '../UrukWaterChart';
import UrukWritingChart from '../UrukWritingChart';

export const metadata:Metadata={
  title:'Uruk and the first states',
  description:'An evidence-led visual history of how cities, landscapes, food, administration, and coercion combined in early Mesopotamia.',
  openGraph:{title:'Uruk and the first states — How Everything Evolved',description:'A visual history of the bundle of systems behind the first Mesopotamian states.',images:[]},
  twitter:{card:'summary',title:'Uruk and the first states — How Everything Evolved',description:'How cities, landscapes, food, administration, and coercion combined in early Mesopotamia.',images:[]},
};

const ComingSoon=({number,claim,title,children}:{number:string;claim:string;title:string;children:React.ReactNode})=><section className="insight uruk-coming"><div className="insight-copy"><span className="insight-number">{number}</span><p className="claim">{claim}</p><h3>{title}</h3><div>{children}</div><span className="research-state">Evidence audit in progress</span></div><div className="uruk-placeholder" aria-label={`${title} visualization is being researched`}><span>{number}</span><div><b>Visualization under evidence review</b><p>This panel will go live only when its chronology, geography, definitions, and source keys can be audited.</p></div></div></section>;

export default function UrukPage(){return <HistoryPageShell
  title="Uruk and the first states"
  eyebrow="First cities · Mesopotamia · information"
  standfirst="The first states were not one invention. Dense settlement, managed landscapes, storable food, accounting, and organized labor reinforced one another."
  status="draft"
  progress="3 of 5 insights live"
  published="August 2026"
  insightHeading={<>Before states ruled territory,<br/>institutions learned to count.</>}
  introduction={<><p>By the late fourth millennium BCE, Uruk was at the center of an urban world unlike the villages that preceded it. But “the state” did not arrive on a single date. Archaeology instead shows overlapping changes in settlement scale, waterways and wetlands, staple production, institutional accounting, labor, ritual, and violence.</p><p>This page asks five ordered questions. Did cities and states develop on the same clock? What ecology sustained concentration? Which foods were easiest for institutions to appropriate? What did the first writing actually record? And why were early states powerful yet fragile?</p><p>The three live insights begin with what the evidence can distinguish: approximate settlement footprints are not populations or constitutions; visible palaeochannels are not one dated river map; and surviving proto-cuneiform records support an administrative origin without proving that writing was invented solely for taxes.</p></>}
  methods={<><p>This draft publishes three of five planned arguments. The urbanization chronology keeps settlement footprints, public institutions, record-keeping, and political interpretation in separate lanes. Phase ranges are not annual observations, hectares are not converted into population, and the chart assigns no precise birthday to the state.</p><p>The water visual keeps unlike spatial and chronological evidence apart. Jotheri et al.’s CC BY map is a mixed-age alluvial palimpsest, not a reconstruction of 3300 BCE. Altaweel et al.’s M38 borehole predates Uruk’s urban peak; later directly dated canals and texts constrain what can be claimed but cannot be projected backward into a precise Uruk network.</p><p>The writing genre shares reproduce Robert Englund’s language exactly as bounded values: less than 1% lexical for Uruk IV and close to 20% for Uruk III. The corpus counts reproduce Born and Kelley’s 19 May 2020 CDLI snapshot while keeping unlike units on separate axes.</p><p>The broader five-part thesis remains provisional. In particular, the “grain made people taxable” argument is a hypothesis to test against wetland subsistence, pastoralism, crop choice, settlement archaeology, and competing explanations. No unpublished Anki text is evidence.</p><EvidencePanel page="uruk" /></>}
>
  <section className="insight uruk-urban-insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">Uruk did not become a city and a state in one leap. Scale, public institutions, records, and political power ran on different clocks.</p><h3>There is no single birthday for the city-state</h3><p>Uruk’s visible footprint was enormous by the end of the fourth millennium: about 250 hectares around 3100 BCE and roughly 400 hectares in the early third millennium. But hectares measure a settlement edge, not a constitution—or even a population.</p><p>Other parts of Mesopotamia already had large settlements and public institutions. Tell Brak expanded from about 55 to 130 hectares, and institutional food production at Shakhi Kora is radiocarbon-bounded to 3941–3377 cal BCE. Those paths were local, plural, and sometimes reversible.</p><p>At Uruk, monumental building, sealing, accounting, writing, and a wider political economy became mutually reinforcing. Scholars reasonably describe an emergent state during the fourth millennium, but the sources do not give us a dated first king or unequivocal proof of monocratic rule.</p><a className="source-link" href="https://doi.org/10.15184/aqy.2024.189">Read the current institutional evidence ↗</a></div><div className="viz-card uruk-urban-viz"><div className="viz-title"><div><span>Urban footprint + institutional chronology</span><h4>When did Uruk become a state?</h4></div><small>4400–2900 BCE · four evidence clocks</small></div><UrukUrbanizationChart/><p className="viz-note"><b>Method:</b> Archaeological date ranges, settlement footprints, and scholarly political interpretations retain separate lanes and evidence labels. Footprint observations are not interpolated into annual growth or converted into population.</p></div></section>
  <section className="insight uruk-water-insight"><div className="insight-copy"><span className="insight-number">02</span><p className="claim">Uruk’s concentration depended on a moving freshwater–marsh mosaic—but the surviving evidence cannot be turned into one clean fourth-millennium river map.</p><h3>Water made concentration possible, not inevitable</h3><p>Southern Mesopotamia was not a dry plain waiting for engineers. A borehole near the Uruk–Larsa region records freshwater conditions from roughly 7750 to 4900 BCE and an alternating mosaic of marsh, river edge, overbank deposition, and floodplain. This was an environment of changing water, plants, fish, fields, and transport.</p><p>People amplified that ecology. Levees made gravity irrigation possible; crevasse splays could become local canals; channels connected fields, settlements, and marshes. The preserved Eridu landscape contains more than 200 primary canals, 4,000 branches, and 700 farms—but those traces accumulated across occupations from the sixth to early first millennium BCE. They never formed one simultaneous system.</p><p>That chronological mismatch is the point. Remote sensing reveals an extraordinary hydraulic landscape, while directly dated canal deposits and developed irrigation terminology are later than Uruk’s principal urban expansion. Water enabled concentration. The evidence does not show that one hydraulic bureaucracy created the first state.</p><a className="source-link" href="https://doi.org/10.15184/aqy.2025.19">Explore the open canal study ↗</a></div><div className="viz-card uruk-water-viz"><div className="viz-title"><div><span>Floodplain map + evidence chronology</span><h4>Can we map the water beneath Uruk?</h4></div><small>9700–1000 BCE · no invented Uruk river layer</small></div><UrukWaterChart/><p className="viz-note"><b>Method:</b> Published palaeochannels, a local borehole sequence, a regional climate synthesis, later canal stratigraphy, and textual evidence remain separate. The map shows visible channel traces of mixed age, while the chronology shows why none can be assigned wholesale to Uruk’s fourth-millennium peak.</p></div></section>
  <ComingSoon number="03" claim="Storable cereals were legible to institutions—but they were only one part of a mixed subsistence landscape." title="Test the grain-state hypothesis"><p>Grain is divisible, measurable, transportable, and storable. That makes it attractive to tax collectors. It does not prove grain alone caused states, so this comparison will include tubers, animals, fish, dates, and the archaeological record of actual extraction.</p></ComingSoon>
  <section className="insight uruk-writing-insight"><div className="insight-copy"><span className="insight-number">04</span><p className="claim">The earliest surviving writing was overwhelmingly administrative; a broader scribal knowledge system grew alongside it.</p><h3>Writing began by making transactions durable</h3><p>Proto-cuneiform appears on tablets at Uruk around 3350–3000 BCE. The records counted and classified goods, people, land, work, and institutional transactions. They were not yet prose: numerical systems, signs, layout, and sealings carried much of the meaning.</p><p>In the earliest Uruk IV phase, less than 1% of known tablets were lexical lists. In the following Uruk III phase, lexical texts were close to 20%. Administrators did more than keep accounts: they built lists that taught, standardized, and explored the new sign system.</p><p>That distinction matters. “Writing began as administration” is well supported. “Writing was invented only to collect grain taxes” is not. The physical and symbolic precursors were diverse, many signs remain contested, and the surviving archive is a filtered sample.</p><a className="source-link" href="https://doi.org/10.1093/oxfordhb/9780199557301.013.0002">Read Englund’s evidence review ↗</a></div><div className="viz-card uruk-writing-viz"><div className="viz-title"><div><span>Archive composition + corpus attrition</span><h4>What did the first writing do?</h4></div><small>Uruk IV–III · no invented annual series</small></div><UrukWritingChart/><p className="viz-note"><b>Method:</b> Genre shares are published bounded descriptions, not recomputed observations. CDLI corpus counts describe a 2020 digital snapshot; they do not correct for excavation, survival, publication, or legibility bias.</p></div></section>
  <ComingSoon number="05" claim="Early states could organize remarkable concentrations of labor while remaining vulnerable to dispersal, conflict, ecology, and exit." title="Powerful—and fragile—population machines"><p>The final visual will compare walls, institutional labor, settlement dispersal, conflict, and evidence for populations outside state control. It will not reduce collapse to one score or assume that leaving a city meant civilizational failure.</p></ComingSoon>
</HistoryPageShell>}
