import type { Metadata } from 'next';
import CradlesEcologyProfiles from '../CradlesEcologyProfiles';
import CradlesEvidenceClocks from '../CradlesEvidenceClocks';
import CradlesSequenceClocks from '../CradlesSequenceClocks';
import CradlesCoordinationRoutes from '../CradlesCoordinationRoutes';
import CradlesAfterlives from '../CradlesAfterlives';
import ChartFooter from '../components/ChartFooter';
import EvidencePanel from '../components/EvidencePanel';
import HistoryPageShell from '../components/HistoryPageShell';

export const metadata:Metadata={
  title:'The cradles of civilization',
  description:'How cities, states, writing, infrastructure, and political life emerged across six early regional systems.',
  openGraph:{title:'The cradles of civilization — How Everything Evolved',description:'Five visual claims about how the first cities formed, worked, and changed.',images:[]},
  twitter:{card:'summary',title:'The cradles of civilization — How Everything Evolved',description:'Five visual claims about how the first cities formed, worked, and changed.',images:[]},
};

export default function CradlesPage(){return <HistoryPageShell
  title="The cradles of civilization"
  eyebrow="First cities · six regions · comparative archaeology"
  standfirst="Cities, states, and writing did not arrive as one package—or on one civilizational clock."
  status="reviewed"
  progress="5 of 5 insights live"
  published="August 2026"
  introduction={<><p>The first cities and states did not radiate from one origin. Mesopotamia, Egypt, the Indus, northern China, Mesoamerica, and the Andes concentrated people and political power through different ecologies, technologies, and institutions.</p><p>These five comparisons ask when urban life appeared, how communities managed water, which tools were optional, how surplus became organized power, and what happened when early capitals broke apart.</p></>}
  insightLabels={['Cities, states, and writing emerged on different schedules','The first cities adapted to radically different water regimes','Cities and states could appear without writing or bronze','Records, standards, markets, and monuments turned surplus into power','Capitals fell, but people and institutions reorganized']}
  methods={<><p>The comparison begins with Cowgill’s dimensional approach to urbanism and Spencer’s six-region territorial-expansion model, then checks each regional clock against specialist work. The shared frame is useful, but neither source turns “primary state” into an uncontested category.</p><p>Rows preserve evidence status: archaeological attestation, published synthesis, scholarly inference, contested inference, undeciphered notation, or evidence gap. Political centralization is never inferred from city size alone. The Indus row does not invent a ruling dynasty; the San Andrés row remains probable and contested; earlier Chinese signs are not promoted into secure writing; and the Andes notation lane is left undated rather than plotted at zero.</p><p>The ecology comparison is a thirty-cell qualitative matrix, not a model output. Water, rainfall, crops, transport, and settlement form keep their own place, period, source keys, and limits. “Settlement form” is used instead of a shared density number because preservation, survey coverage, and population models are not comparable enough to support one.</p><p>The five-clock sequence reuses the audited city, state, and notation rows, then adds bronze and monumental-building evidence. “Bronze” deliberately means different defensible thresholds in different source traditions—rare attestation, sustained use, analytical assemblage, or regional scaling—and every row states that limit. The 4000 BCE–1550 CE axis exists to make the very late Mesoamerican and Andean alloy clocks visible, not to imply annual continuity.</p><p>The coordination comparison follows twenty-four input → institution → outcome routes. Four routes per region are an editorial sampling frame, not an institutional-diversity count. Unlike archives, workshops, weights, marketplaces, water works, and monuments are not converted into a common capacity score. Every route states what it cannot establish about quantities, coercion, hierarchy, or central control.</p><p>The afterlives comparison follows six bounded case studies instead of a collapse curve. Crawford and colleagues define settlement persistence as continuous use of a well-defined place; this page therefore refuses to treat occupation, population, political authority, records, and institutions as interchangeable kinds of continuity. Every pathway states its geographic scope and inference limit.</p><p>Map points locate regional cases, not political boundaries. Timeline ranges are visual comparisons of published phases and dated contexts; they are not confidence intervals, civilizational scores, or proof that the feature appearing first caused the others.</p><EvidencePanel page="cradles"/></>}
>
  <section className="insight cradles-clock-insight"><div className="insight-copy"><span className="insight-number">01</span><h3>Cities, states, and writing emerged on different schedules</h3><p>Mesopotamia and Egypt compressed urban concentration, territorial rule, and durable notation into several centuries. Other regions separated those changes by much longer intervals.</p><p>Taosi’s walled center preceded the Erlitou state model and secure Shang writing. The Indus built vast planned cities and shared standards without securely identified kings or a deciphered script. Caral reached monumental urban scale long before the regional state clock used here, while no accepted early Andean script date can be plotted.</p><p>Urban life was therefore not one invention that switched on everywhere at once. It was a recurring combination of settlement, authority, and information systems assembled in different orders.</p></div><div className="viz-card cradles-clock-viz"><div className="viz-title"><div><span>Urban scale, political centralization, and durable notation across six regions</span><h4>Cities, states, and writing emerged on different schedules</h4></div></div><CradlesEvidenceClocks/><ChartFooter source="Cowgill (2004), Spencer (2010), and regional archaeological syntheses" note="Ranges preserve published phases rather than annual estimates. Map points locate evidence cases, not ancient borders; political centralization remains a scholarly inference, and the Andean notation gap is left undated." dataHref="/data/cradles-evidence-clocks.csv" /></div></section>
  <section className="insight cradles-ecology-insight"><div className="insight-copy"><span className="insight-number">02</span><h3>The first cities adapted to radically different water regimes</h3><p>Southern Mesopotamia grew in a shifting river-and-marsh mosaic. Egypt concentrated life along a narrow annual floodplain. Indus communities crossed winter and summer rainfall systems, while northern Chinese centers used dry loess platforms and river terraces.</p><p>Monte Albán relied on seasonal rain, household water works, and marketplace links from a hilltop. Caral connected irrigated desert valleys to rich coastal fisheries through cotton, crops, and marine food.</p><p>Water mattered everywhere, but through different combinations of floods, rainfall, canals, local storage, transport, and exchange. The first cities adapted their institutions to those local regimes.</p></div><div className="viz-card cradles-ecology-viz"><div className="viz-title"><div><span>Water, rainfall, crops, transport, and settlement across six regions</span><h4>The first cities adapted to radically different water regimes</h4></div></div><CradlesEcologyProfiles/><ChartFooter source="Regional environmental archaeology summarized in the Cradles evidence registry" note="The thirty cells are qualitative comparisons, not measurements on a common scale. They do not identify one hydraulic cause, crop share, traffic volume, or settlement-density score." dataHref="/data/cradles-ecology-profiles.csv" /></div></section>
  <section className="insight cradles-sequence-insight"><div className="insight-copy"><span className="insight-number">03</span><h3>Cities and states could appear without writing or bronze</h3><p>In Mesopotamia and Egypt, cities, state institutions, monuments, and notation clustered within several centuries; widespread bronze use followed. Elsewhere the sequence spread across millennia.</p><p>Taosi’s monumental center preceded scaled bronze casting and secure Chinese writing. Caral’s urban concentration came more than three millennia before the Andean bronze transition shown here, without an accepted early script date. Mesoamerican monuments and probable notation also appeared long before West Mexican bronze alloys.</p><p>Writing and bronze became powerful tools, but neither was a universal prerequisite for urban life or political centralization.</p></div><div className="viz-card cradles-sequence-viz"><div className="viz-title"><div><span>Cities, states, notation, monuments, and bronze across six regions</span><h4>Cities and states could appear without writing or bronze</h4></div></div><CradlesSequenceClocks/><ChartFooter source="Regional urban, political, inscription, monument, and metallurgy chronologies" note="Ranges preserve phase evidence rather than invention dates or annual continuity. Bronze rows use source-specific thresholds, tied ordinal positions share a rank, and missing evidence remains undated." dataHref="/data/cradles-sequence-clocks.csv" /></div></section>
  <section className="insight cradles-coordination-insight"><div className="insight-copy"><span className="insight-number">04</span><h3>Records, standards, markets, and monuments turned surplus into power</h3><p>Food and materials became politically useful only when institutions could count, store, transform, move, or mobilize them. Mesopotamian tablets tracked obligations; Egyptian breweries and workshops organized production; Taosi and Erlitou concentrated storage, crafts, and access.</p><p>The Indus coordinated cities through shared weights, seals, streets, and drains without a recovered dynasty. Monte Albán joined household production to marketplaces and distributed water works. Aguada Fénix assembled enormous communal labor before familiar Maya royal courts.</p><p>Caral linked irrigated valleys, cotton-dependent fisheries, maize, and monumental gathering. The shared mechanism was not one staple or bureaucracy, but institutions that converted resources into coordinated action.</p></div><div className="viz-card cradles-coordination-viz"><div className="viz-title"><div><span>Inputs, coordinating institutions, and visible outcomes across six regions</span><h4>Records, standards, markets, and monuments turned surplus into power</h4></div></div><CradlesCoordinationRoutes/><ChartFooter source="Twenty-four source-bounded institutional routes in the Cradles evidence registry" note="The routes are qualitative evidence chains, not equal observations or a common state-capacity scale. They do not establish quantities, coercion, ownership, or centralized control where the underlying evidence cannot." dataHref="/data/cradles-coordination-routes.csv" /></div></section>
  <section className="insight cradles-afterlives-insight"><div className="insight-copy"><span className="insight-number">05</span><h3>Capitals fell, but people and institutions reorganized</h3><p>Shakhi Kora’s residents dismantled a centralizing institution and dispersed. Taosi’s monumental core was destroyed, yet occupation continued after it lost capital status. In Egypt, authority was rebuilt from Thebes as Karnak and a new capital grew.</p><p>The Indus transformation shifted settlement toward smaller centers and regional traditions. Monte Albán fragmented while secondary Oaxacan centers changed on their own schedules. Caral’s monumental system ended, although the evidence does not reveal every destination or successor.</p><p>The end of a capital was therefore not the end of its entire society. Political authority, settlement, population, and institutions could separate and take new forms.</p></div><div className="viz-card cradles-afterlives-viz"><div className="viz-title"><div><span>Before, political break, and visible afterlife in six regional cases</span><h4>Capitals fell, but people and institutions reorganized</h4></div></div><CradlesAfterlives/><ChartFooter source="Six regional archaeological transition studies summarized in the Cradles evidence registry" note="The cases are unlike pathways rather than a collapse rate. Site occupation does not prove social continuity, and the evidence does not identify every cause, migrant destination, dynastic identity, or direct successor." dataHref="/data/cradles-afterlives.csv" /></div></section>
</HistoryPageShell>}
