import type { Metadata } from 'next';
import CradlesEcologyProfiles from '../CradlesEcologyProfiles';
import CradlesEvidenceClocks from '../CradlesEvidenceClocks';
import CradlesSequenceClocks from '../CradlesSequenceClocks';
import CradlesCoordinationRoutes from '../CradlesCoordinationRoutes';
import CradlesAfterlives from '../CradlesAfterlives';
import EvidencePanel from '../components/EvidencePanel';
import HistoryPageShell from '../components/HistoryPageShell';

export const metadata:Metadata={
  title:'The cradles of civilization',
  description:'Compare the different clocks, ecologies, institutions, and historical afterlives of six early regional systems.',
  openGraph:{title:'The cradles of civilization — How Everything Evolved',description:'Six regions, different clocks, coordination routes, and afterlives—no civilizational league table.',images:[]},
  twitter:{card:'summary',title:'The cradles of civilization — How Everything Evolved',description:'Six regions, different clocks, coordination routes, and afterlives—no civilizational league table.',images:[]},
};

export default function CradlesPage(){return <HistoryPageShell
  title="The cradles of civilization"
  eyebrow="First cities · six regions · comparative archaeology"
  standfirst="Cities, states, and writing did not arrive as one package—or on one civilizational clock."
  status="reviewed"
  progress="5 of 5 insights live"
  published="August 2026"
  introduction={<><p>“The cradles of civilization” sounds like a list of places with birthdays. The evidence is less tidy. Large settlements can precede territorial states. Durable signs can appear before urban consolidation—or remain undeciphered. Administration can leave monumental architecture without a securely accepted script.</p><p>This page compares six regions frequently used in debates about independent urban and state formation: Mesopotamia, Egypt, the Indus, northern China, Mesoamerica, and the Andes. The list is a research frame, not a ranking or a claim that development stopped at six centers.</p><p>The five insights separate institutional clocks, environmental pathways, technology sequences, coordination systems, and historical afterlives. Together they show why neither “civilization” nor “collapse” can be reduced to one score: places, people, capitals, records, and institutions each change on different clocks.</p></>}
  insightLabels={['Cities, states, and writing emerged on different clocks','Early cities grew from different ecological combinations','Civilization did not arrive as one technological package','Surplus became power through different coordinating institutions','Cities, states, and institutions did not share one kind of collapse']}
  methods={<><p>The comparison begins with Cowgill’s dimensional approach to urbanism and Spencer’s six-region territorial-expansion model, then checks each regional clock against specialist work. The shared frame is useful, but neither source turns “primary state” into an uncontested category.</p><p>Rows preserve evidence status: archaeological attestation, published synthesis, scholarly inference, contested inference, undeciphered notation, or evidence gap. Political centralization is never inferred from city size alone. The Indus row does not invent a ruling dynasty; the San Andrés row remains probable and contested; earlier Chinese signs are not promoted into secure writing; and the Andes notation lane is left undated rather than plotted at zero.</p><p>The ecology comparison is a thirty-cell qualitative matrix, not a model output. Water, rainfall, crops, transport, and settlement form keep their own place, period, source keys, and limits. “Settlement form” is used instead of a shared density number because preservation, survey coverage, and population models are not comparable enough to support one.</p><p>The five-clock sequence reuses the audited city, state, and notation rows, then adds bronze and monumental-building evidence. “Bronze” deliberately means different defensible thresholds in different source traditions—rare attestation, sustained use, analytical assemblage, or regional scaling—and every row states that limit. The 4000 BCE–1550 CE axis exists to make the very late Mesoamerican and Andean alloy clocks visible, not to imply annual continuity.</p><p>The coordination comparison follows twenty-four input → institution → outcome routes. Four routes per region are an editorial sampling frame, not an institutional-diversity count. Unlike archives, workshops, weights, marketplaces, water works, and monuments are not converted into a common capacity score. Every route states what it cannot establish about quantities, coercion, hierarchy, or central control.</p><p>The afterlives comparison follows six bounded case studies instead of a collapse curve. Crawford and colleagues define settlement persistence as continuous use of a well-defined place; this page therefore refuses to treat occupation, population, political authority, records, and institutions as interchangeable kinds of continuity. Every pathway states its geographic scope and inference limit.</p><p>Map points locate regional cases, not political boundaries. Timeline ranges are visual comparisons of published phases and dated contexts; they are not confidence intervals, civilizational scores, or proof that the feature appearing first caused the others.</p><EvidencePanel page="cradles"/></>}
>
  <section className="insight cradles-clock-insight"><div className="insight-copy"><span className="insight-number">01</span><p className="claim">The first cities, states, and writing systems emerged on different clocks—even within the same region.</p><h3>There was no single civilizational takeoff</h3><p>Mesopotamia and Egypt show relatively compressed sequences: urban concentration, territorial rule, and durable notation become visible within several centuries. Elsewhere the clocks separate sharply. Taosi precedes the Erlitou state model and secure Shang writing. San Andrés notation may precede Monte Albán’s regional state.</p><p>The Indus is a warning against reading institutions from monuments. Its vast planned cities and shared standards do not come with securely identified kings, royal tombs, or palaces; its sign system remains undeciphered. Complexity did not require the political forms archaeologists once expected to find.</p><p>The Andes make the strongest case for showing absence honestly. Caral’s urban and monumental concentration is early. A probable regional state clock appears much later at Virú. There is no securely accepted early script clock to plot here—and that is an evidence gap, not zero administration.</p><a className="source-link" href="https://doi.org/10.1073/pnas.1002470107">Read the six-region comparative model ↗</a></div><div className="viz-card cradles-clock-viz"><div className="viz-title"><div><span>Six regions · three evidence clocks</span><h4>What emerged—and when?</h4></div><small>4000–100 BCE · no civilization score</small></div><CradlesEvidenceClocks/><p className="viz-note"><b>Method:</b> Select a region, then select a lane. Ranges preserve archaeological phases or published syntheses. They are not annual estimates. The map shows evidence locations, not territorial boundaries or independent-invention certainty.</p></div></section>
  <section className="insight cradles-ecology-insight"><div className="insight-copy"><span className="insight-number">02</span><p className="claim">Early cities grew from different combinations of water, crops, mobility, and settlement—not one hydraulic formula.</p><h3>There was no single environmental recipe</h3><p>Rivers mattered everywhere, but not in the same way. Southern Mesopotamia was a shifting freshwater–marsh mosaic. Egypt concentrated people along a narrow floodplain. Indus communities crossed overlapping winter and summer rainfall systems. Northern Chinese centers used dry loess platforms and river terraces without becoming wet-rice states.</p><p>The strongest counterexamples sit outside a simple great-river story. Monte Albán grew on a defensible hilltop with unreliable rainfall, household-scale water works, and marketplace links to the valley. Caral joined irrigated coastal valleys to an exceptionally productive fishery; cotton, orchards, maize, and marine protein entered the argument on different evidentiary clocks.</p><p>The result is not that ecology did not matter. It mattered so specifically that a single score would erase the mechanism. Read down to see one regional fingerprint, then read across to compare one dimension while keeping every source limit visible.</p><a className="source-link" href="https://doi.org/10.3389/fpos.2022.805047">Read the open Monte Albán ecology study ↗</a></div><div className="viz-card cradles-ecology-viz"><div className="viz-title"><div><span>Six regions · five ecological dimensions</span><h4>Six ways to sustain concentration</h4></div><small>30 sourced observations · no hydraulic score</small></div><CradlesEcologyProfiles/><p className="viz-note"><b>Method:</b> The cards and comparison rows are qualitative evidence summaries, not measurements on a shared scale. Select a region to read its five-part profile, or select a dimension to compare all six. Each cell exposes the reason it cannot be generalized.</p></div></section>
  <section className="insight cradles-sequence-insight"><div className="insight-copy"><span className="insight-number">03</span><p className="claim">In this comparison, the bronze clock never precedes every city, state, notation, or monument clock.</p><h3>Civilization did not arrive as a package</h3><p>In Mesopotamia and Egypt, urban concentration, political centralization, monuments, and notation cluster within a few centuries; sustained or common bronze use follows. At Taosi, a walled monumental center precedes the Erlitou state model and scaled bronze casting, while secure writing appears later still.</p><p>The Americas break the package apart. Caral’s monumental concentration is more than two millennia earlier than the probable Virú state clock and over three millennia earlier than the regional Tiwanaku–Wari bronze transition shown here. Mesoamerican monuments and probable notation are visible long before West Mexican bronze alloys.</p><p>The point is not that bronze was unimportant. It is that “Bronze Age” is a regional materials history, not a universal prerequisite for urban life. Select a region to inspect its phase evidence, then compare the ordinal signatures without turning earlier into better.</p><a className="source-link" href="https://doi.org/10.15184/aqy.2025.41">Read the bronze-transition synthesis ↗</a></div><div className="viz-card cradles-sequence-viz"><div className="viz-title"><div><span>Six regions · five evidence clocks</span><h4>Five milestones, six different sequences</h4></div><small>4000 BCE–1550 CE · bronze is not a score</small></div><CradlesSequenceClocks/><p className="viz-note"><b>Method:</b> Ranges preserve phases, analytical assemblages, or published transition windows. Tied ordinal numbers mean the current evidence cannot order those clocks more finely. Missing evidence remains undated; bronze rows distinguish rare objects, sustained use, and later regional scaling.</p></div></section>
  <section className="insight cradles-coordination-insight"><div className="insight-copy"><span className="insight-number">04</span><p className="claim">Surplus did not organize itself. Early cities made resources usable through different mixes of records, workshops, standards, exchange, public works, and communal labor.</p><h3>There was no single route from grain to state power</h3><p>Mesopotamian tablets made selected obligations legible; institutional kitchens provisioned groups. Predynastic Egyptian breweries and workshops coordinated production beyond one household. Taosi separated storage and craft districts, while Erlitou placed specialist production near a planned political core.</p><p>But centralized storage was not the only answer. Shared weights, seals, streets, and drains coordinated the Indus world without a recovered dynasty. Monte Albán grew through household intensification, marketplaces, and distributed water works. Aguada Fénix assembled extraordinary communal labor before the familiar Maya royal court.</p><p>Caral joined irrigated valleys, cotton-dependent fisheries, maize, and monumental gathering. None of these routes can be ranked in one unit. The argument is institutional: abundance became politically consequential only when people created ways to record, move, transform, or collectively use it.</p><a className="source-link" href="https://www.cambridge.org/core/journals/antiquity/article/inequality-declined-in-the-bronze-age-city-of-mohenjodaro/BF07ED4E516F2127F1C3E645C9C8F462">Read the open Indus public-goods study ↗</a></div><div className="viz-card cradles-coordination-viz"><div className="viz-title"><div><span>Six regions · twenty-four institutional routes</span><h4>How did resources become coordination?</h4></div><small>inputs → institutions → outcomes · no capacity score</small></div><CradlesCoordinationRoutes/><p className="viz-note"><b>Method:</b> Select a region, then a route. Each row is a qualitative evidence chain with its own chronology and inference limit. Four routes per region make the comparison inspectable; they are not a count of everything the society did.</p></div></section>
  <section className="insight cradles-afterlives-insight"><div className="insight-copy"><span className="insight-number">05</span><p className="claim">A city can empty, a capital can fall, or a state can fragment without its people and institutions sharing one fate.</p><h3>There was no single kind of collapse</h3><p>Shakhi Kora’s residents deliberately dismantled a centralizing arrangement and dispersed. Taosi’s monumental political core was destroyed, but occupation continued after it ceased to be a capital. In Egypt, authority was rebuilt from Thebes while Karnak and a new capital developed around a shifting Nile bank.</p><p>The Indus transformation was a deurbanization and regional shift, not evidence that its population disappeared. Monte Albán fragmented while secondary Oaxacan centers changed on different schedules. At Caral, a proposed chain of environmental hazards remains a hypothesis; the record does not reveal every destination or successor.</p><p>“Collapse” is useful only after naming what ended. Sites, populations, political orders, archives, and institutions can each persist—or become archaeologically unreadable—on different clocks.</p><a className="source-link" href="https://doi.org/10.15184/aqy.2022.175">Read the settlement-persistence method ↗</a></div><div className="viz-card cradles-afterlives-viz"><div className="viz-title"><div><span>Six regions · six unlike transitions</span><h4>What actually ended?</h4></div><small>before → break → afterlife · no collapse score</small></div><CradlesAfterlives/><p className="viz-note"><b>Method:</b> Select a case to follow one evidence-bounded pathway. The six chronologies are not synchronized, and the pathway labels are not ranks. “Afterlife” means what is archaeologically visible after the transition—not proof of unchanged identity or direct descent.</p></div></section>
</HistoryPageShell>}
